moby/swarmkit

manager/manager_test.go

This fixes a data race.
cc @cyli

manager: Test must hold lock when calling becomeFollower

---

manager/logbroker/broker.go

This is a possible fix for #1974. It makes lb.connectedNodes also index a node's subscriptions, so that they can be `Done()`'d when the node is dropped, safely under the protection of a mutex.
I haven't thoroughly tested this code, and it probably needs a test written to make sure this works. This PR is mostly for design review, to make sure I'm going in the right direction here before I spend a bunch more time finishing it out.
/cc @aaronlehmann

Fix possible race in ListenSubscriptions

---

manager/controlapi/network.go

`RemoveNetwork` currently won't allow a network to be removed if any task in the store references it. This is a change relative to Docker 1.12, where only services were checked.
This might be a little heavy handed. Some tasks in the store may be long dead. Resource attachment tasks, in particular, must be detached by the API user, and this might be neglected after a failure.
Change `RemoveNetwork` to only fail the network deletion if a task has actual and desired state of "running" or below. This means that neither a failed resource attachment task (whose desired state won't be adjusted) or a down node (where actual state won't reflect desired state) can block the network deletion.
There may be some corner cases where deleting the network while a task is in the process of shutting down …

controlapi: Allow removal of network when only dead tasks reference it

---

manager/allocator/allocator_test.go
manager/allocator/network.go

Instead of retrying unallocated tasks, services, and networks every time data changes in the store, limit these retries to every 5 minutes.
When a repeated attempt to allocate one of these objects fails, log it at the debug log level, to reduce noise in the logs.
cc @alexmavr @yongtang @aboch

allocator: Less aggressive retry

---

agent/exec/dockerapi/adapter.go

Before this PR, attempting to do logs on service with TTY was undefined behavior and caused `~*~*~weird errors~*~*~`. This doesn't fix that, but disallows the undefined behavior until we do.

Error when attempting to do logs on TTY service

---

manager/allocator/network.go

If a service update caused the service to be successfully allocated, that service should be removed from `unallocatedServices`.
If the allocation was unsuccessful, `unallocatedServices` should be updated to contain the latest version of the service.
cc @alexmavr @yongtang @aboch

allocator: Update unallocatedServices properly after service updates

---

manager/allocator/network.go

This looks like an oversight. Networks may have been kept in this set
forever after deletion.
cc @alexmavr @yongtang @aboch

allocator: Remove deleted networks from the unallocated set

---

ca/certificates.go
ca/certificates_test.go
ca/external.go
ca/external_test.go
ca/testutils/externalutils.go

This PR provides 2 ways of creating cross-signed roots, to be used as intermediates during root rotation:
1.  Take a certificate, and cross-sign the certificate.  This can be used when rotating from `internal->internal`, and `internal->external`.
2. Generate a CA CSR from the root certificate, and submit it to an external CA to be signed as an intermediate.  This can be used when rotating from external->internal.
`external->external` cannot be supported without adding an extra API to the external signing server (either taking query parameters, or adding a new URL) in order for the external CA to also just sign an intermediate using just a certificate (because we need the private key material in order to generate an actual CSR).
After further discussion with @diogomonica  and @jlhawn , we …

[ca] Add utility to create cross-signed roots to the RootCA.

---

manager/allocator/network.go

The allocator currently uses `taskDead` to check if a task should not be allocated. However, this checks that both the desired state and actual state are past "running". In the case of network attachment tasks, there is no orchestration, and the desired state is always "running". This means allocation can be reattempted on a failed attachment task indefinitely.
Change the allocator to only try to allocate tasks where both the desired and actual state are "running" or below.
Technically we could probably exclude any task which is at "pending" or beyond, because these have already been allocated, but I'm less confident in that.
cc @alexmavr @yongtang @aboch @dongluochen

allocator: Avoid allocating tasks that are no longer running

---

ca/certificates.go
ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/external.go
ca/external_test.go
ca/testutils/cautils.go
ca/testutils/staticcerts.go

Part of addressing intermediate support in https://github.com/docker/swarmkit/issues/1990.

ca: Add support for appending intermediates to issued TLS certs

---

manager/scheduler/scheduler.go

Tasks are split between task groups based on common specs. This allows
nodes to only be ranked once per group, not once per task.
This logic doesn't work correctly because maps are marshalled in a
random order. Currently, the same task can end up in a multiple groups
(say, if it's updated multiple times, and the marshalling ends up being
different). To make sure we don't try to schedule the same task twice
within the same batch, use a map for unassignedTasks instead of a linked
list.
Note this doesn't fix the brokenness of task spec deduplication based on
marshalling the protobuf. This is a fix for the symptom that can be
backported, and I'm going to replace the marshalling stuff in a
different PR.

scheduler: Fix accounting when task ends up in multiple groups

---

manager/scheduler/nodeset.go

Each node in the decision tree has a count of tasks assigned at or below
that node. The bottom level did not have this count populated. Fix this
so that topology-aware scheduling works correctly when tasks are
scheduled individually.
Test coverage for this is coming in the next PR.

scheduler: Correctly count tasks at bottom level of decision tree

---

BUILDING.md
CONTRIBUTING.md
design/topology.md

Spaces, it is aligned to view codes with any editor, including the web page views (such as in the GitHub code). When use tabs, the view on the page is chaos, and it is terrible to mix tabs and spaces.
Signed-off-by: yupengzte <yu.peng36@zte.com.cn>

Replace the tab with 4 spaces in md files

---

ca/certificates.go
ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/external.go
ca/external_test.go
ca/server.go
ca/testutils/cautils.go
ca/testutils/externalutils.go
cmd/external-ca-example/main.go
integration/integration_test.go
integration/node.go
manager/manager.go
manager/manager_test.go
node/node_test.go

Since in theory, we could be signing with an intermediate certificate, which should not be used as a trust root.
This is useful both for supporting offline roots, and for supporting swarm root CA rotation (in which the root we trust is still the old root, but we will be signing with a cross-signed intermediate, which can easily be switched to the new root.
For more context on how this will be used in terms of root CA rotation, please see https://github.com/docker/swarmkit/pull/2037.  ([or just the diff](https://github.com/docker/swarmkit/compare/7c78bfad7a4792f88cc050dbcf516dec9f1c9367...4d7bb0df1ff8660e7887c230b56c565063e357ef))
I made it a requirement that the signing cert has to chain up through the intermediates to the root pool, so that during root CA rotation the signing cert will …

[ca] Separate RootCA signing cert from root certs

---

manager/dispatcher/dispatcher.go

There are a few places where Debugf/Errorf are used in places where a format string is not expected. In most instances this is cosmetic, but the case of `log.G(ctx).Debugf(err.Error())` is problematic. If the error message contains a % character, the output will be malformed. Correct these log calls.

dispatcher: Fix possible format string bug in logging

---

manager/dispatcher/dispatcher.go

Details in the comments.
I believe this was brought up during our conversations with @tiborvass @anusha-ragunathan @ehazlett.
This guarantees that "one off tasks" (for instance, a global service with restart policy never), once completed, will forever remain in the complete state.
Previously, completed tasks could potentially move to orphaned if a node went down for more than 24 hours.
@aaronlehmann @dongluochen Speaking of which - do you think this fixes an edge case in the "on failure" restart policy? I think without this PR, successful tasks moving to orphaned would have been rescheduled

dispatcher: Only mark running tasks as orphaned.

---

manager/state/store/nodes.go
manager/state/store/resources.go
manager/state/store/services.go
manager/state/store/tasks.go

These type assertions check for failure, and panic in the failure case. A simple type assertion that doesn't check for failure would accomplish the same thing. Use these instead to simplify the code and avoid confusion.
cc @aluzzardi @cyli

store: Remove extra panics

---

manager/allocator/network.go
manager/controlapi/network.go
manager/controlapi/service.go

Signed-off-by: Alessandro Boch <aboch@docker.com>

Reuse allocator.IsIngressNetworkNeeded in controlapi

---

ca/certificates.go
ca/certificates_test.go
ca/config.go
ca/transport_test.go
cmd/external-ca-example/main.go
integration/integration_test.go
node/node.go
node/node_test.go

This is a minor refactor that would be useful when autogenerating Root CAs as part of root rotation (if the user wants swarm to just generate a key and cert for them)

[ca] Separate `CreateRootCA` from saving root CA

---

ca/server.go
ca/server_test.go
manager/controlapi/cluster.go
manager/controlapi/cluster_test.go
manager/controlapi/server.go
manager/controlapi/server_test.go
manager/manager.go

This is also a minor refactor needed because the root CA can change over time now, so is needed for generating new join tokens and also for generating cross-signed certs when doing root rotations (when updating the swarm cluster).
We also make sure, when updating the cluster, to update the security config to reflect the latest version of the cluster to prevent join tokens from being generated using an older version of the `RootCA`.

[ca] Make the control API server take a security config instead of RootCA

---

circle.yml

Our circle.yml is set up so that we have to cd into $WORKDIR for each
step. If we run "make dep-validate" in the default working directory,
where there also happens to be a checkout of the source tree, really
weird things happen.
cc @ijc25

Fix dependency validation

---

manager/controlapi/service.go
manager/controlapi/service_test.go

We disallow changing network attachments, because in the past this wouldn't trigger rolling updates properly. However, this restriction predates the movement of `Networks` from `Spec` to `TaskSpec`. It should be fine to update `TaskSpec.Networks`, since the criteria for a rolling update is the `TaskSpec` in the task not matching the service.
Change controlapi to allow the `Networks` field in `TaskSpec` to be updated. It's also okay to change the field in `Spec` if the one in `TaskSpec` is also being changed at the same time - for example, if migrating data from the legacy `Spec.Networks` field to `Spec.Task.Networks`.
This is difficult to fully test inside swarmkit, but I am including an integration test in the corresponding docker PR.
Fixes #1029
cc @dhiltgen @mavenugo

controlapi: Allow network attachments to be changed

---

ca/certificates_test.go
ca/server.go

While re-organizing #2052, pulled out some minor changes that don't really fit.  This just adds an additional test case I had forgotten for validating intermediates, and cleans up an extra variable declaration.

[ca] Minor cleanups

---

cmd/swarm-rafttool/main.go
cmd/swarmctl/main.go
cmd/swarmd/defaults/defaults.go
cmd/swarmd/main.go

Having this in `pwd`/swarmkitstate/ of the swarmd process is annoying if
actually trying to run as a system daemon (as I'm trying to do in #1965).

Move default swarmd.sock to /run

---

ca/external.go
ca/external_test.go

[ca]: Add a 5-second timeout to an external CA signing request

---

ca/external.go
ca/external_test.go

Cherry-pick of #2064 for 17.03 branch.
cc @cyli @diogomonica @mavenugo

[17.03] Add a 5-second timeout to an external CA signing request

---

ca/certificates.go
ca/certificates_test.go
ca/testutils/cautils.go

This fixes the last TODO in the certificates test, and ensures that the ca `testutils` can handle a `RootCA` with intermediates as well.

[ca]:  Add RequestAndSaveNewCertificates test with intermediates

---

ca/certificates.go
ca/certificates_test.go
ca/config.go

@aaronlehmann discovered an error where if an external CA was unreachable, a new node join would attempt to call `IssueNodeCertificate` on the remote CA 3 times at 5 second intervals, resulting in 3 different node entries.  The assumption would be that `GetRemoteSignedCertificate` would be called, which would call `IssueNodeCertificate` on the remote CA once, and then just keep calling `NodeCertificateStatus`.
The issue seems to be that we had a context timeout of 5 seconds on the call to `NodeCertificateStatus`.  However, if the call to `NodeCertificateStatus` errors (which it would with the timeout), rather than retry `NodeCertificateStatus` later, `GetRemoteSignedCertificate` just returns.
This PR updates `GetRemoteSignedCertificate` so if the call to `NodeCertificateStatus` times out …

[ca]: Fix GetRemoteSignedCertificate retry

---

api/ca.pb.go
api/logbroker.pb.go
api/specs.pb.go
api/types.pb.go
protobuf/plugin/deepcopy/deepcopy.go
protobuf/plugin/deepcopy/deepcopytest.go
protobuf/plugin/deepcopy/test/deepcopy.pb.go
protobuf/plugin/deepcopy/test/deepcopypb_test.go

deepcopy was treating "bytes" as a scalar value and relying on a direct assignment. It's necessary to copy the underlying bytes as well.

Make deepcopy actually deep

---

api/types.pb.go

Two PRs collided, this makes the generated protobuf code consistent.

Run "make generate"

---

ca/certificates.go
ca/certificates_test.go

Cherry-pick of #2063 to 17.03
> @aaronlehmann discovered an error where if an external CA was unreachable, a new node join would attempt to call IssueNodeCertificate on the remote CA 3 times at 5 second intervals, resulting in 3 different node entries. The assumption would be that GetRemoteSignedCertificate would be called, which would call IssueNodeCertificate on the remote CA once, and then just keep calling NodeCertificateStatus.
> 
> The issue seems to be that we had a context timeout of 5 seconds on the call to NodeCertificateStatus. However, if the call to NodeCertificateStatus errors (which it would with the timeout), rather than retry NodeCertificateStatus later, GetRemoteSignedCertificate just returns.
> 
> This PR updates GetRemoteSignedCertificate so if the call to …

[17.03] Fix GetRemoteSignedCertificate retry

---

manager/state/store/extensions.go
manager/state/store/resources.go

The `Resource` and `Extension` types still use wrappers around the protobuf
type. This will be necessary for future changes (#1999) that reference the
relevant extension inside the `resourceEntry`, and reference indexer
objects in the `extensionEntry`. The use of wrappers isn't working
correctly in the current state, because `CopyStoreObject` is returning the
base protobuf type, and stripping the wrapper before anything is saved
in the store. Fix this by defining a custom `CopyStoreObject` for each of
these types. Also, wrap the indexers.

store: Fix type wrappers for Resource and Extension types

---

protobuf/plugin/deepcopy/deepcopytest.go
protobuf/plugin/deepcopy/test/deepcopypb_test.go

A panic was seen in this unit test. There is a missing bounds check that
needs to be added since the randomly-generated slices may have 0 length.

deepcopy: Additional bounds checking in unit test

---

manager/allocator/networkallocator/networkallocator.go

- Needs to label the request for network gateway address
appropriately and needs to honor the case where the
driver has autonomously selected the gateway address.
This was reported in docker/libnetwork/issues/1702

Network allocator does not respect the IPAM contract for nw gw

---

agent/exec/dockerapi/container.go
agent/exec/dockerapi/container_test.go

Closes #1308 -- though this will be handled in the engine itself instead of the agent/exec interface. Not sure if we also want to check this in the agent.

Use docker's new mounts API instead of Binds

---

ca/certificates.go
ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/external_test.go
ca/testutils/cautils.go
ca/testutils/externalutils.go
ca/transport_test.go
cmd/external-ca-example/main.go
integration/node.go
node/node_test.go

The issuer info will allow us to determine if a TLS certificate needs rotation (because it is signed by the wrong issuer during a root rotation - if it is signed by a cert with the same subject + public key as our desired signing cert, it doesn't need to rotate its certificates).
This information will be generated from:
1. `RootCA.IssueAndSaveNewCertificates`
1. `RootCA.RequestAndSaveNewCertificates`
1.  Loading TLS certs from disk.
As part of this change, I've also updated `SecurityConfig` to accept this info plus the TLS certificate in order to update credentials, as opposed to accepting a new `ClientTLSCreds` object and `ServerTLSCreds` object. 
This means that creation of the mutable TLS credentials can be centralized to just within `SecurityConfig`, and that the issuer information is …

[ca] Propagate issuer info from TLS certificates to SecurityConfig

---

manager/controlapi/cluster.go
manager/controlapi/service.go

Just fix some typos.
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>

fix typos in manager/controlapi

---

api/defaults/service.go
manager/orchestrator/task.go

Instead of special-casing this in the orchestrator, put this in the
central defaults package.

defaults: Add default value for Restart.Condition

---

api/defaults/service.go
manager/orchestrator/update/updater.go

Right now, the updater uses `Update` defaults for a rollback if no `Rollback` settings are provided in the service. Make the `Rollback` defaults explicit instead.

defaults: Add Rollback defaults

---

ca/certificates.go
ca/certificates_test.go
ca/server.go
ca/server_test.go
manager/controlapi/ca_rotation.go
manager/controlapi/ca_rotation_test.go

Since we are accepting certificates from the user now, which may have extra whitespace and maybe headers, ensure that we normalize the certificates the user provide us so that when we set the `api.RootCA.CACert` or the `api.RootCA.RootRotation.CACert` will not have any headers or extraneous whitespace. 
Note that if there is extra whitespace or headers already in an `api.RootCA` object, it will not be cleaned up.

[ca/controlapi]: Ensure, when comparing certificates, that we compare the canonicalized form

---

manager/dispatcher/dispatcher.go

The leader sets timers that trigger when nodes' heartbeat timeouts
expire. These timers may trigger after another node takes over as the
leader. In that case, they add updates to nodeUpdates that are acted on
when this node becomes the leader again. That's bad because it means
other nodes will immediately be marked as "DOWN" instead of being in the
UNKNOWN state for the ~15 second grace period.
Reset nodeUpdates and taskUpdates when the dispatcher starts up, so
stale data is not a factor.
I found I could reproduce this reliably by running a cluster of three
managers, and using ^Z to suspend the leader. After repeating this a few
times, nodes would start to get marked DOWN immediately after a leader
change.

dispatcher: Clean up leftover task and node updates

---

ca/testutils/cautils.go
manager/dispatcher/dispatcher_test.go

This way during tests we can make sure there are no conflicts when updating a store from multiple goroutines simultaneously.

[ca/dispatcher]: Use the mock proposer in the test CA memory store

---

manager/orchestrator/replicated/update_test.go
manager/orchestrator/update/updater.go
manager/orchestrator/update/updater_test.go

When Monitor is not explicitly set in the spec, we're supposed to use the default. This regressed in #2080.
cc @cyli @dongluochen

updater: Fix rollback regression

---

ca/reconciler.go
ca/server.go
ca/server_test.go
ca/testutils/cautils.go
integration/api.go
integration/cluster.go
integration/integration_test.go
integration/node.go

The CA server, when it detects a root rotation, will start a reconciliation loop that tells all nodes to rotate their TLS certificates, and once all are done, completes the root rotation.
~~This is stacked on top of #2097~~ Merged.
Addresses #1990.
~~Note that this does not throttle how quickly the nodes get TLS certificates yet.  This should be throttled in the dispatcher, not the CA server.  For instance, if it detects a root rotation, possibly it could delay the session message for every node by a random number of seconds.  This seems more likely to correctly delay nodes than setting the issuance state in batches, since the dispatcher can set the delay based on the number of nodes connected to it.~~
Update: Was thinking through how to delay things on the dispatcher side, and we don't …

[ca] Root rotation reconciliation loop in the CA server

---

ca/reconciler.go

Do not call WaitGroup.Add from within the reconciler loop goroutine, since WaitGroup.Add must be called before WaitGroup.Wait is called, and calling it from within the goroutine is racy because it means that the WaitGroup.Wait could be called before the goroutine is actually started.

[ca] Fix data race with the reconciler's WaitGroup

---

manager/controlapi/ca_rotation.go
manager/controlapi/ca_rotation_test.go

Do not require, when updating the cluster spec, that cluster CAs have associated
root certs.  If none is provided, assume that the external CA is meant to be
associated with the current root CA.

[controlapi] Backwards compatibility when updating cluster spec external CAs

---

circle.yml

It turns out that origin/master may not be up to date in CircleCI
checkouts. Fetch origin so that diffing for the vendor check can be done
correctly.
Note that this doesn't help the case of PRs against branches other than
master, but the worst case is that those will waste a few seconds doing
unnecessary vendor validation. Since those PRs are relatively rare, that
seems fine.

[CI] Fetch origin before diffing

---

manager/controlapi/ca_rotation.go
manager/controlapi/ca_rotation_test.go

Do not require, when updating the cluster spec, that cluster CAs have associated
root certs.  If none is provided, assume that the external CA is meant to be
associated with the current root CA.

[controlapi][17.05] Backwards compatibility when updating cluster spec external CAs

---

manager/orchestrator/global/global.go
manager/orchestrator/global/global_test.go

The global orchestrator was accidentally mixing tasks from different
services when assembling a "slots" parameter to `Update`. This would cause
the affected tasks to get shut down and replaced even though they were
up to date.

orchestrator/global: Fix incorrectly assembled parameters to updater.Update

---

manager/orchestrator/global/global.go
manager/orchestrator/global/global_test.go

The global orchestrator was accidentally mixing tasks from different
services when assembling a "slots" parameter to Update. This would cause
the affected tasks to get shut down and replaced even though they were
up to date.
Backport of #2113
ping @dongluochen @cyli

[17.05.0] orchestrator/global: Fix incorrectly assembled parameters to updater.Update

---

agent/agent_test.go

Bump the timeout for the agent test `TestSessionRestartedOnNodeDescriptionChange` in order to avoid spurious test failures.  Also include a little more info on why the test failed, if it fails.
Hopefully this may fix #2122.

[tests] Maybe fix flakey test by increasing timeout

---

ca/server.go

Only log messages about updating root CA in CA server if it's not the first time a cluster object has been set.
Fixes #2131

[ca] Fix spurious CA server log messages

---

manager/state/raft/membership/cluster_test.go
manager/state/raft/raft.go

A change to enable the CheckQuorum option was merged in September (#1564), but never actually took effect because the config structure where it was set is not used directly.
This fixes the problem to enable it.
The option is useful because it makes a leader realize that quorum is lost and start a new election. Otherwise, the leader will still try to service RPCs, and will succeed when those RPCs don't involve writes. This is confusing.

raft: Actually enable CheckQuorum

---

manager/state/raft/raft.go

When we remove the peers on the snapshot's Removed list from from the
transport, we may have already removed them in the past, or never even
been in contact with these peers. We shouldn't log an error if it turns
out these peers are not known by the transport. This avoids a misleading
error message.
@cyli

raft: Don't log errors removing members based on snapshot

---

manager/dispatcher/dispatcher.go

In the dispatcher, start watching for cluster changes before sending the first
session message, because it's possible to miss a cluster update just between when
the message is being sent and when we start watching for cluster updates.

[dispatcher] Maybe prevent missing a network key update

---

manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/networkallocator_test.go

The PR contains fix and test cases to address the issue : 
https://github.com/moby/moby/issues/32629
The root cause of the issue was with some parts of the code assuming to address only single network attachment for service. The PR addresses issue to handle combination of sequence like network add delete in the same service update or over multiple service updates.

[FIX]: Fixing issue seen in service update with network add and remove 

---

manager/allocator/networkallocator/networkallocator.go

This is dead code. `s.Endpoint` is initialized above.

allocator: Remove redundant nil check

---

manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/networkallocator_test.go

Backport of #2139:
> The PR contains fix and test cases to address the issue :
moby/moby#32629
>
> The root cause of the issue was with some parts of the code assuming to address only single network attachment for service. The PR addresses issue to handle combination of sequence like network add delete in the same service update or over multiple service updates.
ping @abhinandanpb @aboch @aluzzardi @dongluochen @dperny

[17.05] Fixing issue seen in service update with network add and remove

---

ca/reconciler.go
ca/server_test.go
manager/allocator/network.go
manager/dispatcher/dispatcher.go
manager/orchestrator/constraintenforcer/constraint_enforcer.go
manager/orchestrator/global/global.go
manager/orchestrator/replicated/services.go
manager/orchestrator/replicated/tasks.go
manager/orchestrator/service.go
manager/orchestrator/taskinit/init.go
manager/orchestrator/update/updater.go
manager/scheduler/scheduler.go
manager/state/store/memory.go
manager/state/store/memory_test.go

Currently `Batch` returns the number of updates it was able to commit
successfully, but this isn't really actionable. Either it committed
everything successfully, or the node lost leadership and it doesn't
matter what was committed and what wasn't (the new leader will pick up
from where we left off). A compliant caller of Batch would have to do a
bunch of accounting keep its internal state in sync with what Batch was
able to commit. This turns out not to matter in the current
implementation. Most uses of Batch ignored the first return value.
Change `Batch` to only return an error.
Fixes #2111
This is an alternative to #2110 
cc @ijc25 @dongluochen @aboch @yongtang

store: Simplify Batch

---

manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/portallocator.go
manager/allocator/networkallocator/portallocator_test.go

This PR has a few small cleanups for the allocator code.
It may be easiest to review commit-by-commit.
```
allocator: Rename PortsAllocatedInHostPublishMode
Rename to HostPublishPortsNeedUpdate, and invert the logic. This better
matches ServiceNeedsAllocation and is a clearer description of what the
function is used for.
```
```
allocator: Factor specNetworks assignment into a function
```
```
allocator: Standardize on label/continue syntax when comparing VIPs with networks
Also, return explicit error values instead of relying on the named
return variable.
```
```
allocator: Make updatePortsInHostPublishMode check for host publish mode, not ingress
This will make things easier if/when we add another publish mode.
Also, update the Spec on s.Endpoint whether or not the new value is nil.
``` …

allocator: Various cleanups

---

identity/doc.go
manager/allocator/doc.go
manager/state/store/doc.go

WatchableStore mentioned in manager/state/doc.go does not seem to exist.
MemoryStore fits the old description. I assume this was missed in a
rename.
Signed-off-by: Alexander Midlash <amidlash@docker.com>

Minor doc changes.

---

agent/worker.go

This moves the publish of a task manager creation event to after the
successful resolution of a task manager, ensuring that it will be there
when later resolved for log subscriptions.
Before, we correctly ignored the error, but it was not reported via the
correct log messagses. We have added the proper `WithError` to the log
message to ensure traceability.
It is unclear whether or not this early mount validation, the cause of
the controller resolution failure, is valid or not. We should really be
deferring to the "runtime" to make that determination and fail at
startup, but this PR should allow this to work gracefully.
Closes https://github.com/docker/swarmkit/issues/2147

agent: avoid race condition after failing task startup

---

agent/worker.go

Cherry picks #2148 into the bump branch.
This is the probable fix for a segfault that has likely existed since the inception of service logs. 
/cc @stevvooe and @aaronlehmann

[17.05.0] cherry-pick: agent: avoid race condition after failing task startup

---

node/node.go

Passing a slash-delimited path into `filepath.Join` kind of defeats the purpose.

node: Use filepath.Join properly

---

manager/controlapi/service.go
manager/controlapi/service_test.go

This removes the limitation of forcing secrets to be in `/var/run/secrets` and allows arbitrary paths.  Note: these are still bind mounted and on tmpfs.
Refs https://github.com/docker/docker/pull/32336#issuecomment-293035306

Allow secret references to be full paths

---

manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/networkallocator_test.go

The regression was seen when docker service was created with published ports which would instantiateingress network.The service allocate was not allocating vip for ingress network.
The fix contains a check to verify if the vip is on ingress or user defined network and allocate/verify service allocation.

Fixing issue with ingress network vip not allocated on service create

---

manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/networkallocator_test.go

Backport of #2155. Also includes one commit from #2144, to make the backport cleaner.
cc @abhinandanpb @aboch @mavenugo @vieux

[17.05] Fixing issue with ingress network vip not allocated on service create

---

ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/renewer.go
ca/renewer_test.go
node/node.go

This is similar in concept to the last attempt (#2152), but moves the retries into the ca code. `RenewTLSConfig` had to be refactored to support notifying the loop of the expected role. This couldn't be passed over the channel easily, because the sending code can't block indefinitely long, and using a goroutine would let updates to the expected role race.

node: Third proposed fix for cert renewal logic race

---

identity/doc.go

`NewID` doesn't return an error, it panics.

Update `identity/doc.go` to be coherent with the code

---

vendor.conf
vendor/github.com/coreos/etcd/raft/raft.go

Now that we are using CheckQuorum, it is causing some spurious leader
elections that are leading to test failures in both SwarmKit and Docker
integration tests.
I submitted this change upstream, but it hasn't been reviewed yet. I'd
like to temporarily vendor a fork that has the change. First, this will
unblock vendoring swarmkit from the master branch. Also, it will give us
a chance to test the change more broadly. Finally, we probably don't
want to vendor the master branch of etcd, so without this temporary
fork, we'd have to wait for a release that includes this change.

Temporarily vendor fork of etcd

---

manager/allocator/networkallocator/networkallocator.go

A NetworkSpec should never be updated by the core. Avoid updating it in even a
trivial manner by restructuring the creation of ipamConfigs. I also happen to
find the new logic easier to grok.
This is largely benign right now but never writing to Network.Spec will make
changes in #2108 easier to reason about.

Avoid writing to Network.Spec in allocatePools

---

manager/scheduler/scheduler.go

Fix https://github.com/moby/moby/issues/32999. 
Deleting tasks may free up node resources. Pending tasks should be evaluated. 

scheduler should re-evaluate pending tasks after any task removal

---

agent/agent_test.go
agent/session.go
agent/testutils/fakes.go
node/node_test.go

Connections to a local dispatcher can’t really be closed, so a session can’t really be restarted because closing a session just closes the connection.  When this happens, it just starts up another session without closing the previous one.
Since we need to restart a session to push new TLS data up to the dispatcher from the agent, change "closing" a session to mean first shutting down all the clients with a context.cancel before
closing the connection.

[agent] Fix session rebuilding against a local dispatcher

---

ca/certificates.go
ca/certificates_test.go
ca/config.go

When downloading a root certificate or getting a certificate signed, the existing code will retry a few times on failure, but does not wait between retries. If a leader election is in process, all attempts may fail. Add a delay to give the election a chance to complete.
This probably won't fix all of the recent problems with flaky integration tests, but it seems worth doing anyway.

ca: Delay between retries when retrieving certs

---

ca/certificates.go
ca/certificates_test.go
ca/external_test.go

Fix bug where we could not cross-sign an RSA certificate with an ECDSA certificate and vice versa.
Noticed this when poking around the docker CLI.  It's because we are just using the new cert as a template, and the new cert's signature algorithm could be different than the old cert's signature algorithm (because the new cert's key could be an entirely different key type than the old).

[ca] Fix cross-signing bug where ECDSA keys can't cross-sign RSA CAs

---

manager/controlapi/service.go

- it is checking for `Internal` instead of `Ingress`
This is a breakage introduced in f39ead8777a6c
This was reported by @archisgore in https://github.com/docker/swarmkit/pull/2028#issuecomment-300211162

Fix service network validation

---

manager/dispatcher/dispatcher.go

Deleting a service causes the underlying tasks to be deleted. The
dispatcher currently logs warning and error messages when it can't find
tasks that correspond to status reports from an agent. These log
messages should be logged at the debug level, because it's normal for
tasks to be deleted like this. Also, only one message should be logged
per missing task.
cc @cpuguy83

dispatcher: Quiet log messages when a service is deleted

---

manager/controlapi/service.go
manager/controlapi/service_test.go
manager/scheduler/filter.go
manager/scheduler/nodeinfo.go
manager/scheduler/pipeline.go
manager/scheduler/scheduler_test.go

Relax the validation in controlapi to allow two services to use the same host-mode published port.
Add a scheduler filter so that tasks from these services land on different nodes.
cc @aboch @pvnovarese @aluzzardi @dongluochen

Allow different services to use the same host-mode port

---

manager/state/raft/raft.go

If the leader comes back after an extended period of quorum loss, we may
not realize this until a tick has elapsed. API calls may fail even
though there actually is a leader at that point in time. To solve this,
optimistically try to get the leader connection, and only check
ticksWithNoLeader if this fails.
cc @cyli

raft: Check for leader before returning quorum loss error

---

manager/scheduler/filter.go
manager/scheduler/scheduler_test.go

I noticed that doing `Architecture` comparisons on the Platform filter is likely to cause issues.
For instance, I saw that the docker-in-docker dev container reports node info as `linux`/`x86_64` and the `alpine:latest@sha256:c0537ff6a5218ef531ece93d4984efc99bbf3f7497c0a7726c88e2bb7584dc96` image I downloaded reports its platform info as `linux`/`amd64`. The image can still run.
This means that the platform filter, as implemented now, will kick off an image that is capable of running on a node. I think this mismatch is a bug, but I don't think we lose by disabling Architecture comparisons, at least for now.
cc @aluzzardi @aaronlehmann @friism 

Better Architecture comparison for Platform filter

---

manager/dispatcher/dispatcher.go

defer the unlock so it is not missed.
Fixes #2184

dispatcher: Ensure processUpdatesLock is unlocked

---

manager/scheduler/scheduler_test.go

task1 lands on node1.
task2 cannot be scheduled.
task3 can land on either node2 or node3 without creating an unbalanced situation. The lack of platform information on node3 is not a factor because task3 doesn't have platform constraints.
However, the test currently expects task3 to land on node1 or node2.
cc @nishanttotla

scheduler: Fix flaky test TestSchedulerCompatiblePlatform

---

manager/manager.go
manager/state/raft/raft.go
node/node_test.go

If `raftNode.JoinAndStart` failed, `Stop` will block forever because it waits for the manager to start up.
To fix this, close the "started" channel even if Run exits early due to an error. Fix the way the collector is initialized so its `Stop` method won't hang either.
Add a test that makes sure the node shuts down cleanly after a failed manager initialization.
cc @cyli

manager: Fix hanging Stop method

---

manager/scheduler/filter.go

If there is no engine description then this assumes that all drivers etc are built-in and thus always available, and when they are not proper errors will be generated and propagated.
This avoids the need in https://github.com/docker/swarmkit/pull/1965 to populate a spurious `api.NodeDescription.Engine` field (spurious because there is no engine in this case).
The `api.NodeDescription.Engine` field is https://github.com/ijc25/swarmkit/blob/42f853a3c262666e29d4c0bd3ea301d5e736bc82/agent/exec/containerd/executor.go#L93...L101 in the current PR (but I expect that link to break when I next force push there) it is the `executor.Describe` method and is just:
```
// Possibly this should have a Containerd entry
// instead. There is some code …
```

Only filter on plugins if running with docker engine

---

manager/allocator/cnmallocator/drivers_darwin.go

When building on mac OS I got the following error:
```
manager/allocator/cnmallocator/drivers_darwin.go:14: undefined: PredefinedNetworkData
```
Import the type from the `networkallocator` package.

Fix cnmallocator darwin import

---

ca/external.go
ca/testutils/externalutils.go

When we make an external CA request to cross-sign a certificate, include a particular signing profile that can be implemented by the external CA.
This way it will be easier for them to implement extra policies.
This is not urgent, but would be good to make this part of the input external CAs that interact with swarm should expect.
cc @diogomonica @aaronlehmann @jlhawn

[ca] Include a signing profile for cross-signing CA certs externally

---

agent/agent.go
agent/agent_test.go
agent/config.go
agent/session.go
integration/integration_test.go
node/node.go

This is an attempt to address https://github.com/moby/moby/issues/33380.
Basically, when a join address is passed, then if there are x509 errors when connecting to that join address, the agent should bail rather than attempt to rebuild a session over and over.  This is on the assumption that a join address is only passed when attempting to join a cluster (see https://github.com/moby/moby/pull/33361).
We want to make sure that, if the join address is passed, it only fails on x509 errors if there were no previous successful sessions.  If there were previous successful sessions, this indicates that the x509 error is perhaps a result of one of the managers, as opposed to the node that is attempting to join.
Because of this, we have to keep track of how many sessions and session errors …

[agent/node] Bail on cert error when joining

---

ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/external.go
ca/server_test.go
ca/testutils/cautils.go

Since if it's not updated when getting a cert signed by an external CA, no intermediates are appended.
Previously the test for this (`TestRequestAndSaveNewCertificatesWithIntermediates`) passed due a combination of both this bug and a bug in how the test CA utility worked (it updated the RootCA to one without intermediates, but since updating the root CA didn't actually propagate to the external CA signing object, the external CA signer did produce a cert with intermediates).
I've updated the test CA utility and the tests as well.  I'll also open a PR against the 17.06 branch.
cc @aaronlehmann @diogomonica @jlhawn

[ca] Fix the UpdateRootCA function to also update the ExternalCA's rootCA

---

ca/reconciler.go
ca/server_test.go

When rotating the root CA, tell nodes that are in "pending" membership status
to rotate as well, because the membership status isn't really used atm, and it
is valid for a node update to change the membership status to pending by
accident.
Also attempt to stabilize some of the root rotation tests.  (I think this fixes #2138)
cc @aaronlehmann @diogomonica 
`moby/moby` does not set the `NodeSpec.Membership`, so whenever there's a node update, the membership status gets set to `PENDING` which is the default value.

[ca] When rotating the root CA, ignore the node membership

---

manager/allocator/allocator.go

The allocator starts a watch on events and never shuts it down. If this node loses leadership, events will continue to pile up in that queue forever, leading to memory exhaustion.
Fix this by giving the watch a well-defined lifecycle. Return it along with a cancel function from an init() method to make it clear it must be cancelled, instead of sticking the cancel function value in a struct where there is no clear responsibilty for calling it.
In the future, we might consider changing `Watch` to run a callback function, so shutting down the watch is mandatory (similar to what we do with store transactions).
cc @briantd @jakegdocker

allocator: Fix events watch leak

---

ca/certificates_test.go
ca/config_test.go
ca/external.go
ca/testutils/cautils.go
integration/integration_test.go

This PR includes some test cleanups discovered while debugging #2221:
1. The goroutine that updates to the RootCA of the testing CA server never actually terminates after a test, because the context is never canceled.  This makes sure that goroutine is cleaned up.
1. One of the fake CA servers is never stopped after a test - added a defer stop.
1. Similar to how the integration tests log the test names, do the same for the testing CA so we can tell which logs belong to which test.
cc @aaronlehmann @ijc25 This does not actually fix the stated issue above, but would be helpful for debugging and may reduce some resource consumption for running the tests.

[tests] Cleanup and better logging

---

ca/certificates.go

If a node has no registered TLS info, or has TLS info indicating that it was signed
by a different CA cert, and the cluster is in the middle of a root rotation, then
the root reconciler updates the node info to mark it as needing a rotation.
However, when a node requests a new cert, it will only download the new cert if the
issuance status is ISSUED.  If the root reconciler happens to get to the node
immediately after the CA signs it but before the node downloads it, then the node
will never download it and will poll until timeout, and then request a new certificate
instead.
Since a node only gets marked as ROTATE if it's not already in PENDING, just download
the cert even if the cluster says that the issuance state is ROTATE.  This will cut
short a lot of extra polling before the node …

[ca] GetRemoteSignedCertificate downloads cert in Issuance or Rotate state

---

ca/testutils/cautils.go

Ensure that the test CA, if an external CA is desired, does not have a local signer.
This also does is not a fix for #2221, but is more correct behavior.  I added https://github.com/docker/swarmkit/pull/2210/files#diff-70b482ef8a125f8723ff2f77b65299faR146 as a comment and never followed through on it in #2210.

[tests] No local signer for test CA if external CA is desired

---

manager/orchestrator/task.go

`IsTaskDirty` assumed that if a task had a `SpecVersion`, the corresponding service must also have a `SpecVersion`, since that is where the task's field is copied from. However, there are mixed-version scenarios where a service could get updated by a manager running an older version of swarmkit than the manager that created the task. Add a check to avoid a crash in this case.

orchestrator: Check that service's SpecVersion exists before dereferencing

---

ca/config.go
ca/config_test.go
ca/server_test.go
node/node.go

Validate the Root CA certificate before updating the security config with
a new RootCA, to be sure that the root CA certificate matches the TLS
credentials already in the SecurityConfig.
This will prevent, for instance, a manager from telling an agent to load
an invalid root certificate, as can happen if an agent connects to a
manager that is being caught up via raft and hence might be replaying
old root rotations.
Without this change, a manager that is catching up (for instance if it has been promoted, or if it was behind) and replying raft messages might tell all the nodes connected to it to update their root CA to an older version.  This will also prevent that manager from updating to an outdated root CA as it's catching up.
This is not the …

[ca] Validate the Root CA certificate before updating the security config

---

manager/allocator/cnmallocator/networkallocator.go
manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
manager/controlapi/common.go
manager/controlapi/network.go
manager/controlapi/network_test.go
manager/controlapi/server.go
manager/controlapi/server_test.go
manager/manager.go
manager/manager_test.go

At the point at which the controlapi server is created the allocator has not yet been created, and hence is nil.
Since CNM is currently the only actual choice do as with `PredefinedNetworks` and hardcode the use of the CNM backend, this will be reworked once there is a second choice.
Fixes #2230. Add a call to NetworkCreate in TestManager and a test to controlapi specifically to trigger this code path. The latter tests controlapi in isolation, while the former would catch e.g. a race or initialisation order issue in a manager.
Also, in controlapi tests, change a `testnet2` into a 3 in `TestRemoveNetwork` to avoid (harmless) duplication.
Also, only call `IsBuiltInNetworkDriver` for Network plugin type.
Replaces #2231.

Avoid nil Allocator in controlapi

---

manager/allocator/allocator_test.go
manager/allocator/network.go

When the allocator starts up, there is a pass that "allocates" the
existing tasks/nodes/services in the store. In fact, existing tasks are
typically already allocated, and this is mostly populating local state
to reflect which IPs are taken. However, if there are any tasks in the
store which are brand new, or previously failed to allocated, these will
actually receive new allocations.
The problem is that allocation of new IPs is interspersed with updating
local state with existing IPs. If a task, node, or service that needs an
IP is processed before one that claims a specific IP, the IP claimed by
the latter task be assigned.
This change makes the allocator do two passes on initialization. First
it handles objects that claim a specific IP, then it handles all other
objects.
cc …

allocator: Avoid assigning duplicate IPs during initialization

---

ca/certificates.go
ca/config.go
ca/config_test.go
ca/renewer.go
ca/renewer_test.go
ca/server.go
manager/manager.go
node/node.go

When renewing the TLS certificate, if we get an x509.UnknownAuthorityError,
try to update the root CA such that it validates against the old TLS creds
before renewing again.
This can help with edge cases where a manager might have been demoted, and
thus not be able to push the latest root certificate to its agent, but
the node needs to renew the TLS cert to get one for the worker role (but
root rotation has already finished, and hence any certificate it gets will
no longer have the intermediate and won't validate).
Still needs test.  The ideal scenario @aaronlehmann and I discussed was to separate the Root CA used to sign new certs from the root CA the node itself uses to validate incoming connections and external servers, but that may be a …

[ca/node] Maybe update the root CA when renewing the TLS cert

---

manager/allocator/allocator_test.go
manager/allocator/cnmallocator/networkallocator.go
manager/manager.go

This commit contains the following fixes:
1) On upgrade from pre 17.06 version services created with net=host
were failing because the swarm was not aware of host network being
created. The fix added takes care of this by creating network if
the store does not contain predefined networks
2) On a cluster with upgraded 17.06 version of docker swarm manager
the daemon panics while trying to access IPAM driver in the createNetworkRequest on
the nodes with pre 17.06 versions. In order to avoid panics empty struct is passed
with network attachment. This does not have any function impact.
Signed-off-by: Abhinandan Prativadi <abhi@docker.com>

Fixing error with host network mode on upgrade from pre 17.06 versions

---

manager/allocator/allocator_linux_test.go
manager/allocator/allocator_test.go

The macvlan driver isn't supported on Darwin, so a test case that depends on its behavior needs to be marked Linux-specific.
cc @abhinandanpb

allocator: Fix tests on darwin

---

Makefile
circle.yml

Also remove installing the extra mockgen package when installing dependencies, since we no longer use gomock.

[ci] Bump go verison up to 1.8.3

---

manager/allocator/network.go

The allocator wraps errors returned by `Allocate` and `AllocateTask` to explain that this was an allocation failure and add the task ID or network ID. However, this information is already part of the errors returned by these functions.

allocator: Remove redundant error wrapping

---

manager/orchestrator/replicated/update_test.go

This test triggers a race condition in the way the updater and restart supervisor interact.
The problem is normally masked by a second reconciliation pass triggered as a side effect of the update completing, but this test case does not wait long enough for the update to be declared complete.
Since the test does not pass reliably, it should be skipped until the underlying issue (#2242) is fixed.
Fixes #2137

Skip TestUpdaterRollbackAndPauseNoMonitor

---

manager/manager.go
manager/orchestrator/replicated/task_reaper_test.go
manager/orchestrator/taskreaper/task_reaper.go

It is not necessary to create a watch in the `New` function. Creating it in `Run` is more consistent with other parts of the code, and makes the lifecycle of the watch clearer.
This is not a functional change, but it may help prevent adding bugs in the future.
Also, thread through a context to use for logging.

taskreaper: Clean up Watch code

---

manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

The scheduler has simple failure loop detection that attempts to prefer
other nodes when a certain node experiences several failures in a row of
tasks from the same service. This makes sense for replicated services,
but doesn't have an effect on global services, because the node is
predetermined for each task. When this code path triggers with a global
service, it produces a confusing log message that suggests other nodes
will be preferred for this global service.
Change the scheduler to keep track of which tasks were preassigned to
nodes, and avoid tracking failures of those tasks.
Fixes #2228
cc @cpuguy83

scheduler: Do not try to underweight nodes for global services

---

manager/allocator/network.go

We retry failed allocations every 5 minutes. If something else gets
deallocated, we should trigger the retry immediately in case the
allocations were failing due to IP exhaustion, and the deallocation
freed up an IP.
cc @abhinandanpb

allocator: Retry failed allocations immediately upon a deallocation

---

agent/agent_test.go

In `agent.go`, the ready channel is closed before the agent session tracker, if any, gets notified that a session is established.  This would periodically cause `TestAgentRegistersSessionsWithSessionTracker` to fail because it would wait until the node was ready and then see if the tracker had been notified, and sometimes that happened in the reverse order.
This PR also injects the testCA's context into all the agent calls so that better logging can be included.
The other option as opposed to polling in the test is, in the agent, to make the session tracker get called before the ready channel is closed, but perhaps closing the channel as soon as the agent was ready rather than waiting on any tracker code, which may be slow, might be better? …

[tests] Fix flakey `TestAgentRegistersSessionsWithSessionTracker` test.

---

integration/integration_test.go

`TestNodeRejoins` tests that both a manager and agent will fail early if the certificates on disk have been changed in the case where they've already joined a cluster previously.  After discussion with @aaronlehmann, this should be the case for agent, but not necessarily the case for manager, so remove that assumption from the test.
Previously this was often passing because on startup, the agent of the manager may try to connect to another manager first and the agent dies.  If the manager itself starts up first, and the local agent connects to that manager, then the manager just keeps trying to reconnect to the rest of the raft cluster over and over and failing.  If the local agent connects to this local manager first instead, then the flakeyness was triggered because the node is never …

[tests] Fix flakey TestNodeRejoins test

---

circle.yml

This sets up a tmpfs mount to be used for temporary files created by tests.
If this works, hopefully it will fix the excessive I/O latencies that
are blocking tests for long periods and causing them to fail.
As a side effect, this also stores temporary compilation artifacts on
tmpfs.

Run CI with temporary files on a ramdisk

---

ca/external_test.go
ca/renewer_test.go
ca/server_test.go

Missed a few in #2222, namely in the server tests and renewer tests.

[tests] Pass the TestCA context to all the CA tests

---

manager/dispatcher/dispatcher.go

Changes the debug message to make it clearer that swarmkit agent actively noticed the task status update and that the dispatcher is now committing that state to the store. I'm still familiarizing myself to the swarmkit architecture and lexicon so please let me know if this can be improved.
Closes #2208 
Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>

dispatcher: Make debug log clear that dispatcher committed the task status

---

manager/controlapi/cluster.go
manager/controlapi/cluster_test.go

Not because it's a secret, but otherwise the user flow of getting and updating the cluster spec would be problematic because the key is redacted but the cert is not - the user would be responsible for having to remove the cert instead to make sure this doesn't change the swarm CA key.
cc @aaronlehmann @andrewhsu @jlhawn

[controlapi] Redact the cluster spec CA signing certificate when getting the cluster info

---

manager/scheduler/filter.go
manager/scheduler/scheduler_test.go

Docker added support for logging plugins, this makes sure swarmkit can
filter nodes for task scheduling based on available log plugins.

Add filtering for log plugins

---

manager/scheduler/nodeset.go
manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

This function previously could take an uninitialized `NodeInfo` structure and fill in whatever was missing. This is very error-prone, so remove this logic and change the only caller that relies on it to always pass in a properly initialized `NodeInfo`.
This was originally a cleanup that was part of #2253, but it turns out to fix a bad panic. Opening as a separate PR for backport.
cc @andrewhsu

scheduler: Clean up addOrUpdateNode

---

manager/manager_test.go

So that the test names are displayed in the test output.  This was useful for debugging manage test failures.

[tests] Use the TestCA context in all the manager tests in manager_test.go

---

manager/state/raft/membership/cluster_test.go
manager/state/raft/raft_test.go
manager/state/raft/storage_test.go
manager/state/raft/testutils/testutils.go

We were altering the node map during the tests, so some of the replaced nodes didn't get cleaned up.  See https://github.com/docker/swarmkit/pull/2269#issuecomment-309617060

[tests] Clean up unremoved temp files from manager raft tests.

---

agent/storage.go

Instead of repeating the literal key, use the constants that are already defined.

agent: Use bucket key constants

---

manager/dispatcher/dispatcher.go

When the argument is a string returned by `Error`, we don't want to use `Debugf`, since if the error string happens to include % characters, this will cause a format string error.
Also prefer `Debug` over `Debugf` in cases where literal strings do not include any formatting (this part is purely cosmetic).

dispatcher: Use Debug instead of Debugf

---

agent/exec/dockerapi/adapter.go
agent/exec/dockerapi/container.go
agent/exec/dockerapi/controller.go
agent/exec/dockerapi/controller_integration_test.go
agent/exec/dockerapi/controller_test.go
agent/exec/dockerapi/executor.go
manager/controlapi/service.go
template/context.go
template/context_test.go
template/expand.go
template/getter.go
template/getter_test.go

At the moment we can only use NodeID as a template variable. The hostname is better for some kind of application and it's also more flexible and human readable. See #1951 or moby/moby#32561 for related proposals.
This PR is built on the previous work done by @gianarb

Add support for templating Node.Hostname in docker executor

---

manager/state/store/clusters.go
manager/state/store/configs.go
manager/state/store/extensions.go
manager/state/store/memory_test.go
manager/state/store/networks.go
manager/state/store/nodes.go
manager/state/store/object.go
manager/state/store/resources.go
manager/state/store/secrets.go
manager/state/store/services.go
manager/state/store/tasks.go

Since if the object already exists, the event produced should be an update and not a delete/create.
This is probably the cause of https://github.com/moby/moby/pull/33541, where an unlock key change is sometimes is not picked up by a snapshot restore from another node.
cc @aaronlehmann 
Also, :( generics

[store] Change the `Restore` action on objects to update instead of delete/create

---

watch/queue/queue.go
watch/queue/queue_test.go
watch/sinks.go
watch/sinks_test.go
watch/watch.go
watch/watch_test.go

This PR extends the `watch` package with the following items:
- A new Queue-like sink called the `LimitQueue`. This is near-identical to the implementation of a Queue from https://github.com/docker/go-events/blob/master/queue.go with the difference that the queue has an upper size limit. When that limit is reached, a channel is closed and it's up to the user to determine the desired behavior from there
- A sink wrapper called the `TimeoutSink` which wraps another sink with a timeout. If the timeout is reached, the wrapped sink is closed and an error is returned to the writer.
- A `ChannelSinkGenerator` interface which can be used to configure the sink-chain that `watch.Queue` creates for each watcher.
- Support for contexts on `watch.Queue`
- A new set of constructors that tie these …

Extend watch queue with a timeout and size limit

---

ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/external_test.go
ca/testutils/cautils.go
manager/controlapi/ca_rotation_test.go
node/node.go
node/node_test.go

Rather than use `SetWatch`.  This returns the `watch.Queue.Close` function as a cleanup function whenever a security config is created.
cc @aaronlehmann @diogomonica

[ca] Refactor SecurityConfig to automatically create a watch.Queue

---

manager/scheduler/nodeinfo.go
manager/scheduler/nodeset.go
manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

This addresses a longstanding TODO which I forgot about. Currently, the scheduler tracks potential failure loops by service ID. However, if the service is updated, it won't distinguish the new version of the service from the old one. This means even if the operator fixes the underlying problem, the new tasks from the updated service will still avoid the node where the problem was detected.
Change the failure tracking to be sensitive to `SpecVersion` as well. If `SpecVersion` changes, we'll treat the task as a different kind of task for failure tracking purposes.
Also, add a periodic cleanup pass to make sure `recentFailures` doesn't grow without bound, and clean up `addOrUpdateNode` so it doesn't try to fix up uninitialized `nodeInfo` structs (which is fragile).
cc @aluzzardi

scheduler: Version-aware failure tracking

---

vendor.conf
vendor/github.com/Microsoft/go-winio/README.md
vendor/github.com/Microsoft/go-winio/backup.go
vendor/github.com/Microsoft/go-winio/file.go
vendor/github.com/Microsoft/go-winio/fileinfo.go
vendor/github.com/Microsoft/go-winio/pipe.go
vendor/github.com/Microsoft/go-winio/privilege.go
vendor/github.com/Microsoft/go-winio/reparse.go
vendor/github.com/Microsoft/go-winio/sd.go
vendor/github.com/Microsoft/go-winio/syscall.go
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go

Matches the version used in moby/moby
Full diff: https://github.com/Microsoft/go-winio/compare/f778f05015353be65d242f3fedc18695756153bb...v0.4.2

Bump go-winio to v0.4.2

---

ca/external.go
ca/external_test.go

Clean up some of the external CA signing code.

[ca] Limit the size of the response back from the external CA

---

manager/orchestrator/global/global.go
manager/orchestrator/global/global_test.go

Currently, the global orchestrator leaves associated tasks around when
a node is deleted. There is no process for reaping these tasks, as the
task reaper keeps a certain number of global service tasks *per node*.
Instead, delete the task right away when its node is deleted. This is
similar to how the replicated orchestrator deletes tasks when scaling
down, since tasks in those slots that are no longer being used would not
end up being reaped.
Fixes #2295
cc @thaJeztah

orchestrator/global: Delete tasks when their node is deleted

---

.gitignore

I was running `make ci` and noticed my working git directory picked up a bunch of unstaged `coverage.txt` files.
I don't think there's any value in tracking them with git if they aren't checked into the repo, so this PR adds `*coverage.txt` to the `.gitignore`
Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>

gitignore: ignore coverage.txt files

---

manager/logbroker/broker.go
manager/logbroker/broker_test.go
manager/manager.go
manager/watchapi/server.go
manager/watchapi/server_test.go
manager/watchapi/watch.go

Because we use `GracefulStop`, RPCs need to finish on their own when the
manager shuts down.
The `watchapi` server formerly was completely stateless, and didn't have a
notion of starting or stopping.
This adds `Start` and `Stop` functions that control a context, adapted from
the logbroker code. When the context is cancelled, outstanding RPCs will
finish.
There are also some related cleanups and fixes in the logbroker code.
Fixes #2307
cc @dperny

watchapi: Terminate RPCs when the manager shuts down

---

design/task_model.md

The `ALLOCATED` state I think is now called the `PENDING` state.  Also, document the `ORPHANED` state.

design: Update the task model doc to reflect the current task state names.

---

template/context.go
template/expand.go
template/getter.go
template/getter_test.go

This changes the templated ConfigGetter to include an extra method,
GetAndFlagSecretData, which returns an interpolated config and also a
flag indicating whether it contains any data from a secret. This can be
used downstream to avoid storing the config to disk.
Ideally, there would be some kind of Sensitive method on a Config object
itself, but since that type is automatically generated by protoc,
including a private field is awkward to do. Thus this approach of
returning the flag along with the config. Note that I opted for a method
that returns the config and the flag at the same time instead of a
method that just returns the flag, since a method that returns the flag
still needs to expand the config, and it seems most robust and
performant to just return the config and the flag at the …

template: Indicate which configs contain secret data

---

ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/external.go
ca/external_test.go
ca/server.go
ca/server_test.go
manager/controlapi/ca_rotation.go
node/node.go

This is the first step towards splitting the CA server's signing functionality from `SecurityConfig`, which serves more for providing creds for mTLS.  Doing so will help unify the root CA update paths in `node/node.go`.
The only node that ever needs the `ExternalCA` object is the leader that is running the CA server anyway, so it makes sense for it to go into the CA server.  This also better makes it possible at a future point to provide separate creds for contacting the external CA server if we ever needed to do so.

[ca] Extricate `ExternalCA` from `SecurityConfig`

---

manager/orchestrator/global/global.go
manager/orchestrator/global/global_test.go
manager/orchestrator/testutils/testutils.go

There is some tension around what to do when reconciling a service whose restart policy is "none". On one hand, the restart policy says not to restart a failed task. On the other hand, the declarative state of the service says a certain number of replics of the service should run, or the task should run on all possible nodes, and a change to the spec might resolve the condition that caused the failure.
Currently, the replicated orchestrator chooses to favor the declarative state when reconciling a service. This means that on a leader change or change to the service, we effectively ignore the restart policy.
The global orchestrator, on the other hand, refuses to touch the task on any node where it has failed, if the restart policy says to do so. This can lead to very unintuitive behavior, …

global: Allow updates of failed services with restart policy "none"

---

design/raft.md

This document explains how the Raft implementation works.

design: Add raft.md

---

manager/manager.go

The watch server was wrongly changed to only run on the leader node. It needs to run on all managers because this is one of the RPC services that is not proxied to the leader (since all nodes receive events through Raft).
This is regression introduced by #2310 (sorry). It never made it into the moby tree. It is covered by tests in that tree.
cc @cyli @aluzzardi

manager: Always run the watch server

---

manager/orchestrator/replicated/update_test.go
manager/orchestrator/update/updater.go

There is an oversight in this code that prevents it from changing the
spec version to match the spec that's put in place during a rollback.
This could cause a service not to get rolled back all the way.
Currently, tasks may stay on the new version until they fail and are
replaced with an older version.
cc @cpuguy83 @thaJeztah

orchestrator/update: Update spec version when rolling back

---

manager/orchestrator/update/updater.go

In start-then-stop mode, the updater waits for a verdict on the startup
of a new task, and then shuts down the tasks that this new task was
meant to replace. It should really only shut down the old task if the
new task successfully reached running. The thinking here was probably
that a task which fails on startup would briefly enter the running state
before failing, so there isn't much point in distinguishing between
running and some terminal state. However, if a health check is being
used, the task may never enter the running state. This can also happen
when a task is rejected by a node.
See https://github.com/moby/moby/issues/34111 for a repro case.
cc @sirlatrom @cpuguy83

orchestrator/update: Only shut down old tasks on success

---

manager/manager.go
manager/state/raft/raft.go
manager/state/raft/raft_test.go
manager/state/raft/testutils/testutils.go
node/node.go

If Join is called and the member already exists in the cluster, instead
of returning an error, it will update the node's address with the new
one provided to the RPC.
This will allow managers to update their addresses automatically on
startup, if they were configured to autodetect the addresses.
It will also be possible to manually repeat the "docker swarm join"
command, to specify a different advertise address, or rejoin a cluster
when all known manager IPs have changed.
cc @aluzzardi @cyli

raft: Allow Join to be called multiple times for the same cluster member

---

manager/orchestrator/replicated/restart_test.go
manager/orchestrator/restart/restart.go

When a service reaches the limit on the number of restart attempts and then it is updated, currently the limit is still enforced. This isn't the right behavior, because restarts before the service was updated shouldn't count against the new version. There may have been a problem with the old service spec that is fixed with the new spec.
See https://github.com/moby/moby/issues/34007

orchestrator/restart: Reset restart history when task spec changes

---

manager/orchestrator/global/global.go
manager/orchestrator/global/global_test.go
manager/orchestrator/testutils/testutils.go

The global orchestrator shuts down tasks on drained nodes. This makes
sense - it's consistent with the replicated orchestrator shutting down
tasks in the same situation (as part of a possible restart), and it
prevents rolling updates from getting stuck when it hits a node that's
down. But the global orchestrator will still try to create tasks on down
nodes when it reconciles a service. This is very inconsistent.
Change the global orchestrator to treat down nodes like drained nodes -
all their tasks get shut down immediately, and they get ignored by
reconciliation until they become ready again.
cc @cyli @aluzzardi

orchestrator/global: Don't create tasks on down nodes

---

design/store.md

This document describes how the data store works, focusing on the
in-memory storage and transactional interface. A separate document to be
added later will describe how the store uses Raft consensus to replicate
data.

design: Add store.md

---

manager/dispatcher/assignments.go
manager/dispatcher/dispatcher_test.go
manager/drivers/secrets.go

This commit extends SwarmKit secret management with pluggable secret
backends support.
Following previous commits:
docker/swarmkit@eebac27
moby/moby@08f7cf0
Added the following parameters to the plugin request:
```
- ServiceSpec.TaskSpec.ContainerSpec.Hostname - for use in a x509
certificate
- ServiceSpec.EndpointSpec - has desired DNS domains that might be
suitable for an external x509 certificate
- ServiceSpec.Annotations.Name - name of the service
- ServiceSpec.Annotations.Labels - captures environment names, and other
metadata
```
Signed-off-by: Liron Levin <liron@twistlock.com>

Plugable secret backend

---

design/orchestrators.md

This describes what the global and replicated orchestrators do and how
they work. It also explains orchestration components used by the global
and replicated orchestrators, like the restart supervisor and update
supervisor.

design: Add orchestrators.md

---

ca/server.go

Also,  and just watch for changes of the only cluster we care about.  This fixes an occasional data race caused by #2336 where the cluster is accessed outside of a lock.  Alternative is to lock before accessing the cluster ID, but this seems simpler.

[ca] In the CA server, ensure we always have a cluster ID

---

manager/controlapi/secret.go
manager/controlapi/server.go
manager/controlapi/server_test.go
manager/manager.go

Ensure secret driver exist before creating a secret that reference a
driver.
Since plugin getter is always nil in swarmd, it's a little hard to test
the feature on swarmd.
Waiting for moby/moby#34117 for breaking the plugin subsystem
dependencies on libcontainerd.
Signed-off-by: Liron Levin <liron@twistlock.com>

Plugable secret backend - ensure secret driver exist

---

Protobuild.toml
api/README.md
api/api.pb.txt
circle.yml

Use the API stability tool of protobuild to stabilize the proto descriptors in swarmkit. It will generate:
- `api/api.pb.txt` for `api` package
Signed-off-by: He Xiaoxi <tossmilestone@gmail.com>

Stabilize the api proto descriptors in swarmkit

---

manager/orchestrator/task.go
manager/orchestrator/update/updater_test.go

This patch causes the orchestrator to ignore the PullOptions field of a ContainerSpec when determining whether a task is considered to be 'dirty'. It is only ignored if and only if the current state of the task is either READY, STARTING, or RUNNING.
Related to #971

IsTaskDirty: Ignore PullOptions for running tasks

---

manager/manager.go

Set grpc max message size to 128MB.

---

manager/state/raft/raft.go

Adding a new manager node or promoting a worker to a manager fails with "XXX: node lost leader status". After the failure, the leadership does not actually change. Here, my hypothesis is that the reason for raft proposals to fail may not just be ErrLostLeadership.

More logging for raft/processInternalRaftRequest

---

manager/state/raft/raft.go
manager/state/store/memory.go

More comments and logging fixes.

---

circle.yml

Bumps the Go version used to 1.8.4, which contains security fixes; https://groups.google.com/forum/#!topic/golang-announce/1hZYiemnkdE

Bump Go to 1.8.4

---

manager/scheduler/filter.go
manager/scheduler/scheduler_test.go

The "none" driver is a special keyword to disable logging, so don't
filter nodes if the "none" driver is not listed on the nodes, since it's
not really a driver and doesn't exist.

Don't filter nodes if logdriver==none

---

manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/networkallocator_test.go
manager/allocator/networkallocator/portallocator.go
vendor.conf
vendor/github.com/docker/libnetwork/bitseq/sequence.go
vendor/github.com/docker/libnetwork/bitseq/store.go
vendor/github.com/docker/libnetwork/drivers/overlay/ovmanager/ovmanager.go
vendor/github.com/docker/libnetwork/idm/idm.go
vendor/github.com/docker/libnetwork/ipam/allocator.go
vendor/github.com/docker/libnetwork/ipamapi/labels.go
vendor/github.com/docker/libnetwork/types/types.go
vendor/github.com/docker/libnetwork/vendor.conf

Since cherry pick fails due to code reorg, I have manually updated the respective files.
(cherry picked from commit fe0d7f63cd93f9cb65c8533393a1447f4f55c63c)
(cherry picked from commit ed271d4ae37d782f53d70f04535850239aff2722)

Backport Adding ipam options to ipam driver requests #2324

---

manager/state/raft/raft.go
manager/state/raft/transport/mock_raft_test.go
manager/state/raft/transport/peer.go
manager/state/raft/transport/transport.go

Since #2375 was merged, we've been getting `context deadline exceeded` while sending large raft snapshots. After investigation from @anshulpundir and I, it seems that the gRPC context timeout was too short at 2 seconds to be sufficient for sending large snapshots. This PR increases the default value to 45 seconds. Testing from @davidwilliamson confirms that this fixes the issue.
cc @anshulpundir @aluzzardi @stevvooe @aaronlehmann @marcusmartins @mghazizadeh 

Increase gRPC request timeout to 20 seconds for sending snapshots

---

agent/exec/controller.go
api/types.pb.go
api/types.proto
manager/allocator/network.go
manager/orchestrator/constraintenforcer/constraint_enforcer.go
manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

There are some cases when a task can't advance from a particular state because preconditions are not met. For example, if no nodes meet its constraints, it will not advance to "assigned".
Currently, we put a note about this in the `Message` field of `TaskStatus`, but this is not surfaced to the user. It wouldn't make sense to expose `Message` prominently because it usually contains uninteresting notes about how the task reached that state. Its presence does not indicate that something is wrong.
Expand the scope of `Err` to also cover non-terminal errors that are blocking the task from progressing, and use it in those cases.
Ideally we would also use this to surface IP allocation failures that block a task in "new", but the current design of the allocator would loop if we updated a task on …

api: Use TaskStatus Err field for non-terminal errors

---

manager/scheduler/filter.go
manager/scheduler/scheduler_test.go

Backport:
* https://github.com/docker/swarmkit/pull/2396 Don't filter nodes if logdriver==none
With cherry-pick of 9608c63:
```
$ git cherry-pick -s -x 9608c63
```
Went in clean.

[17.10] Don't filter nodes if logdriver==none

---

manager/state/raft/raft.go
manager/state/raft/transport/mock_raft_test.go
manager/state/raft/transport/peer.go
manager/state/raft/transport/transport.go

Cherry pick #2391.
`git cherry-pick -s -x e3e2821fe3eae707915b78215526da078d2d75a7`

[17.10] Increase gRPC request timeout to 20 seconds when sending snapshots

---

manager/state/raft/raft.go
manager/state/raft/transport/mock_raft_test.go
manager/state/raft/transport/peer.go
manager/state/raft/transport/transport.go

Cherry-pick #2391 
`git cherry-pick -s -x e3e2821fe3eae707915b78215526da078d2d75a7`

[17.06] Increase gRPC request timeout to 20 seconds when sending snapshots

---

manager/controlapi/node.go
manager/controlapi/node_test.go

When a node is removed, delete all of its attachment tasks, so that any networks being used by those tasks can be successfully removed.
Provides a workaround to the state where a node with attachments is somehow removed from the cluster while attached to a network, preventing the network from being removed. Does not fix many other related bugs.

Delete node attachments when node is removed

---

manager/controlapi/node.go
manager/controlapi/node_test.go

When a node is removed, delete all of its attachment tasks, so that any
networks being used by those tasks can be successfully removed.
Provides a workaround to the state where a node with attachments is
somehow removed from the cluster while attached to a network, preventing
the network from being removed. Does not fix many other related bugs.
Includes a unit test for the function that removes node attachment
tasks.

[17.06] Delete node attachments when node is removed

---

ca/keyreadwriter.go
manager/allocator/network.go
manager/controlapi/network.go
manager/controlapi/service.go
manager/dispatcher/dispatcher.go
manager/logbroker/broker_test.go
manager/orchestrator/update/updater.go
manager/scheduler/scheduler.go
manager/state/raft/raft.go
manager/state/raft/storage/storage.go

Cherry picks #2377 to v17.03. Does not apply cleanly. Also involves making changes not in the original patch, but in the spirit of that patch.
(cherry picked from commit aa2c48b53cbae5203b8cf81262eaccf8be353ca6)
/cc @anshulpundir

[v17.03] Fix linter errors.

---

manager/controlapi/node.go
manager/controlapi/node_test.go

When a node is removed, delete all of its attachment tasks, so that any
networks being used by those tasks can be successfully removed.
Provides a workaround to the state where a node with attachments is
somehow removed from the cluster while attached to a network, preventing
the network from being removed. Does not fix many other related bugs.
Includes a unit test for the function that removes node attachment
tasks.
Cherry picks #2409 to 17.03. Cherry-pick applies cleanly.
(cherry picked from commit 0c7b2fc23685c6ab80f2d1c82ce63d66dd3f25ba)

[v17.03] Cherry-pick Delete node attachments when node is removed

---

manager/state/raft/raft.go

Cherry-pick #2391 
I had to manually make these changes, since the cherry-pick wasn't clean. I think this needs a code review.
cc @anshulpundir @aaronlehmann @andrewhsu @thaJeztah 

[17.03] Increase gRPC request timeout to 20 seconds when sending snapshots

---

connectionbroker/broker.go
manager/state/raft/transport/transport.go

gRPC connects to proxy by default (https://github.com/docker/swarmkit/commit/c23aa65fc646081600eb206c2f2dcff5a9e25143), breaking swarmkit. This change provides a basic custom dialer to override the proxy dialer for manager <-> manager and manager <-> worker connections.

Provide custom gRPC dialer to override default proxy dialer

---

api/genericresource/parse.go
api/genericresource/parse_test.go
cmd/swarmctl/service/flagparser/flags.go
cmd/swarmctl/service/flagparser/resource.go
cmd/swarmd/main.go
design/generic_resources.md

Signed-off-by: Renaud Gaubert rgaubert@nvidia.com
*What I did:*
Changed the CLI format of Generic Resources as suggested by @thaJeztah in docker/cli/pull/429
From `--generic-resources "apple=2;orange={blue,red,green}"`
To `--generic-resources "apple=2,orange=blue,orange=red,orange=green"`
This new format albeit a bit more verbose is the CSV format and is already used for `--mount`
- See [here](https://github.com/moby/moby/issues/33439) for tracking
- See [here](https://github.com/docker/swarmkit/blob/master/design/generic_resources.md) for design document
*How to verify it:*
```
$ swarmd ... --generic-resources "apple=2,orange=blue,orange=red,orange=green"
$ swarmct service create ... --generic-resources "orange=2,apple=2"
```

Generic resource cli

---

api/types.pb.go
api/types.proto
manager/orchestrator/taskreaper/task_reaper.go

Based on recent conversations about 'orphaned' task state and the task reaper. Just wanted to capture these in the code for better readability.

Comments for Task Reaper.

---

manager/scheduler/filter.go

hanging off issue #2401 add mapping for aarch64 to arm64

issue 2401 - normalize "aarch64" architectures to "arm64"

---

manager/scheduler/filter.go

Cherry-pick https://github.com/docker/swarmkit/pull/2411.
`git cherry-pick -s -x 9d702763118b132cbe9005a80625ba2160089c3d`

[17.11] normalize "aarch64" architectures to "arm64"

---

manager/scheduler/filter.go
manager/scheduler/scheduler_test.go

When a LogDriver is provided without a name, as part of the service spec, the plugin filter fails to find a suitable node. This PR fixes that behavior, by ignoring the filtering for log drivers when the name isn't provided.
Fix https://github.com/docker/swarmkit/issues/2392

Avoid running plugin filter when Log Driver does not have a Name

---

manager/manager.go
manager/state/raft/raft.go

We recently saw an issue where the cluster object was not found in the store during keymanager init. Adding some minor debug info. Probably not super helpful, but suggestions welcome.
cc @nishanttotla 
Signed-off-by: Anshul Pundir anshul.pundir@docker.com

Adding logging to keymanager and cluster store object create.

---

manager/controlapi/cluster.go
manager/controlapi/cluster_test.go
manager/controlapi/node.go
manager/keymanager/keymanager_test.go
manager/manager.go
manager/orchestrator/global/global.go
manager/orchestrator/replicated/services.go
manager/orchestrator/update/updater_test.go

Currently, the cluster name is hardcoded and is expected to not change for the swarmkit to function. Enforcing that by returning an error if cluster name change is attempted.

Error on cluster spec name change.

---

manager/orchestrator/update/updater.go

Cherry-pick #2308.
`git cherry-pick -s -x 6728c52055ba639312a293306cf58ce4be5d2aa6`

[17.06] orchestrator/update: Only shut down old tasks on success

---

api/api.pb.txt

Update with make generate.

---

manager/controlapi/cluster.go
manager/controlapi/cluster_test.go
manager/controlapi/node.go
manager/keymanager/keymanager_test.go
manager/manager.go
manager/orchestrator/global/global.go
manager/orchestrator/replicated/services.go
manager/orchestrator/update/updater_test.go

Cherry-pick https://github.com/docker/swarmkit/pull/2436.
`git cherry-pick -s -x 0b078d10da563bd8c1d4f3a795a81a5d2dbf5232`

[17.09] Error on cluster spec name change

---

manager/controlapi/node.go
manager/controlapi/node_test.go

Cherry-pick of https://github.com/docker/swarmkit/pull/2409 for 17.09
```
git checkout -b 17.09-backport-workaround-attachments upstream/bump_v17.09
git cherry-pick -s -S -x 0c7b2fc23685c6ab80f2d1c82ce63d66dd3f25ba
```
When a node is removed, delete all of its attachment tasks, so that any
networks being used by those tasks can be successfully removed.
Provides a workaround to the state where a node with attachments is
somehow removed from the cluster while attached to a network, preventing
the network from being removed. Does not fix many other related bugs.
Includes a unit test for the function that removes node attachment
tasks.
(cherry picked from commit 0c7b2fc23685c6ab80f2d1c82ce63d66dd3f25ba)
ping @dperny @anshulpundir PTAL

[17.09] Delete node attachments when node is removed

---

connectionbroker/broker.go
manager/state/raft/transport/transport.go

Cherry-pick of https://github.com/docker/swarmkit/pull/2419 for 17.09
```
git checkout -b 17.09-backport-proxy upstream/bump_v17.09
git cherry-pick -s -S -x 312be5983e2d2f01f0cbcc99d027b28433256705
```
(cherry picked from commit 312be5983e2d2f01f0cbcc99d027b28433256705)
ping @anshulpundir @nishanttotla PTAL

[17.09] Provide custom gRPC dialer to override default proxy dialer (#2419)

---

api/api.pb.txt

Protobuf was updated to version 3.5, in commit
https://github.com/docker/swarmkit/pull/2448/commits/9b981e255e4b3172b54db76e3c96021f981f3e27 (https://github.com/docker/swarmkit/pull/2448), but files were not regenerated.
These are the changes after running `make generate` after installing protobuf 3.5
Relates to https://github.com/docker/swarmkit/issues/2444
ping @dperny @stevvooe @anshulpundir

Regenerate protobuf for 3.5

---

api/ca.pb.go
api/control.pb.go
api/dispatcher.pb.go
api/health.pb.go
api/logbroker.pb.go
api/raft.pb.go
api/resource.pb.go
api/watch.pb.go
ca/auth.go
ca/server.go
manager/controlapi/ca_rotation.go
manager/controlapi/cluster.go
manager/controlapi/common.go
manager/controlapi/config.go
manager/controlapi/network.go
manager/controlapi/node.go
manager/controlapi/secret.go
manager/controlapi/service.go
manager/controlapi/task.go
manager/dispatcher/dispatcher.go
manager/dispatcher/nodes.go
manager/health/health.go
manager/logbroker/broker.go
manager/resourceapi/allocator.go
manager/state/raft/raft.go
manager/state/raft/transport/mock_raft_test.go
manager/watchapi/watch.go
protobuf/plugin/raftproxy/raftproxy.go
protobuf/plugin/raftproxy/test/service.pb.go
protobuf/plugin/storeobject/storeobject.go

from the function's description; https://github.com/docker/swarmkit/blob/c23aa65fc646081600eb206c2f2dcff5a9e25143/vendor/google.golang.org/grpc/rpc_util.go#L393-L399
```go
// Errorf returns an error containing an error code and a description;
// Errorf returns nil if c is OK.
//
// Deprecated; use status.Errorf instead.
func Errorf(c codes.Code, format string, a ...interface{}) error {
return status.Errorf(c, format, a...)
}
```

Replace deprecated grpc.Errorf() with status.Errorf()

---

manager/manager.go
manager/state/raft/raft.go
manager/state/raft/transport/mock_raft_test.go
manager/state/raft/transport/peer.go
manager/state/raft/transport/transport.go

Since we can now stream snapshots between raft nodes, we can revert the grpc workarounds.

Revert grpc max message size/large timeout workaround for snapshot shipping between raft nodes

---

manager/allocator/cnmallocator/portallocator.go
manager/allocator/cnmallocator/portallocator_test.go

Fixes a bug where if a service has the same number of host-mode published ports with PublishedPort 0, changes to the spec would not reflect in the service object.
Also altered the unit tests to be more informative, and added a new unit test case for this bug.

Fix changing host target port

---

manager/orchestrator/replicated/replicated_test.go
manager/orchestrator/replicated/slot.go

This PR adds support for making the task termination order deterministic when scaling down.
Please refer to #2264 for more details. (closes #2264)

Make the task termination order deterministic

---

cmd/swarmctl/common/common.go

It will support swarmctl on windows(etc, swarmctl.exe -s //./pipe/swarm.sock cluster inspect default)

use xnet.DialTimeoutLocal for swarmctl grpc Dialer

---

manager/allocator/allocator_test.go
manager/allocator/cnmallocator/networkallocator.go

Tracking down [libnetwork/1790#issuecomment-308222053](https://github.com/docker/libnetwork/issues/1790#issuecomment-308222053).  The report is that if on a single node several services are started, and if this node is then rebooted, all the services appear to come back but some of them are no longer reachable.
On probing, the cause turned out to be an invalid assignment of IP addresses to services when they were restored.  Specifically, the same IP address was assigned to one service's VIP and also a different service's endpoint.  The result was that packets got delivered to the wrong container and caused symptoms like services or ports unreachable.
This is very likely to also be the cause of [moby/#35675](https://github.com/moby/moby/issues/35675) and other duplicate-IP or overlapping …

Added required call to allocate VIPs when endpoints are restored

---

manager/allocator/allocator_test.go
manager/allocator/cnmallocator/networkallocator.go

Opening a new PR to get things moving. The original back port PR https://github.com/docker/swarmkit/pull/2472

[Backport 17.12] Added required call to allocate VIPs when endpoints are restored

---

manager/orchestrator/taskreaper/task_reaper.go
manager/orchestrator/taskreaper/task_reaper_test.go

Tasks in the complete state were not cleaned up because the task reaper was only looking at task.Status.State >= api.TaskStateShutdown, but the COMPLETE state (api.TaskStateCompleted) is the actual "first" terminal state.
/cc @anshulpundir

Fix task reaper not cleaning up COMPLETE tasks

---

manager/orchestrator/taskreaper/task_reaper.go
manager/orchestrator/taskreaper/task_reaper_test.go

Tasks in the complete state were not cleaned up because the task reaper
was only looking at task.Status.State >= api.TaskStateShutdown, but the
COMPLETE state (api.TaskStateCompleted) is the actual "first" terminal
state.
Added a test for the initialization stage of the task repear. This runs
the logic of which tasks to clean up through its paces, but doesn't test
the run-time logic of the task reaper (it's ability to respond to
updates to tasks).
Cherry-pick of docker/swarmkit#2473
Cherry pick does not apply cleanly. In addition, cherry pick requires
changes to `manager/orchestrator/taskreaper/task_reaper_test.go`,
because of a difference in the API of the task reaper.
(cherry picked from commit e5b310727c4c8b186c774b4e28d154c3fb4e32b8)

[v17.06.5] Cherry-pick "Fix task reaper not cleaning up COMPLETE tasks"

---

manager/orchestrator/taskreaper/task_reaper.go
manager/orchestrator/taskreaper/task_reaper_test.go

Tasks in the complete state were not cleaned up because the task reaper
was only looking at task.Status.State >= api.TaskStateShutdown, but the
COMPLETE state (api.TaskStateCompleted) is the actual "first" terminal
state.
Added a test for the initialization stage of the task repear. This runs
the logic of which tasks to clean up through its paces, but doesn't test
the run-time logic of the task reaper (it's ability to respond to
updates to tasks).
Cherry-pick of docker/swarmkit#2473
Cherry pick does apply cleanly
(cherry picked from commit e5b310727c4c8b186c774b4e28d154c3fb4e32b8)
Signed-off-by: Eli Uriegas <seemethere101@gmail.com>

[17.12] Fix task reaper not cleaning up COMPLETE tasks

---

manager/allocator/cnmallocator/networkallocator.go
manager/allocator/cnmallocator/networkallocator_test.go
manager/allocator/cnmallocator/portallocator.go
vendor.conf
vendor/github.com/docker/libnetwork/bitseq/sequence.go
vendor/github.com/docker/libnetwork/bitseq/store.go
vendor/github.com/docker/libnetwork/drivers/overlay/ovmanager/ovmanager.go
vendor/github.com/docker/libnetwork/idm/idm.go
vendor/github.com/docker/libnetwork/ipam/allocator.go
vendor/github.com/docker/libnetwork/ipamapi/labels.go
vendor/github.com/docker/libnetwork/types/types.go
vendor/github.com/docker/libnetwork/vendor.conf

Backport of https://github.com/docker/swarmkit/pull/2324 for 17.09
```
git checkout -b 17.09-backport-ipam upstream/bump_v17.09
git cherry-pick -s -S -x ed271d4ae37d782f53d70f04535850239aff2722
git cherry-pick -s -S -x fe0d7f63cd93f9cb65c8533393a1447f4f55c63c
```
ping @abhi @anshulpundir @mavenugo PTAL

[17.09] Adding ipam options to ipam driver requests

---

manager/allocator/allocator_test.go
manager/allocator/networkallocator/networkallocator.go

Since cherry pick doesnt apply cleanly, I manually backported docker/swarmkit#2468
Cherry Picked from docker/swarmkit#2468:
Addressing duplicate IP issue on ingress network from 5fd25d2bf65d543f0a36c0202a305d063bf443e5
Added required call to allocate VIPs when endpoints are restored  2397ddf3c1da3a2265f7cd2a56fe22ea66b6e374
<----Original Commit Message----->
Tracking down libnetwork/1790#issuecomment-308222053. The report is that if on a single node several services are started, and if this node is then rebooted, all the services appear to come back but some of them are no longer reachable.
On probing, the cause turned out to be an invalid assignment of IP addresses to services when they were restored. Specifically, the same IP address was assigned to one service's VIP and also a …

[Backport 17.06.5] #2468 Added required call to allocate VIPs when endpoints are restored

---

cmd/swarm-rafttool/dump.go
cmd/swarm-rafttool/main.go

The swarm raft logs and snapshots are useful, powerful debugging tools, but they contain very sensitive cluster information. This change adds a `--redact` flag to both dump-wal and dump-snapshot, which removes secret and config data, and removes container environment variables. The dumps will still contain sensitive information, but not rising to the level of passwords or encryption keys.

Add option to redact sensitive cluster information from state dumps

---

design/task_model.md

Updating design docs based on new behavior introduced in https://github.com/docker/swarmkit/pull/2461.
Ping @dperny @anshulpundir 

Update design to describe desired state REMOVE behavior for tasks

---

agent/agent.go
agent/session.go
connectionbroker/broker.go
manager/dispatcher/dispatcher.go

Added info logs to the agent to track the manager its connecting to,  timeouts, heartbeat from the dispatcher.

[agent] debug logs for session, node events on dispatcher, heartbeats

---

manager/dispatcher/dispatcher.go

Fixes for synchronizing the dispatcher shutdown with in-progress rpcs. This addresses the case where the Dispatcher.Register() rpc races with Dispatcher.Stop() and reinserts into the dispatcher node store after it has been cleaned up by Stop().
We'll hold off on changing the grace period for agents until we have tested this fix at scale.

[manager/dispatcher] Synchronization fixes

---

manager/orchestrator/taskreaper/task_reaper.go

Ensure task reaper stopChan is closed no more than once

---

manager/dispatcher/dispatcher.go

git cherry-pick 0b2778a95b0a493b04bae128652bd2e69c1fe6e2
Cherry pick was clean, with negligible conflict resolution

[manager/dispatcher] Synchronize Dispatcher.Stop() with incoming rpcs.

---

api/api.pb.txt

Protobuf was updated to version 3.5, in commit https://github.com/docker/swarmkit/pull/2448/commits/9b981e255e4b3172b54db76e3c96021f981f3e27 (https://github.com/docker/swarmkit/pull/2448)
and regenerated in https://github.com/docker/swarmkit/pull/2451/commits/93c3290f31990bf4fe0e01759deea7ac55c4d955 (https://github.com/docker/swarmkit/pull/2451), however in https://github.com/docker/swarmkit/pull/2458/commits/58e42ec9f7f3d241966b1d0f7bc34457888f6aa4 (https://github.com/docker/swarmkit/pull/2458)
those changes were reverted; possibly due to an older version of protobuf being used.
These are the changes after running `make generate` after installing protobuf 3.5.1

Regenerate protobuf for 3.5 (again)

---

manager/allocator/allocator_test.go
manager/allocator/cnmallocator/networkallocator.go
manager/allocator/network.go

Passing and empty EndpointSpec in the service spec
was correctly triggering the VIP allocation but
the leader election was erroneusly handling the IPAM
state restore.
This fix ensure that the EndpointSpec if not specified is
actually added to the ServiceSpec selection endpoint mode VIP.
Also the allocate service has now the restart flag that will skip
the deallocation logic that was erroneously triggered.
Fix: https://github.com/moby/moby/issues/33795

Fix IP overlap with empty EndpointSpec

---

ca/certificates.go
ca/certificates_test.go
ca/config_test.go
ca/keyreadwriter.go
ca/keyreadwriter_test.go
ca/keyutils/keyutils.go
ca/keyutils/keyutils_test.go
ca/pkcs8/pkcs8.go
ca/pkcs8/pkcs8_test.go
ca/testutils/cautils.go
ca/testutils/staticcerts.go
cmd/swarm-rafttool/common.go
cmd/swarm-rafttool/main.go
integration/cluster.go
integration/integration_test.go
manager/deks_test.go
manager/manager.go
manager/manager_test.go
node/node.go
vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go

This is to replace EC Private Keys with PKCS#8 in order to eliminate usage of MD5 in swarmkit when the keys are encrypted or decrypted.

Replace EC Private Key with PKCS#8 PEMs

---

manager/scheduler/scheduler_test.go

Adding this extra unit test to rule out a possible cause for #2392.

scheduler: Adding plugin filter unit test for bind mount

---

cmd/swarm-rafttool/dump.go

When I added the --redact flag for swarm-rafttool, I forgot to include the registry auth token as sensitive data to be redacted, so it was present in redacted raft dumps. This replaces it with a redaction.

Redact registry auth token from swarm-rafttool

---

manager/allocator/allocator_test.go
manager/allocator/cnmallocator/networkallocator.go
manager/allocator/network.go

cherry-pick of https://github.com/docker/swarmkit/pull/2505 for 17.12
```
git checkout -b 17.12-backport-fixendpointspec upstream/bump_v17.12
git cherry-pick -s -S -x bd4e923c241ff1f9a493eab02125edbf6ec0b901
```
(no conflicts)
Passing and empty EndpointSpec in the service spec
was correctly triggering the VIP allocation but
the leader election was erroneusly handling the IPAM
state restore trying to release the VIP.
The fix focuses on proper handling of the restart case.
(cherry picked from commit bd4e923c241ff1f9a493eab02125edbf6ec0b901)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

[17.12] Fix IP overlap with empty EndpointSpec

---

manager/dispatcher/dispatcher.go

This reverts commit 0b2778a95b0a493b04bae128652bd2e69c1fe6e2.
Need to revert since waitgroup Add() and Wait() itself need intricate synchronization and are not atomic. Will implement another way, likely a RWLock as @fcrisciani originally suggested.

Revert "[manager/dispatcher] Synchronize Dispatcher.Stop() with incoming rpcs."

---

manager/controlapi/service.go
manager/controlapi/service_test.go

Ingress network is a special network used only to expose
ports. For this reason the network cannot be explicitly
attached during service create or service update

Ingress network should not be attachable

---

manager/dispatcher/dispatcher.go

(cherry picked from commit 6b163ff64355d7a0a0fcc97af860b7893e90a2c5)
https://github.com/docker/swarmkit/pull/2519

[manager/dispatcher] Synchronize Dispatcher.Stop() with incoming rpcs

---

manager/orchestrator/replicated/task_reaper_test.go

We force set the task state in the unit-tests to verify task reaper behavior, but don't set the desired state, which triggers reconciliation which can race with further task related changes triggered from the unit-test.

[manager/orchestrator/task_reaper] Fix task reaper test to also set the desired state on tasks to prevent reconciliation races

---

agent/agent.go
agent/worker.go

When the agent registers a new session, it should resend all task statuses, in case any were missed by the manager after the last session dropped.
Supercedes #2499, excludes code for batch-updating.

Resend all task statuses on new session

---

manager/dispatcher/dispatcher.go
manager/dispatcher/dispatcher_test.go
manager/manager.go

The motivation for this change is to have a clean slate dispatcher on leadership change. Also, it seems like we could have a stale config on the dispatcher since its not re-initialized when a node regains leadership.

[manager/dispatcher] Initialize the dispatcher on becoming leader

---

manager/state/store/memory_test.go

This PR is a fix for #2536, essentially using the first proposed way of fixing the original issue.
This fixes a possible data race in `manager/state/store/memory_test.go`
An alternative to this fix would be to define a new variable in the following way:
```Go
for c := 0; c != 5; c++ {
...
x := c
go func() {
...
Name: nodeIDs[i%benchmarkNumNodes] + "_" + strconv.Itoa(x) + "_" + strconv.Itoa(i),
...
}
}
```

Fix possible data race in manager/state/store/memory_test.go

---

manager/manager.go

Changes the grpc unary and stream interceptors to implement logging of errors returned by RPCs (while also letting the prometheus interceptors do their thing).
The biggest motivation for this change is that if a client times out while a GRPC method is happening, the client may not ever get an error from the server, but the server should hopefully log an error explaining why it couldn't handle the request (like what part it may have been blocked on).

Log GRPC server errors

---

manager/manager.go
manager/state/raft/raft.go
manager/state/raft/raft_test.go

Updates (*Manager).handleLeadershipEvent to include a log message explaining where the leadership changed, using swarmkit node IDs instead of the raft node ids, at the Info level.

Log leadership changes at manager level

---

cmd/swarmd/main.go
manager/state/raft/raft.go

Motivation for this change is to address recently seen frequent leader elections due to network flakiness.
ElectionTick is recommended to be 10xHeartbeatTick https://github.com/coreos/etcd/blob/master/raft/raft.go#L132

[state/raft] Increase raft ElectionTick to 10xHeartbeatTick

---

agent/session.go

agent: backoff session when no remotes are available

---

agent/worker.go

Add an ID function to StatusReporter, so we can better log what reporter failed.
Granted, this is a lot of extra changes to fix this problematic line:  https://github.com/docker/swarmkit/compare/master...cyli:fix-agent-data-race?expand=1#diff-689e5cbc4a9f04fda8f8cd9749d87db7L438.
We could just take out the reporting on which reporter failed instead, and that would be shorter.  But since we've been having trouble debugging live logs, I thought more information would be more useful than less.
Fixes #2576

Fix agent logging race

---

api/objects.pb.go
api/objects.proto

Commit https://github.com/docker/swarmkit/commit/a3eac7370f744e4273bef620a357c6363dae3b5f#diff-2d262053827f7ee9d77859975113953cR62 (https://github.com/docker/swarmkit/pull/2385) renamed `LbAttachments` to `Attachments`, but did not update this deprecation comment.
ping @stevvooe PTAL

Fix deprecation comment

---

manager/allocator/allocator_test.go
manager/allocator/network.go

This commits adds a fix for restore case where there might a mix of allocated and unallocated
network in raft. During restore the allocator was going over the networks lexicographically which would mean that there might be a chance for an unallocated network say net1 o be allocated the same vxlan
id or subnet pool that was allocated to another networki net2. Because of this during restoring, when allocator tries to allocate the reallocate network net2, it would fail because it allocated network resources to net1 during restore. This would mean services,tasks and network itself would be in a
messed up state.
(cherry picked from commit https://github.com/docker/swarmkit/pull/2571/commits/7f9db677bf1d6413bf6f9a41e4e7349e0dea3d65)
Signed-off-by: Abhinandan <abhi@docker.com>

[backport 17.06]Adding logic to restore networks in order

---

manager/manager_test.go

I've noticed these two tests failing occasionally in CI:
In the `TestManager`, it may take a little while for the dispatcher to come up, so poll until it's up.
In `TestManagerLockUnlock`, we wait for the TLS key bytes to change to test to see whether it has been decrypted after disabling the unlock key.  However, it could have changed due to a renewal due to the previous unlock key rotation.  So when polling, check that it's decrypted.
Also, I just changed all instances of `assert.` to `require.` so that the test fails immediately instead of continuing on and erroring.  Just my personal preference - if anyone particularly objects, I'll be happy to change it back after a discussion.
I was able to replicate the flakiness within 2-5 iterations of running these tests in CI (if I used the SSH …

Fix some flakiness with the manager tests

---

manager/manager.go
manager/role_manager.go
manager/role_manager_test.go

Fixes https://github.com/docker/swarmkit/issues/2548 (please see description there), I think.
Wondering if we should also prevent node removal if the demotion process hasn't completed for a manager (e.g. if the node is still in the raft cluster, we disallow the remove node API call and require that the user try again later).

RoleManager will remove deleted nodes from the cluster membership

---

manager/orchestrator/replicated/task_reaper_test.go
manager/orchestrator/taskreaper/task_reaper.go
manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

Adresses https://github.com/moby/moby/issues/36699
scheduler: changes to ignore unassigned tasks.
task reaper: changes to cleanup unassigned tasks in terminal state.

Scheduler/TaskReaper: handle unassigned tasks marked for shutdown

---

manager/manager.go

- fix the logic that was checking for predefined networks. Before the
GetNetwork was passing the network name, while instead the network ID is
the key that is supposed to be used. The CreateNetwork anyway is doing
the very same check and create the network if not existing.

Avoid predefined error log

---

manager/orchestrator/taskreaper/task_reaper.go
manager/orchestrator/taskreaper/task_reaper_test.go

This PR addresses https://github.com/docker/swarmkit/issues/2555.
cc @docker/core-swarmkit-maintainers 

Task reaper should delete tasks with removed slots that were not yet assigned

---

manager/state/store/memory.go

Fix for #2602
Move the conflicting operation inside the critical section (before the `Unlock()` call).
Fix #2602: timedMutex critical operation outside of critical section

Fix manager/state/store.timedMutex

---

api/ca.pb.go
api/control.pb.go
api/dispatcher.pb.go
api/health.pb.go
api/logbroker.pb.go
api/raft.pb.go
api/resource.pb.go
api/watch.pb.go
ca/forward.go
protobuf/plugin/raftproxy/raftproxy.go
protobuf/plugin/raftproxy/test/service.pb.go

This switches the current usage of NewContext and FromContext to use the
underlying methods in the metadata package.  The wrappers will be removed in
future versions of grpc.
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Don't use wrappers for grpc metadata

---

manager/allocator/network.go
manager/dispatcher/dispatcher.go

This is to help debug some of the recent issues around tasks stuck in state "new", desired state "running".

[manager/allocator] Logging for allocation workflows

---

manager/allocator/network.go
manager/dispatcher/dispatcher.go
manager/manager_test.go
manager/orchestrator/replicated/task_reaper_test.go
manager/orchestrator/taskreaper/task_reaper.go
manager/orchestrator/taskreaper/task_reaper_test.go
manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go
vendor/github.com/docker/docker/contrib/README.md
vendor/github.com/docker/docker/contrib/nnp-test/nnp-test.c
vendor/github.com/docker/docker/contrib/syscall-test/acct.c
vendor/github.com/docker/docker/contrib/syscall-test/exit32.s
vendor/github.com/docker/docker/contrib/syscall-test/ns.c
vendor/github.com/docker/docker/contrib/syscall-test/raw.c
vendor/github.com/docker/docker/contrib/syscall-test/setgid.c
vendor/github.com/docker/docker/contrib/syscall-test/setuid.c
vendor/github.com/docker/docker/contrib/syscall-test/socket.c
vendor/github.com/docker/docker/contrib/syscall-test/userns.c
vendor/golang.org/x/crypto/otr/libotr_test_helper.c
vendor/golang.org/x/crypto/otr/otr.go
vendor/golang.org/x/crypto/otr/smp.go
vendor/golang.org/x/sys/windows/svc/event.go
vendor/golang.org/x/sys/windows/svc/go12.c
vendor/golang.org/x/sys/windows/svc/go12.go
vendor/golang.org/x/sys/windows/svc/go13.go
vendor/golang.org/x/sys/windows/svc/security.go
vendor/golang.org/x/sys/windows/svc/service.go
vendor/golang.org/x/sys/windows/svc/sys_386.s
vendor/golang.org/x/sys/windows/svc/sys_amd64.s

This PR is a cherry-pick of commits from the following PRs (in order, on top of the bump_v18.03 branch):
https://github.com/docker/swarmkit/pull/2574
https://github.com/docker/swarmkit/pull/2557
https://github.com/docker/swarmkit/pull/2614
In order to fix some test flakiness, I've also cherry-picked https://github.com/docker/swarmkit/pull/2575.
```
git cherry-pick -s -x e3fcf6d9c553e9c69f83df6c49364eb270e62445
git cherry-pick -s -x 88064b5e2a8ca3431285333b37176a13db357648
git cherry-pick -s -x 7f638251835ccc3d791f128e3dbad76ccb9aaebd
git cherry-pick -s -x bef2bd052936d3aefe36cc7e8f6fefeb593e2531
git cherry-pick -s -x 649826059c3b65f2cc54c88de9e448174dfb15ff
```
All cherry-picks were clean.
cc @anshulpundir @chungers @rchourasia @andrewhsu

Cherry picking scheduler and task reaper fixes, plus allocator logging.

---

integration/integration_test.go
manager/deks.go
manager/deks_test.go
manager/manager.go
manager/manager_test.go
manager/state/raft/raft.go
manager/state/raft/storage.go
node/node.go

This PR ~~is based on https://github.com/docker/swarmkit/pull/2562, and~~ propagates the FIPS boolean to other parts of the manager that need it.  This also documents the `KeyReadWriter` and `RaftDEKManager` better, so that reviewers can understand how they interact.
~~To view these changes alone, please see https://github.com/docker/swarmkit/pull/2586/files/b2da71c62612e2109d563fa05a764284caf0ec74..7003b358d8051bce2615d2ae5cd1e30c585250b4.~~ (no need, #2562 was merged)
The code changes are actually fairly small ~~- most of the change is comments and a [prose doc](https://github.com/cyli/swarmkit/blob/b2ec3d83c3523fe593121bf76a46482ca7d75170/design/raft_encryption.md) about raft encryption~~.  There are also some test changes to make sure that the fips boolean is handled properly, and a …

[fips] Propagate the FIPS boolean to the manager, raft storage layer, and raft DEK management

---

manager/allocator/network.go
manager/dispatcher/dispatcher.go
vendor/github.com/docker/docker/contrib/README.md
vendor/github.com/docker/docker/contrib/nnp-test/nnp-test.c
vendor/github.com/docker/docker/contrib/syscall-test/acct.c
vendor/github.com/docker/docker/contrib/syscall-test/appletalk.c
vendor/github.com/docker/docker/contrib/syscall-test/exit32.s
vendor/github.com/docker/docker/contrib/syscall-test/ns.c
vendor/github.com/docker/docker/contrib/syscall-test/raw.c
vendor/github.com/docker/docker/contrib/syscall-test/setgid.c
vendor/github.com/docker/docker/contrib/syscall-test/setuid.c
vendor/github.com/docker/docker/contrib/syscall-test/socket.c
vendor/github.com/docker/docker/contrib/syscall-test/userns.c
vendor/github.com/opencontainers/runc/libcontainer/nsenter/README.md
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter.go
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_gccgo.go
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
vendor/golang.org/x/crypto/otr/libotr_test_helper.c
vendor/golang.org/x/crypto/otr/otr.go
vendor/golang.org/x/crypto/otr/smp.go
vendor/golang.org/x/sys/windows/svc/event.go
vendor/golang.org/x/sys/windows/svc/go12.c
vendor/golang.org/x/sys/windows/svc/go12.go
vendor/golang.org/x/sys/windows/svc/go13.go
vendor/golang.org/x/sys/windows/svc/security.go
vendor/golang.org/x/sys/windows/svc/service.go
vendor/golang.org/x/sys/windows/svc/sys_386.s
vendor/golang.org/x/sys/windows/svc/sys_amd64.s

Cherry pick https://github.com/docker/swarmkit/pull/2614
CI failure is due to the flaky test in https://github.com/docker/swarmkit/pull/2575. I tried cherry picking that, but to make it work, we need to cherry-pick at least https://github.com/docker/swarmkit/pull/2246 and https://github.com/docker/swarmkit/pull/2274 (and potentially more PRs?). I spent some time doing that but it became too hairy.
```
git cherry-pick -s -x bef2bd052936d3aefe36cc7e8f6fefeb593e2531
```
Cherry pick was not clean. Needs quick review.
cc @anshulpundir @chungers @rchourasia

[bump_v.17.06] Logging for allocation workflows

---

ca/keyreadwriter.go
design/raft_encryption.md
manager/deks.go
manager/state/raft/raft.go

In particular, why the `KeyReadWriter` and `RaftDEKManager` are abstracted from each other and their respective responsibilities.
This is useful for reviewing https://github.com/docker/swarmkit/pull/2586, and was cherry-picked from that PR.

[docs] Document how raft encryption works

---

manager/encryption/encryption.go
manager/encryption/encryption_test.go
manager/encryption/fernet.go
manager/encryption/nacl.go

As @justincormack pointed out in https://github.com/docker/swarmkit/pull/2632, `MultiDecrypter`'s `Decrypt` function is somewhat hard to read, and there are no tests for the fallthrough case.  This PR adds those fallthrough tests and also uses explicit returns rather than named return variables in the `Decrypt` function.
Also changes the error message when we can't decrypt the record to be slightly more friendly.

Minor cleanup of raft encryption algorithms 

---

manager/manager_test.go

This backports https://github.com/docker/swarmkit/pull/2575 to 17.06 in an attempt to fix CI flakiness.
cc @nishanttotla

[17.06] Backport manager test fixes

---

api/deepcopy/copy.go

Previously, trying to create a service with `Init` (which is a
BoolValue) would panic. It is now fixed.
Before, `swarmctl service create --init --name=foo --image nginx:alpine` would make the daemon panic, after, it creates the container with the correct spec.
Required for https://github.com/moby/moby/pull/37183 and carrying https://github.com/docker/cli/pull/479

Fix `deepcopy.Copy` panicing with BoolValue

---

manager/allocator/allocator_test.go
manager/allocator/network.go

cherry-pick of https://github.com/docker/swarmkit/pull/2571 for the 18.03 branch
```
git checkout -b 18.03-restore-networks upstream/bump_v18.03
git cherry-pick -s -S -x 7f9db677bf1d6413bf6f9a41e4e7349e0dea3d65
git push -u origin
```
no conflicts, cherry-pick was clean
This commits adds a fix for restore case where
there might a mix of allocated and unallocated
network in raft. During restore the allocator
was going over the networks lexicographically which
would mean that there might be a chance for an
unallocated network say net1 o be allocated the same vxlan
id or subnet pool that was allocated to another networki net2.
Because of this during restoring, when allocator tries
to allocate the reallocate network net2, it would fail
because it allocated network resources to net1 during …

[18.03] Adding logic to restore networks in order

---

design/orchestrators.md
design/task_model.md
design/tla/.gitignore
design/tla/EventCounter.tla
design/tla/Makefile
design/tla/README.md
design/tla/SwarmKit.tla
design/tla/Tasks.tla
design/tla/Types.tla
design/tla/WorkerImpl.tla
design/tla/WorkerSpec.tla
design/tla/models/SwarmKit.cfg
design/tla/models/WorkerImpl.cfg

I want to learn about how SwarmKit works, and extend its documentation. As a first step, I've been reading through the docs in the `design` directory and writing a more formal version of them. If someone familiar with SwarmKit has time to read over and correct my intepretation, that would be great. I marked with `XXX` things I was particularly unsure about. For example, the docs say very little about how a service is removed.
To make it more precise, I've written the document using [TLA+](https://en.wikipedia.org/wiki/TLA%2B) notation, but hopefully it's still readable to people not familiar with that.
So far, this is based only on reading the design docs. I plan to start reading through the Go code soon, but I wanted to get some early feedback first. Once it's correct, …

TLA+ model for SwarmKit tasks

---

manager/dispatcher/dispatcher.go

We noticed repeated CI failures pointing to data races because of unlocked access to the dispatcher context in Heartbeat(). Golang also does not provide any guarantees around read-only operations on objects which are otherwise locked. 
This will likely have a performance impact, which we will evaluate and some of the dispatcher code might need to be re-written accordingly. But correctness is first.

[manager/dispatcher] Replace call to isRunning() to isRunningLocked() in dispatcher Heartbeat()

---

manager/orchestrator/taskreaper/task_reaper.go

cherry-pick 592e8eddfa43ec5fbd6e34da5ad6890dfa9313fb

[orchestrator/task reaper] Backport: Clean up tasks in dirty list for which the service has been deleted.

---

manager/orchestrator/taskreaper/task_reaper.go
manager/orchestrator/taskreaper/task_reaper_test.go

Addresses the following from from https://github.com/docker/swarmkit/issues/2672:
task reaper dirty set is not cleaned up in various different scenarios at the end of tick() and causes high CPU as each additional task causes tick() to be called.
For testing, we should get coverage for cases where the tasks are not expected to be removed from the task reaper dirty set e.g. service already deleted, size of dirty set 1000 but per slot retention limit not reached etc.

[manager/orchestrator/reaper] Clean out the task reaper dirty set at the end of tick()

---

manager/orchestrator/taskreaper/task_reaper.go
manager/orchestrator/taskreaper/task_reaper_test.go

The batching logic of the task reaper was previously race-y because of its use of timer.Reset. This fixes the logic to guarantee it's not race-y.
Before resetting the timer, always make sure it's stopped first. Only reset the timer when it is stopped.
Added some maybe kludge-y code which allows checking that the task reaper fires at the appropriate times, and added a test to verify that the task reaper behaves as expected.
/cc @anshulpundir and @dani-docker

Fix task reaper batching

---

api/objects.pb.go
api/storeobject.go
manager/metrics/collector.go
protobuf/plugin/storeobject/storeobject.go

Adds metrics for most of the user-facing store object types. Allows the
user to keep track of how many objects are in the object store at any
given time.
Many of the most pressing issues in swarmkit have been made more difficult to debug by the fact that there is insufficient cluster visibility.
To help alleviate this, I've added metrics for the total number of tasks, services, networks, secrets, and configs in the object store.
Updated the metrics collector package to include more metrics. Refactored some of the API and added some new code gen to make the code cleaner.
WIP, not sure yet.
Added metrics values for total number of tasks, services, …

Add metrics for store object types

---

circle.yml

Release notes: https://golang.org/doc/go1.10

Bump Go to 1.10.3

---

api/objects.pb.go
api/storeobject.go
manager/metrics/collector.go
protobuf/plugin/storeobject/storeobject.go

Adds metrics for most of the user-facing store object types. Allows the
user to keep track of how many objects are in the object store at any
given time.
Cherry picks #2673, applies cleanly
(cherry picked from commit b67abf85fcae39716863aec108144d9408ee9fbe)

[17.06] Add metrics for store object types

---

manager/manager_test.go

Since 17.06 branch was changed, this re-backports the manager fixes from https://github.com/docker/swarmkit/pull/2575 to fix manager test flakiness.

17.06 manager test fix

---

manager/manager.go
manager/role_manager.go
manager/role_manager_test.go

Backports https://github.com/docker/swarmkit/pull/2551 to the 17.06 branch.

[backport, 17.06] RoleManager will remove deleted nodes from the cluster membership

---

.circleci/config.yml

Apparently CircleCI sets a default GOPATH to `/home/circleci/.go_workspace` so go stuff won't fall back on the default of `~/go`.  So we have to set the environment variable for the whole job.  Apparently you can use `~` but not other environment variables when setting environment variables in CircleCI v2.
Anyway, I had set a GOPATH just in case for all our test commands, but I forgot it for the dependency validation, which was why #2688 and #2689 were failing.
Edit:  Nm, apparently `~` is not valid for environment variables, so I guess we go back to setting the GOPATH for every command, or just go with what CircleCI expects the go path to be I guess, which would hopefully make the circleci script more maintainable (no need to remember to set the GOPATH everywhere)

Just use the default GOPATH in CircleCI

---

manager/dispatcher/dispatcher.go
node/node.go

TIL that go timers are racy from #2669.   I noticed the dispatcher also calls `Reset` without ensuring that it's stopped or expired first, so added a similar fix.  (See https://github.com/golang/go/issues/11513)
`dispatcher/heartbeat.go` also has a `Reset` without calling `Stop` first, but this seems ok?  If an extra heartbeat gets triggered, that seems inexpensive and fine?

Fix racy batching on the dispatcher

---

agent/agent_test.go
manager/dispatcher/dispatcher.go

Go 1.11 is stricter, and compilation will fail, revealing these issues;
```
agent/agent_test.go:120: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
agent/agent_test.go:125: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
agent/agent_test.go:130: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
agent/agent_test.go:135: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
agent/agent_test.go:140: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
manager/dispatcher/dispatcher.go:426: Entry.Info call has possible formatting directive %s
manager/dispatcher/dispatcher.go:547: Entry.Debug call has possible formatting directive %s …
```

Fix linting issues revealed by Go 1.11

---

manager/dispatcher/dispatcher.go
node/node.go

cherry-pick of https://github.com/docker/swarmkit/pull/2676 for 18.03
```
git checkout -b 18.03-backport-dispatcher-batch-timer upstream/bump_v18.03
git cherry-pick -s -S -x 317ad86ad8fab82e8e3359d44407951c2e3cb4d2
```
cherry-pick was clean

[18.03] Fix racy batching on the dispatcher.

---

cmd/swarmd/main.go

commit https://github.com/docker/swarmkit/pull/2568/commits/fe9b06392aaa10d4aeb4a36bf4defffaa5556d96 (https://github.com/docker/swarmkit/pull/2568) removed the containerd executor, as it was not currently maintained, but these two flags were left behind and are no longer functional.
see https://github.com/docker/swarmkit/pull/2595#issue-179648668

Remove unused "containerd-addr" and "containerd-namespace" flags

---

manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

Signed-off-by: Dani Louca <dani.louca@docker.com>
BACKPORT v17.06
If a task is not yet assigned (for ex:  `noSuitableNode` ) and its service has been removed, the task stays in the `unassignedTasks` map until a new leader election.
Before re-adding the task to `unassignedTasks` map, the fix checks if the task has a valid service in the store.
steps to repro:
- set daemon.log to debug
- create a service with a node constraint that does not exist:
ex: `docker service create -d --constraint 'node.labels.type == queue' alpine sleep 10000`
- watch the logs, you should see an error 
`no suitable node available for task`
- delete the service and invoke the tick() by creating another service; watch the log and notice the same warning taskID …

address unassigned task leak when service is removed (v17.06 backport)

---

vendor.conf
vendor/github.com/google/certificate-transparency-go/client/multilog.go

The current vendor was between v1.0.9 and v1.0.10; this
change switches the dependency to use golang/protobuf instead
of gogo/protobuf.
full diff: https://github.com/google/certificate-transparency-go/compare/5ab67e519c93568ac3ee50fd6772a5bcf8aa460d...v1.0.10

Update google/certificate-transparency-go to v1.0.10

---

agent/agent_test.go
manager/dispatcher/dispatcher.go

cherry-pick of https://github.com/docker/swarmkit/pull/2693 for 18.03 branch
Go 1.11 is stricter, and compilation will fail, revealing these issues;
```
agent/agent_test.go:120: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
agent/agent_test.go:125: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
agent/agent_test.go:130: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
agent/agent_test.go:135: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
agent/agent_test.go:140: *github.com/docker/swarmkit/api.WeightedPeer composite literal uses unkeyed fields
manager/dispatcher/dispatcher.go:426: Entry.Info call has possible …
```

[18.03] Fix linting issues

---

manager/dispatcher/dispatcher.go

backport of https://github.com/docker/swarmkit/pull/2664 for 18.03
```
git checkout -b 18.03-backport-dispatcher upstream/bump_v18.03 
git cherry-pick -s -S -x caee4da2afedf487d98d4e66da3de5721ba415fa
```
We noticed repeated CI failures pointing to data races because of unlocked access to the dispatcher context in Heartbeat(). Golang also does not provide any guarantees around read-only operations on objects which are otherwise locked. 
This will likely have a performance impact, which we will evaluate and some of the dispatcher code might need to be re-written accordingly. But correctness is first.

[input needed] [18.03] [manager/dispatcher] Replace call to isRunning() to isRunningLocked() in dispatcher Heartbeat()

---

manager/dispatcher/dispatcher.go

backport of #2664 for 17.06
git cherry-pick -s -S -x caee4da2afedf487d98d4e66da3de5721ba415fa
cherry-pick was not clean.
We noticed repeated CI failures pointing to data races because of unlocked access to the dispatcher context in Heartbeat(). Golang also does not provide any guarantees around read-only operations on objects which are otherwise locked.
This will likely have a performance impact, which we will evaluate and some of the dispatcher code might need to be re-written accordingly. But correctness is first.

[backport: 17.06] [manager/dispatcher] Replace call to isRunning() to isRunningLocked() in dispatcher Heartbeat()

---

manager/allocator/network.go

Cherry pick #2235.
git cherry-pick -s -x e91352325579da2af724033599bc391eb7269956
We retry failed allocations every 5 minutes. If something else gets
deallocated, we should trigger the retry immediately in case the
allocations were failing due to IP exhaustion, and the deallocation
freed up an IP.
Signed-off-by: Aaron Lehmann <aaron.lehmann@docker.com>
(cherry picked from commit e91352325579da2af724033599bc391eb7269956)

[Backport 17.06] allocator: Retry failed allocations immediately upon a deallocation

---

manager/orchestrator/task.go
manager/orchestrator/task_test.go

cherry pick of 2955cadbf951e3197a9e173a3e06e31bb96a69b1 / https://github.com/docker/swarmkit/pull/2712
Cherry pick was clean.

[Backport 18.03][orchestrator] Fix task sorting

---

manager/orchestrator/taskreaper/task_reaper.go
manager/orchestrator/taskreaper/task_reaper_test.go

Addresses the following from https://github.com/docker/swarmkit/issues/2672#issuecomment-399598738:
The previous logic for skipping over running tasks in tick() was:
if desired=running AND state <= running then don't delete else delete
For example, if a task is (desired=complete, state=running) then this code will delete it from SwarmKit, causing SwarmKit to believe that its resources are no longer in use, which is not correct.
This fixes the logic to ignore tasks which are running (including tasks which are desired to be shutdown), or which are desired to be running (desired state running).

[manager/orchestrator/reaper] Fix the condition used for skipping over running tasks

---

agent/agent.go

agent: return error when failing to apply network key

---

agent/session.go
ca/certificates.go
ca/certificates_test.go
ca/server_test.go
cmd/swarmctl/main.go
integration/cluster.go
manager/controlapi/ca_rotation_test.go
manager/controlapi/cluster_test.go
manager/controlapi/common_test.go
manager/controlapi/config_test.go
manager/controlapi/network_test.go
manager/controlapi/node_test.go
manager/controlapi/secret_test.go
manager/controlapi/service_test.go
manager/controlapi/task_test.go
manager/dispatcher/dispatcher_test.go
manager/manager_test.go
manager/state/raft/raft_test.go
manager/state/raft/transport/mock_raft_test.go
manager/state/raft/transport/peer.go
protobuf/plugin/raftproxy/test/raftproxy_test.go
testutils/grpc.go

`grpc.ErrorDesc(err)` and `grpc.Code(err)` were deprecated in favor of the "status" package in https://github.com/grpc/grpc-go/commit/b5071124392bfd416c713e6595ac149b387f7186
Replacing these with their equivalent, in case the deprecated methods are removed in future

Replace deprecated grpc functions

---

manager/manager.go

Signed-off-by: nmengin <nicolas@containo.us>
This PR adds a test on the error sent by the function `store.CreateNetwork()` when a manager becomes leader in the way to avoid the creation of an error message for a error which is `nil`.
The `if` statement test if the error is not nil before to log a message.
Start a swarmkit cluster with a log level >= `logLevel.Error`.
Thanks to the modification the errors described below sould not appear:
```
level=error msg="failed to create predefined network bridge" error="<nil>"
level=error msg="failed to create predefined network host" error="<nil>"
````
Delete the error logs generated when prefefined networks are initiliazed successfully, Fixes #2719 .

Test if error is nil before to log it

---

manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

cherry-pick of https://github.com/docker/swarmkit/pull/2706 for the bump_v18.03 branch;
```
git checkout -b 18.03-backport-task_leak upstream/bump_v18.03
git cherry-pick -s -S -x 9d977ce6fe0ecd674a17d596e76d141abb88293b
```

[18.03] address unassigned task leak when service is removed

---

api/objects.pb.go
api/storeobject.go
manager/metrics/collector.go
protobuf/plugin/storeobject/storeobject.go

backport of https://github.com/docker/swarmkit/pull/2673 for 18.03
(this was already backported to 17.06 through https://github.com/docker/swarmkit/pull/2679)
```
git checkout -b 18.03-backport-add-more-metrics upstream/bump_v18.03 
git cherry-pick -s -S -x b67abf85fcae39716863aec108144d9408ee9fbe
```
Adds metrics for most of the user-facing store object types. Allows the
user to keep track of how many objects are in the object store at any
given time.
(cherry picked from commit b67abf85fcae39716863aec108144d9408ee9fbe)

[18.03] Add metrics for store object types

---

manager/orchestrator/taskreaper/task_reaper.go
manager/orchestrator/taskreaper/task_reaper_test.go

Cherry-pick of https://github.com/docker/swarmkit/pull/2677 for the bump_v18.03 branch
```
git checkout -b 18.03-backport-reaper2 upstream/bump_v18.03
git cherry-pick -s -S -x 8c5d35342591be0f095678b71446867cd131ca98
git push -u origin
```
Addresses the following from https://github.com/docker/swarmkit/issues/2672#issuecomment-399598738:
The previous logic for skipping over running tasks in tick() was:
if desired=running AND state <= running then don't delete else delete
For example, if a task is (desired=complete, state=running) then this code will delete it from SwarmKit, causing SwarmKit to believe that its resources are no longer in use, which is not correct.
This fixes the logic to ignore tasks which are running (including tasks which are desired …

[18.03] [manager/orchestrator/reaper] Fix the condition used for skipping over running tasks.

---

manager/allocator/allocator_test.go
manager/allocator/network.go

Instead of allocating an attachment for every network on every node, allocate and deallocate attachments on nodes based off whether or not the node needs the attachment because a task using that network is on the node.
A quick fix for the problem raised in #2721.
Essentially, there are load balancer optimizations that rely on nodes having network attachments (IP addresses) for every network being used on the node. Because we can't know what tasks will be needed by a node until after they've passed through the scheduler, we were previously taking a naive approach of allocating a network attachment for every network and every node. This results in far more IP addresses being used than is necessary, which can quickly exhaust the subnet space on a large cluster.
In this PR, …

Only allocate attachments needed by nodes

---

agent/session.go

Signed-off-by: ruicao <ruicao@alauda.io>
Fix the typo: sesssion -> session

Typo fix: sesssion -> session

---

manager/allocator/allocator.go
manager/allocator/allocator_linux_test.go
manager/allocator/allocator_test.go
manager/allocator/cnmallocator/drivers_ipam.go
manager/allocator/cnmallocator/networkallocator.go
manager/allocator/cnmallocator/networkallocator_test.go
manager/allocator/network.go
manager/controlapi/cluster.go
manager/manager.go
node/node.go

We have two params that have been passed around as part of swarm init
config. As part of refactoring the code, we created NetworkConfig struct
and added address pool and subnet mask length as part of the new struct
Older PR review comment has been addressed in this commit.
Signed-off-by: selansen <elango.siva@docker.com>

Default Address Pool Code Refactor

---

manager/dispatcher/dispatcher.go

There was a rare case where the dispatcher could end up deadlocked when
calling stop, which would cause the whole leadership change procedure to
go sideways, the dispatcher to pile up with goroutines, and the node to
crash.
In a nutshell, calls to the Session RPC end up in a (*Cond).Wait(),
waiting for a Broadcast that, once Stop is called, may never come. To
avoid that case, Stop, after being called and canceling the Dispatcher
context, does one final Broadcast to wake the sleeping waiters.
However, because the rpcRW lock, which stops Stop from proceeding until
all RPCs have returned, was previously obtained BEFORE the call to
Broadcast, Stop would never reach this final Broadcast call, waiting on
the Session RPCs to release the rpcRW lock, which they could not do
until Broadcast was …

[manager/dispatcher] Fix deadlock in dispatcher

---

.circleci/config.yml
Dockerfile
api/api.pb.txt
api/dispatcher.pb.go
api/logbroker.pb.go
api/raft.pb.go
api/types.pb.go
manager/scheduler/constraint_test.go
manager/scheduler/nodeinfo.go
protobuf/plugin/raftproxy/test/service.pb.go

Whitespace changes are caused by the fact that gofmt from go-1.11
uses a different heuristic as to how to format the file, making
the source code that was OK for go-1.10 causing a warning with
go-1.11.
NOTE this whitespace change makes the gofmt from go-1.10 complain,
so please upgrade your golang.

Switch to go 1.11

---

direct.mk

Looks like it was used to get faster incremental builds.
Nowdays (since Go 1.10) there is no need to use it, because
go build cache is used [1].
This fixes `make binaries` on my system where golang is installed
as read-only snap:
```
$ make binaries
🐳 bin/swarmd
go build runtime/cgo: open /snap/go/2635/pkg/linux_amd64/runtime/cgo.a: read-only file system
direct.mk:100: recipe for target 'bin/swarmd' failed
```
[1] https://groups.google.com/forum/#!msg/golang-dev/qfa3mHN4ZPA/X2UzjNV1BAAJ

go {build,test}: rm -i option

---

.circleci/config.yml
Dockerfile

Use unzip options to unpack directly to /usr/local/{include,bin},
to avoid unnecessary I/O.
Unfortunately unzip does not support unpacking from a pipe (due
to a limitation of .zip format -- the index is at EOF) so we still
have to save the .zip to disk, read it back, and remove. If they
could only provide tarballs... *sigh*
// cc @wk8 @anshulpundir

Dockerfile, circleci: update protoc to 3.6.1, simplify install

---

manager/controlapi/ca_rotation.go
manager/controlapi/ca_rotation_test.go

Support the edge case for CA rotation where the current root CA has an external CA URL but not key, and the swarm update adds the same cert and key and removes
the external CA URL.  Previously this would error, because it first made sure that the external CA URLs needed by the old root CA were present. This now succeeds because no root rotation is needed, a key is just being provided where none was present before.
This also adds several additional CA root rotation test cases to validate the case where there was an external CA URL, but the root CA also has a key (the external URL is preferred), and the swarm update for removes the external URL without changing the certificate and key.
This should make it easier to reclaim CA functionality from an external CA if the swarm already has the CA …

Handle an edge case in CA rotation where we reclaim CA service from an external CA

---

manager/allocator/allocator_test.go
manager/allocator/network.go

Fix a nil pointer dereference in the 
https://www.youtube.com/watch?v=bLHL75H_VEM
When the network allocator starts, it performs two passes of allocation. The first, with existingAddressesOnly set to "true", simply re-allocates any already reserved addresses, which make the local driver state consistent with the state in swarmkit's object store. The second pass then performs any outstanding new allocations, from when the allocator last stopped.
Since #2725, nodes only have attachments allocated for them if they have a task currently scheduled which requires those networks. This happens after a task is allocated and scheduled.
Before this change, it was possible that, if a Task was correctly allocated, but the allocator stopped before the Node was also …

Fix nil pointer dereference in node allocation

---

agent/agent_test.go
manager/orchestrator/testutils/testutils.go
manager/state/raft/testutils/testutils.go

I find out that most of the flaky tests looks to be caused by timeout during slowness on test machine.
This theory can be proven by running tests with CPU limit. I used these commands on my four core machine:
```
docker build . -t swarmkit-build
docker run --cpus="3" --rm --name test swarmkit-build make test
```
* Added 5 x 2 second wait time to WaitForCluster function in case when ReadyForProposals() does not return true.
* Increased timeout from one second to two seconds on WatchTaskCreate() function, updated function TestSessionReconnectsIfDispatcherErrors() match with that one.
Fixes flaky tests on #2559 , #2600 and #2661

Increased wait time on test utils WaitForCluster and WatchTaskCreate

---

manager/drivers/secrets.go

I added the following fields to the type SecretsProviderRequest:
* SecretLabels
* ServiceID
* TaskID
* TaskName
* TaskImage
* NodeID
This provides more context for the secret driver when it is requested the value for the secret. It is useful both for audit purposes, e.g. an external system (such as HashiCorp Vault) logging which task requested what secret, as well as in a scenario where the plugin would return a different value (or error) based on e.g. labels on the secret.
I added the fields to the type and to the struct when it is built for the request to be made.
Write a plugin that makes use of the new fields. This would be made easier if https://github.com/docker/go-plugins-helpers/pull/111 were merged.
**- Description for the …

Add additional info for secret drivers

---

manager/state/raft/transport/transport.go

Skipping the usual boilerplate, because this is a kludge, everyone involved knows its a kludge, and we'll revert it in the next release.
Increases the maximum recieved message size for gRPC client connections to math.MaxInt32. This means that large controlapi `List` requests will be proxied correctly.

Increase grpc max recv message size

---

manager/state/raft/transport/transport.go

Backports https://github.com/docker/swarmkit/pull/2775

[18.09] Backport of Increase grpc max recv message size

---

Makefile
containerized.mk
direct.mk
hack/debug

That's basically just a light wrapper around delve, to make it nicer to use
(stops it after the session is done, and doesn't ignore interrupts like
the vanilla version does).
Also amending the containerized Makefile to add the right run options
when using delve. That's controlled by the `DOCKER_SWARMKIT_USE_DELVE`
env variable; it's also possible to override the port delve uses
via the `DOCKER_SWARMKIT_DELVE_PORT` env variable.

Adding a `hack/debug` script

---

cmd/swarmctl/network/inspect.go
cmd/swarmctl/service/inspect.go
manager/controlapi/network.go
manager/controlapi/network_test.go
manager/controlapi/service.go
manager/controlapi/service_test.go
manager/deallocator/deallocator.go
manager/deallocator/deallocator_test.go
manager/manager.go
manager/orchestrator/global/global.go
manager/orchestrator/global/global_test.go
manager/orchestrator/replicated/replicated.go
manager/orchestrator/replicated/replicated_test.go
manager/orchestrator/replicated/services.go
manager/orchestrator/taskreaper/task_reaper_test.go

This patch actually stars to use the deallocator to clean up services, as
well as service-level resources (as of now, only networks).
List of changes:
* networks and services don't get deleted right away any more, that's
now the deallocator's job
* networks and services that are pending deletion are marked as such
by swarmctl
* updated all of the relevant code & tests around network & service
deletion
* added unit tests for new functionalities
A previous patch (https://github.com/docker/swarmkit/pull/2759) introduced a
new component, the deallocator, responsible for cleaning up services and
service-level resources. This patch is actually starting to make use of that
component.
Since the deallocator used to rely on the reaper deleting the tasks belonging …

Actually starting to use the deallocator to clean up services

---

manager/controlapi/service.go
manager/controlapi/service_test.go

backport of https://github.com/docker/swarmkit/pull/2779 for 18.09
```
git checkout -b 18.09_backport_fix_api_error_types upstream/bump_v18.09  
git cherry-pick -s -S -x 2061af766f61f6bc8d3e43d5553fba315f569597
git push -u origin
```
cherry-pick was clean; no conflict

[18.09 backport] Return correct error-codes on conflicting names

---

containerized.mk

Comes in handy e.g. to mount a personalized volume on to /root, I like
having my usual bash and git shortcuts in my dev shell :)
Signed-off-by: Jean Rouge <jer329@cornell.edu>

Adding an (optional) `DOCKER_SWARMKIT_EXTRA_RUN_FLAGS` env var to `containerized.mk`

---

manager/controlapi/service.go
manager/controlapi/service_test.go

Commit 2061af766f61f6bc8d3e43d5553fba315f569597 (https://github.com/docker/swarmkit/pull/2779) fixed the API returning incorrect status codes, but also changed the error message for conflicting service-names to be in line with other objects (secrets, configs); "service XX already exists".
Unfortunately, there are existing consumers of the API that perform string-matching, and changing the error-message resulted in a breaking change.
This patch prepends the `ErrNameConflict` error-message to the error-message, so that those consumers still find the original message, but preserves the enhancement made in 2061af7 (inclusion of the conflicting service name).
With this patch applied, the error message will look like this;
name conflicts with an existing object: service myservice already exists …

Include old error-message for backward compatibility

---

manager/manager.go

This code can panic if `config.NetworkConfig` is nil; https://play.golang.org/p/FqfuJkpWUz9
```go
package main
type NetworkConfig struct {
DefaultAddrPool []string
}
type Config struct {
NetworkConfig *NetworkConfig
}
func main() {
config := Config{}
config.NetworkConfig.DefaultAddrPool = append(config.NetworkConfig.DefaultAddrPool, "foo")
}
```

Fix possible panic if NetworkConfig is nil

---

manager/controlapi/service.go
manager/controlapi/service_test.go

Backport of https://github.com/docker/swarmkit/pull/2797 for 18.09
cherry-pick was clean
Commit 2061af766f61f6bc8d3e43d5553fba315f569597 (https://github.com/docker/swarmkit/pull/2779) fixed the API returning incorrect status codes, but also changed the error message for conflicting service-names to be in line with other objects (secrets, configs); "service XX already exists".
Unfortunately, there are existing consumers of the API that perform string-matching, and changing the error-message resulted in a breaking change.
This patch prepends the `ErrNameConflict` error-message to the error-message, so that those consumers still find the original message, but preserves the enhancement made in 2061af7 (inclusion of the conflicting service name).
With this patch applied, the error message will …

[18.09 backport] Include old error-message for backward compatibility

---

cmd/swarmctl/network/inspect.go
cmd/swarmctl/service/inspect.go
manager/controlapi/network.go
manager/controlapi/network_test.go
manager/controlapi/service.go
manager/controlapi/service_test.go
manager/deallocator/deallocator.go
manager/deallocator/deallocator_test.go
manager/manager.go
manager/orchestrator/global/global.go
manager/orchestrator/global/global_test.go
manager/orchestrator/replicated/replicated.go
manager/orchestrator/replicated/replicated_test.go
manager/orchestrator/replicated/services.go
manager/orchestrator/taskreaper/task_reaper_test.go

This reverts commit 2ba1cd9c6a5cd482b319e10ebfd0cb6fb394a165.
Reverting temporarily to unblock Swarmkit updates in the light
of changes requested on https://github.com/moby/moby/pull/38525

Revert "Actually starting to use the deallocator to clean up services"

---

.gometalinter.json

backport of https://github.com/docker/swarmkit/pull/2811 for 18.09. cherry-pick was clean; no conflicts
gometalinter dropped support for gosimple, which is deprecated anyway
and has been subsumed by staticcheck. This commit removes gosimple from
our list of enabled linters (as it's no longer valid). It does not
enable staticcheck, because staticcheck throws too many errors.

[18.09 backport] Fix make check

---

manager/state/raft/util.go

Signed-off-by: Dani Louca <dani.louca@docker.com>
Followed the same logic as in https://github.com/docker/swarmkit/pull/2419 to use a custom grpc dialer and prevent the use of default dialer which picks up the proxy env variable when a manager is joining the cluster.
The affected method `dial` is only used when manager is joining the cluster  and part of `checkHealth` which is also called on join.
- Follow the link to configure 2 nodes (not part of swarm cluster) to use HTTP Proxy https://docs.docker.com/config/daemon/systemd/#httphttps-proxy
- Enable swarm on `node 1` , `docker swarm init`
- Join `node 2` as manager
Actual Result:
```
[centos@esc-1003-1 ~]$ docker swarm join --token SWMTKN-1-2v3cay35o2yavb2bqge6wvyhg6esdn47g82ydi534npgcd4cym-4rmvy3uo2 …
```

Use custom gRPC dialer to override default proxy dialer

---

manager/state/raft/util.go

backport of https://github.com/docker/swarmkit/pull/2802 for 18.03
Minor conflict in import statements, due to https://github.com/docker/swarmkit/pull/2750 not being in the 18.03 branch
```patch
diff --cc manager/state/raft/util.go
index da44dca6,1a49f76c..00000000
--- a/manager/state/raft/util.go
+++ b/manager/state/raft/util.go
@@@ -1,10 -1,10 +1,15 @@@
package raft
import (
++<<<<<<< HEAD
++=======
+       "context"
+       "net"
++>>>>>>> 3a531f45... use a custom grpc dialer when managers are joining
"time"
+      "golang.org/x/net/context"
+
"github.com/docker/swarmkit/api"
"github.com/docker/swarmkit/manager/state"
"github.com/docker/swarmkit/manager/state/store"
```

[18.03 backport] use a custom grpc dialer when managers are joining

---

manager/state/raft/util.go

backport of https://github.com/docker/swarmkit/pull/2802 for 18.09. cherry-pick was clean; no conflicts

[18.09 backport] use a custom grpc dialer when managers are joining

---

manager/controlapi/service.go
manager/controlapi/service_test.go

Adds validation assuring that if a service uses a Config as a CredentialSpec, then the Config is included in the ConfigRefs with a RuntimeTarget.
Includes a test case, which I verified fails before this change and passes after.

Add validation to CredentialSpec configs

---

manager/controlapi/node.go
manager/controlapi/node_test.go

When a node is deleted, its tasks are asked to restart, which involves putting them into a desired state of Shutdown. However, the Allocator will not deallocate a task which is not in an actual state of a terminal state. Once a node is deleted, the only opportunity for its tasks to recieve updates and be moved to a terminal state is when the function moving those tasks to `TaskStateOrphaned` is called, 24 hours after the node enters the Down state. However, if a leadership change occurs, then that function will never be called, and the tasks will never be moved to a terminal state, leaking resources.
With this change, upon node deletion, all of its tasks will be moved to `TaskStateOrphaned`, allowing those tasks' resources …

Fix leaking task resources when nodes are deleted

---

manager/controlapi/node.go
manager/controlapi/node_test.go

backport of https://github.com/docker/swarmkit/pull/2806 for the bump_v18.09 branch
When a node is deleted, its tasks are asked to restart, which involves
putting them into a desired state of Shutdown. However, the Allocator
will not deallocate a task which is not in an actual state of a terminal
state. Once a node is deleted, the only opportunity for its tasks to
recieve updates and be moved to a terminal state is when the function
moving those tasks to TaskStateOrphaned is called, 24 hours after the
node enters the Down state. However, if a leadership change occurs, then
that function will never be called, and the tasks will never be moved to
a terminal state, leaking resources.
With this change, upon node deletion, all of its tasks will be moved to
TaskStateOrphaned, allowing those …

[18.09 backport] Fix leaking task resources when nodes are deleted

---

vendor.conf
vendor/google.golang.org/grpc/rpc_util.go
vendor/google.golang.org/grpc/transport/http2_server.go
vendor/google.golang.org/grpc/transport/http_util.go
vendor/google.golang.org/grpc/transport/transport.go

full diff: https://github.com/grpc/grpc-go/compare/v1.12.0...v1.12.2
- grpc/grpc-go#2074 transport/server: fix race between writing status and header
- fix grpc/grpc-go#1972 Possible race sending headers from server while receiving message over size limit
- grpc/grpc-go#2074 transport: account for user configured small io write buffer
- fix grpc/grpc-go#2089 Server abruptly terminates connections if write buffer is small enough

bump google.golang.org/grpc v1.12.2

---

node/node.go

There was a "return" missing, therefore the "success" message would always be logged, even in case of a failure.
Also rephrased the messages a bit;
- Use "failed to", as it's used in many other locations, so more consistent
- Removed "Swarm successfully ...", as it should be clear from the rest of the message

Fix missing return before "success" message, and minor rephrasing of errors/logs

---

vendor.conf
vendor/github.com/coreos/etcd/snap/db.go
vendor/github.com/coreos/etcd/snap/metrics.go

full diff: https://github.com/coreos/etcd/compare/v3.3.9...v3.3.12
brings in
- https://github.com/etcd-io/etcd/pull/10041 / https://github.com/etcd-io/etcd/pull/9997 add v3 snapshot metrics (fsync, network)

bump github.com/coreos/etcd v3.3.12

---

manager/allocator/network.go

Fixes;
manager/allocator/network.go:186::error: Entry.Errorf format %s has arg nc.ingressNetwork.Spec.Annotations of wrong type github.com/docker/swarmkit/api.Annotations (vet)

Fix linting error

---

vendor.conf
vendor/github.com/fernet/fernet-go/fernet.go

full diff: https://github.com/fernet/fernet-go/compare/1b2437bc582b3cfbb341ee5a29f8ef5b42912ff2...9eac43b88a5efb8651d24de9b68e87567e029736
- fernet/fernet-go#14 verify should only check ttl if > 0

bump fernet/fernet-go 9eac43b88a5efb8651d24de9b68e87567e029736

---

manager/orchestrator/constraintenforcer/constraint_enforcer.go
manager/orchestrator/constraintenforcer/constraint_enforcer_test.go

This patch updates the ConstraintEnforcer to use the placement constraints from the current service spec rather than the placement constraints from the current task spec because they may be outdated in some cases (e.g., when the service was previously updated to modify placement constrainst but the node to which the task was scheduled still satisfies the constraints. If the node is updated in a way which causes it to no longer satisfy the new constraints then the task should be removed even if it still would satisfy the original task constraints).
I'm not sure how to concisely describe it, but how about:
> Fixed an issue where the constraint enforcer would not correctly reject service tasks with outdated placement constraints.
This patch includes a new unit test in the …

Use Service Placement Constraints in Enforcer

---

manager/orchestrator/constraintenforcer/constraint_enforcer.go
manager/orchestrator/constraintenforcer/constraint_enforcer_test.go

Cherry-pick of #2857 to the 19.03 branch. Applies cleanly.

[19.03 backport] Use Service Placement Constraints in Enforcer

---

manager/orchestrator/update/updater.go

Revert #2804 for reasons outlined in #2861.
I ran `git revert 171d814`, but then realized I forgot to add `--signoff`, so I emptied the commit message to abort the commit. Then, I made this same mistake 2 more times in a row. I am not a clever man.
/cc @thaJeztah
Additionally, this change will be backported to 19.03

Revert "Make Service.UpdateStatus non-ambiguous"

---

manager/allocator/networkallocator/portallocator.go
manager/allocator/networkallocator/portallocator_test.go

CC: @dperny @thaJeztah backport for bump_17.06
Fixes a bug where if a service has the same number of host-mode
published ports with PublishedPort 0, changes to the spec would not
reflect in the service object.
(cherry picked from commit 160205598d1af5ccb6b877aa569bc55dd1d171da)

Fix changing host target port failed

---

manager/orchestrator/global/global_test.go
manager/orchestrator/replicated/update_test.go
manager/orchestrator/taskreaper/task_reaper_test.go
manager/orchestrator/testutils/testutils.go
manager/orchestrator/update/updater.go

It is likely that a large portion of test flakiness, especially in CI, comes from the fact that swarmkit components under test are started in goroutines, but those goroutines never have an opportunity to run. This adds code ensuring those goroutines are scheduled and run, which should hopefully solve many inexplicably flaky tests.

Fix flaky tests

---

agent/session.go
manager/manager.go
node/node.go

Signed-off-by: nmengin <nicolas@containo.us>
Increasing the `grpc.MaxCallRecvMsgSize` option to the connections used by the broker.
By adding the option `rpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(math.MaxInt32))` in the dial options used to initialize the connection.
I made the same kind of changes as https://github.com/docker/engine/pull/102 and https://github.com/moby/moby/pull/39306.
These modifications cannot be done in the client side.
Create a lot of Swarmkit objects (Configs, Secrets, Services) in the little period.
The nodes state will change and the message sent to the managers will be greater than the current authorized size (4194304 bytes) but no error messages will occur. …

Increase max recv gRPC message size to initialize connection broker

---

manager/orchestrator/service.go

A simple but old error has recently become evident. Due to the fact that we read an object and then write it back across the boundaries of a transaction, it is possible for the task object to have changed in between transactions. This would cause the attempt to write out the old task to suffer an "Update out of sequence" error.
This fix simply reads the latest version of the task back out within the boundary of a transaction to avoid the race.
This was caught by swarm integration tests in the engine, but I'm unsure of how to write a test for this race condition that would have consistent behavior.

Fix update out of sequence

---

manager/controlapi/node.go
manager/controlapi/node_test.go

When a node is removed, its tasks are set in state ORPHANED. This does not need to be done for tasks that are already in a terminal state, and if all tasks in all states are updated, the size of the transaction may grow too large to process, and node removal becomes impossible.
This changes to only set non-terminal tasks to state ORPHANED, and terminal tasks are left alone.
Altered the `orphanNodeTasks` function in `manager/controlapi/node.go` to check if a task is in a terminal state before updating it.
Updated the unit test for that function to check correctness of the new behavior.
Fixed an issue where nodes with lots of tasks could not be removed.

Only update non-terminal tasks on node removal.

---

manager/controlapi/node.go
manager/controlapi/node_test.go

https://github.com/docker/swarmkit/pull/2867
cc: @thaJeztah @dperny  
Only update non-terminal tasks on node removal.

[18.09 backport] Only update non-terminal tasks on node removal

---

manager/controlapi/node.go
manager/controlapi/node_test.go

https://github.com/docker/swarmkit/pull/2867
cc: @thaJeztah @dperny 

[19.03 backport] Only update non-terminal tasks on node removal

---

.circleci/config.yml
Dockerfile
agent/worker.go
template/getter_test.go

Did the bump in two steps, so that I can cherry-pick the intermediate 1.11.13 bump into older branches

Bump to golang 1.12.9

---

manager/orchestrator/replicatedjob/orchestrator.go
manager/orchestrator/replicatedjob/orchestrator_test.go
manager/orchestrator/service.go
manager/orchestrator/service_test.go

Added the core reconciliation logic for handling services of replicated jobs. Does not include event-handling or initialization logic, just the function itself, and tests to exercise it.
This PR is against the `feature-jobs` branch, which is the branch upon which all jobs code is being merged until the feature is complete.

[Jobs] Add service reconciliation for replicated jobs

---

manager/orchestrator/globaljob/globaljob_test.go
manager/orchestrator/globaljob/orchestrator.go

Adds basic logic for reconciling global jobs, in addition to tests for that logic. The global jobs counterpart to #2878.

[Jobs] Add global job orchestrator skeleton

---

manager/manager.go

Fixes: https://docker.atlassian.net/browse/ENGORC-2651

Remove hardcoded IPAM config subnet value for ingress network

---

manager/manager.go

backport of https://github.com/docker/swarmkit/pull/2890
Fixes: https://docker.atlassian.net/browse/ENGORC-2651
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>
(cherry picked from commit 9ccb20b27fa9a0e7b88800d7e196fa030da2a6a7)
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>

[19.03 backport] Remove hardcoded IPAM config subnet value for ingress network

---

manager/manager.go

backport of https://github.com/docker/swarmkit/pull/2890
Fixes: https://docker.atlassian.net/browse/ENGORC-2651
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>
(cherry picked from commit 9ccb20b27fa9a0e7b88800d7e196fa030da2a6a7)
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>

[18.09 backport]  Remove hardcoded IPAM config subnet value for ingress network

---

manager/manager.go

Adds the jobs orchestrator to the swarmkit manager. Jobs orchestrator will now start and run with the manager.

[Jobs] Wire up jobs orchestrator to manager

---

manager/controlapi/node.go
manager/controlapi/node_test.go

this is for [ENGCORE-711] and [ENGCORE-937]
backport of https://github.com/docker/swarmkit/pull/2806 and https://github.com/docker/swarmkit/pull/2867 for the bump_v18.03 branch
When a node is deleted, its tasks are asked to restart, which involves
putting them into a desired state of Shutdown. However, the Allocator
will not deallocate a task which is not in an actual state of a terminal
state. Once a node is deleted, the only opportunity for its tasks to
recieve updates and be moved to a terminal state is when the function
moving those tasks to TaskStateOrphaned is called, 24 hours after the
node enters the Down state. However, if a leadership change occurs, then
that function will never be called, and the tasks will never be moved to
a terminal state, leaking resources.
With this …

[WIP][18.03 backport] Fix leaking task resources when nodes are deleted

---

cmd/swarm-rafttool/dump.go

container.PullOptions is nil if the service is deployed without
`--with-registry-auth`.  Observed on client+server 19.03.2.
Fixed a panic in `swarm-rafttool dump-snapshot --redact`.
_stack and affected frame:_
```
$ echo -e 'c\nbt\nframe 4' | dlv exec bin/swarm-rafttool -- -d /tmp/swarmdump  dump-snapshot --redact
Type 'help' for list of commands.
2019-09-20 11:36:08.938888 W | wal: ignored file 0000000000000000-0000000000000000.wal.broken in wal
Active members:
NodeID=p1rqbkyjtikf53p1rrov4wk81, RaftID=39c366065096262f, Addr=192.168.30.101:2377
Removed members:
RaftID=2ae2e29a7ad988cc
RaftID=31a2a4a4c22e495c
RaftID=2c73df5477fe943e
RaftID=791d06f8748db411
RaftID=11143b659a8b722d
> [unrecovered-panic] runtime.fatalpanic() /usr/lib/go/src/runtime/panic.go:847 (hits …
```

Fix nil pointer deref in dump-snapshot --redacted [FIELD-2081]

---

vendor.conf
vendor/github.com/dustin/go-humanize/README.markdown
vendor/github.com/dustin/go-humanize/bigbytes.go
vendor/github.com/dustin/go-humanize/bytes.go
vendor/github.com/dustin/go-humanize/comma.go
vendor/github.com/dustin/go-humanize/commaf.go
vendor/github.com/dustin/go-humanize/ftoa.go
vendor/github.com/dustin/go-humanize/humanize.go
vendor/github.com/dustin/go-humanize/number.go
vendor/github.com/dustin/go-humanize/si.go
vendor/github.com/dustin/go-humanize/times.go

full diff: https://github.com/dustin/go-humanize/compare/8929fe90cee4b2cb9deb468b51fb34eba64d1bf0...v1.0.0
probably most relevant change:
- https://github.com/dustin/go-humanize/commit/64dbdae0d393b7d71480a6dace78456396b55286 Add space between the numbers and units
- closes dustin/go-humanize#21 Space between numerical value and unit symbol for SI output
- related: dustin/go-humanize#32 no space between bytes and units

bump dustin/go-humanize v1.0.0

---

.circleci/config.yml
Dockerfile
api/api.pb.txt
api/dispatcher.pb.go
api/logbroker.pb.go
api/raft.pb.go
api/types.pb.go
manager/scheduler/constraint_test.go
manager/scheduler/nodeinfo.go
protobuf/plugin/raftproxy/test/service.pb.go

backport of;
- https://github.com/docker/swarmkit/pull/2752 Switch to go 1.11
- daf87201f686710974b282d4c0b0c8422e55dac9 Bump Golang 1.11.13
- taken from `#2880`  
Whitespace changes are caused by the fact that gofmt from go-1.11
uses a different heuristic as to how to format the file, making
the source code that was OK for go-1.10 causing a warning with
go-1.11.
NOTE this whitespace change makes the gofmt from go-1.10 complain,
so please upgrade your golang.
[v2: regen pb files]
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
(cherry picked from commit fd2d7f2ef925282e8cd2920efa253151749102ad)
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

[18.09 backport] Switch to go 1.11

---

agent/agent_test.go
manager/orchestrator/global/global_test.go
manager/orchestrator/replicated/update_test.go
manager/orchestrator/service.go
manager/orchestrator/taskreaper/task_reaper_test.go
manager/orchestrator/testutils/testutils.go
manager/orchestrator/update/updater.go
manager/state/raft/testutils/testutils.go

relates to 
- https://github.com/moby/moby/pull/39531 integration-cli: fix swarm tests flakiness
Backports of 
- https://github.com/docker/swarmkit/pull/2762 Increased wait time on test utils WaitForCluster and WatchTaskCreate
- https://github.com/docker/swarmkit/pull/2771 Allow using Configs as CredentialSpecs
- **second commit only** (attempt to fix weirdly broken tests)
- https://github.com/docker/swarmkit/pull/2808 Fix flaky tests
- https://github.com/docker/swarmkit/pull/2870 Fix update out of sequence
```
git cherry-pick -s -S -x 5f167cab731ee75bc6cf3888fd2a4a5b5194f924
git cherry-pick -s -S -x be26111c4a48c44fac04c17c69fd2504aea6db91
git cherry-pick -s -S -x 06a356671bc11e4fd5d754f257f9c5f93ec5c563
git cherry-pick -s -S -x d68ac46e3b11d7384472677d210bb0ce941284dc
```
Minor conflict …

[18.03 backport] Fix update out of sequence

---

manager/orchestrator/jobs/fakes_test.go
manager/orchestrator/jobs/global/reconciler.go
manager/orchestrator/jobs/global/reconciler_test.go
manager/orchestrator/jobs/orchestrator.go
manager/orchestrator/jobs/orchestrator_test.go
manager/orchestrator/jobs/replicated/reconciler.go
manager/orchestrator/jobs/replicated/reconciler_test.go
manager/orchestrator/restart/restart.go
manager/orchestrator/taskinit/init.go

In order to make the jobs reconcilers work correctly with the restart supervisor, they have been altered to never replace failed tasks directly Replacing failed tasks is the purview of the restart supervisor. The jobs reconcilers will only create new tasks when needed.
Additionally, this alters the behavior of the replicated job reconciler with regards to slots -- each new task will get a new slot, and when the job is completed, there will be a Completed task in each slot from 0 to TotalCompletions-1.
Then, makes the tweaks necessary for the Restart Supervisor to support Jobs, which are different from other services in that they deliberately have a desired state of Completed.
Finally, wires up the replicated and global orchestrators to call the restart supervisor to restart tasks that …

[Jobs] Support restarting failing jobs tasks

---

agent/worker_test.go

Previous, worker_test.go included a call to t.Log in the mock task controller. This presented a problem: because goroutines spawned by a test are not exited when the test completes, any holdover goroutines, like the one spawned to close the task controller, live on. This creates a problem when that goroutine calls t.Log on a test that has already completed.
This t.Log call doesn't add enough information to bother worrying about. Further, these goroutines, though they may outlive the test, don't actually affect anything or matter, so there's no rush to fix the test to ensure all goroutines exit.
This ought to fix a frequently observed test flake.

Remove t.Log from mock task controller

---

manager/orchestrator/jobs/global/reconciler.go
manager/orchestrator/jobs/global/reconciler_test.go
manager/orchestrator/jobs/orchestrator_controlapi_integration_test.go
manager/orchestrator/jobs/replicated/reconciler.go
manager/orchestrator/jobs/replicated/reconciler_test.go

Adds code to put old tasks in the Shutdown state when jobs are updated, allowing updates to proceed correctly.

[Jobs] Support job updates

---

agent/worker.go

This reverts commit 42085d2f8e43a3ed90ed289d3f3ed3de57837100.
Turns out it's a bad idea to merge a commit with the word "YOLO" in it.
This commit, when vendored into the docker engine, causes a test to hang. See moby/moby#40309.
The thing this was attempting to fix was worked around in #2919.
/cc @thaJeztah

Revert "YOLO see if this works"

---

api/types.pb.go
api/types.proto
manager/orchestrator/jobs/global/reconciler.go
manager/orchestrator/jobs/global/reconciler_test.go
manager/orchestrator/jobs/orchestrator.go
manager/orchestrator/jobs/orchestrator_controlapi_integration_test.go
manager/orchestrator/jobs/replicated/reconciler.go
manager/orchestrator/jobs/replicated/reconciler_test.go

Fixes some TODOs in the code, adds some logging.
Also, more importantly, fixes updating jobs, so that it is done the right way. Tasks, instead of being shut down, are moved to the desired state of Remove, which allows the Task Reaper to do its work.

[Jobs] Support updates, add logging, etc.

---

agent/agent.go

Fixes leaking subscription contexts, and slightly alters the close procedure for PublishLogs streams. This in turn prevents leaking whole connections, and (hopefully) addresses moby/moby#39916
Very carefully, over the course of six or so hours
Merge it and see if the complaints dry up.

Fix leaking log subscription contexts

---

agent/storage.go
agent/storage_test.go
agent/worker.go
agent/worker_test.go

For a long time, it's been a known fault that tasks.db grows out of control. The reason is that this database is only cleaned up, and old tasks removed, during initialization.
When an assignment to a worker is removed, previously, the assignment was just marked as removed in the tasks database. However, an assignment is only removed from a worker when the task is removed from the manager. The worker does not need to continue to keep track of the task.
Instead of marking a task as no longer assigned, when a task is removed as an assignment, we'll simply delete it from the database.
I'm not 100% sure of what all the task database is responsible for, or why it needs to be persisted, so this change is targeted to have the minimal impact on the system.
This …

Fix leaking tasks.db

---

agent/storage.go
agent/storage_test.go
agent/worker.go
agent/worker_test.go

backport of https://github.com/docker/swarmkit/pull/2938
For a long time, it's been a known fault that tasks.db grows out of
control. The reason is that this database is only cleaned up, and old
tasks removed, during initialization.
When an assignment to a worker is removed, previously, the assignment
was just marked as removed in the tasks database. However, an assignment
is only removed from a worker when the task is removed from the manager.
The worker does not need to continue to keep track of the task.
Instead of marking a task as no longer assigned, when a task is removed
as an assignment, we'll simply delete it from the database.
I'm not 100% sure of what all the task database is responsible for, or
why it needs to be persisted, so this change is targeted to have the
minimal impact …

[19.03 backport] Fix leaking tasks.db

---

api/specs.pb.go
api/specs.proto

Fix bad comment on capability_drop field in protobuf def

---

manager/manager.go

When starting everything up, we try creating a cluster object. If this fails, we log an error, unless it fails because the cluster object already exists. However, we're checking for `store.ErrExist`, which is based on an ID conflict, when the real error returned in this case would be `store.ErrNameConflict`, because we check the name first.
Fixes one of the errors mentioned in moby/moby#38189

Avoid logging bogus error

---

manager/orchestrator/update/updater.go

Signed-off-by: Adam Williams <awilliams@mirantis.com>
When the updateConfig delay parameter is larger than the monitor parameter an error in updating can be missed and rollback not performed.  This fix will check for the case where monitor < delay and use the larger of the two. 
Fixes [37972](https://github.com/moby/moby/issues/37972)
Manual testing that failed update will rollback.

Fix update issue on where service doesn't roll back on failure

---

direct.mk

As a result of protobuild being installed with "go get" and the latest gogoproto master being... incompatible, at best, this commit is a stop-gap patch to make swarmkit work while I figure out how to fix the gogoproto incompatibility.

[bump_v19.03] vendor protobuild

---

template/getter_test.go

The signature for the `agent.NewDependencyManager` function has changed because of CSI support. Adds an empty FakePluginGetter to this constructor so that the tests compile.

[feature-volumes] Fix template tests

---

agent/exec/errors.go

Previously, there was an issue where the agent could panic while attempting to determine if an error was temporary.
Before the change, in `agent/exec/errors.go`, the function `IsTemporary` attempted to drill down to a root cause by iterating through the causes of an error by calling `errors.Cause`. If an error has no cause, then `errors.Cause` returns that same error.
The issue is that somewhere in the depths of some code, it was possible for the error to have an underlying type that was non-comparable; for example, maps and slices are uncomparable types. This would cause a panic, as the uncomparable type cannot be compared even to itself.
However, one can see that `errors.Cause` has its own loop, and drills down to the root cause in its own way. There is no need for us to iterate here. …

Fix panic in agent

---

agent/csi/plugin/manager.go
manager/csi/manager.go
testutils/fake_plugingetter.go

Uses two different interfaces to specify which part of the CSI system a plugin is used as
* `docker.csinode/1.0` is the interface for Node plugins, which should run on the worker.
* `docker.csicontroller/1.0` is the interface for Controller plugins, which should run on the manager
If it is desirable to be able to schedule volumes to the manager node, the plugin can advertise both interfaces.

Use two different interfaces for CSI plugins

---

manager/dirty.go

this was a commit that was left over in https://github.com/docker/swarmkit/pull/2837, and thought it could still be useful when debugging problems.
Before:
panic: unexpected field type in StoreSnapshot
After:
panic: unexpected field type in StoreSnapshot: XXX_NoUnkeyedLiteral struct

Improve information if IsStateDirty() fails

---

agent/exec/errors.go
agent/exec/errors_test.go

follow-up to https://github.com/docker/swarmkit/pull/3024
Implements the suggestion I made in https://github.com/docker/swarmkit/pull/3032#discussion_r737316923
This makes sure we detect temporary errors both with pkg/errors.Wrap()
and with native Go error wrapping.

agent/exec: rewrite IsTemporary() to use errors.As()

---

manager/controlapi/volume.go
manager/controlapi/volume_test.go

Previously, the controlapi volume update function did not compare things with DeepEquals, leading to the bugs. Instead, we now use DeepEquals for comparisons, ensuring that we correctly identify equivalent specs as equivalent.

Fix Volume Update

---

ca/server.go
cmd/swarm-rafttool/main.go
cmd/swarm-rafttool/renewcert.go
manager/controlapi/cluster.go

This is useful for recovering a cluster without wiping cluster state in cases in which a swarm's certificates have expired, such as after restoring from backup.
On all Docker Swarm Mode manager nodes with expired swarm-node certs:
```console
root# systemctl stop docker.service
root# ./swarm-rafttool renew-certs --state-dir /var/lib/docker/swarm/
root# systemctl start docker.service
```
If luck is on your side, the swarm will come back up in the ready state without any configuration loss. The workers will likely also have expired certs, so a leave-rejoin dance may be necessary.

rafttool: add tool to renew cert on a manager node

---

ca/certificates.go
ca/config.go

- relates to https://github.com/opencontainers/go-digest/pull/83
This function was in https://github.com/opencontainers/go-digest/commit/55f675811a1b915549933c64571fd86b2676ba76 (https://github.com/opencontainers/go-digest/pull/33), but the format of the GoDoc comments didn't follow the correct format, which caused it not being picked up by tools as "deprecated".
This patch updates uses in the codebase to use the alternatives.

ca: remove uses of deprecated go-digest.Digest.Hex()

---

direct.mk

- relates to https://github.com/moby/swarmkit/pull/215
- relates to https://github.com/moby/swarmkit/pull/2751
Initially the tests were run twice, once with "-i" to "pre build" the tests;
8ebe4356ea2f659758a130ddbed623b7f7010868
Commit cb50952a3a15a58bbbb76003994a694d7a658872 removed the "-i" options,
as it's no longer needed since go1.10, however it did not remove the
(now duplicate) line, so tests were running twice.
Before this, every test was run twice:
After this, tests are only run once (cutting the time for the unit tests in ~half 😂)

Makefile: coverage: don't run tests twice

---

direct.mk

- relates to https://github.com/moby/swarmkit/pull/3070
Possibly it's using a non-standard location;
cp: cannot stat '/home/circleci/.go_workspace:/usr/local/go_workspace/pkg/mod/github.com/gogo/protobuf@v1.3.2/protobuf': No such file or directory
make: *** [direct.mk:146: go-mod-vendor] Error 1
So, using GOMODCACHE path instead of trying to construct our own.

Makefile: go-mod-vendor: fix copying of gogo/protobuf

---

manager/state/raft/storage/walwrap_test.go

- partially addresses https://github.com/moby/swarmkit/issues/2479
- relates to https://github.com/moby/swarmkit/pull/1701 (which introduced the test)
This test failed on macOS, but passed in CI:
--- FAIL: TestCreateOpenInvalidDirFails (0.00s)
walwrap_test.go:205:
Error Trace:	walwrap_test.go:205
Error:      	An error is expected but got nil.
Test:       	TestCreateOpenInvalidDirFails
time="2022-11-19T14:36:00Z" level=info msg="repaired WAL error" error="unexpected EOF"
FAIL
It looks like this test was always broken; this test was added in 3e2cebe76b8c7e1ae67b89de3b5fa063234edc85 and running the test from that commit and with the Go version used at the time showed the test was failing;
git checkout 3e2cebe76b8c7e1ae67b89de3b5fa063234edc85
docker run -it --rm -v …

manager/state/raft/storage: fix TestCreateOpenInvalidDirFails

---

manager/state/raft/storage/snapwrap.go

Commit https://github.com/etcd-io/etcd/commit/3644c9d67ba0316c1c8f7c7d96316bf739234381 (https://github.com/etcd-io/etcd/pull/13401) changed the signature of fileutil.CreateDirAll to now require a go.uber.org/zap.Logger to be passed.
Unfortunately that's a type (not an interface), which results in go.uber.org/zap.Logger to be a direct dependency.
Looking at what fileutil.CreateDirAll does;
- It checks if each directory exists, and has the expected permissions (0700).
- It checks if each directory is empty.
Given that we already delete the directory (and terminate if that fails) before we create the new location, that functionality is redundant, so we can just as well use `os.MkdirAll()` to achieve the same.

manager/state/raft/storage: MigrateSnapshot fix etcd v3.5.6 compatiblity

---

manager/state/raft/storage/walwrap.go
manager/state/raft/storage/walwrap_test.go

- relates to https://github.com/moby/swarmkit/pull/3085
etcd server v3.5.5 includes a fix to prevent the reader from trying to read more data than available in the file, introduced in https://github.com/etcd-io/etcd/commit/621cd7b9e5aa2ccf634b555e4ebe0037b8975066
> restrict the max size of each WAL entry to the remaining size of the file
>
> Currently the max size of each WAL entry is hard coded as 10MB. If users
> set a value > 10MB for the flag --max-request-bytes, then etcd may run
> into a situation that it successfully processes a big request, but fails
> to decode it when replaying the WAL file on startup.
>
> On the other hand, we can't just remove the limitation, because if a
> WAL entry is somehow corrupted, and its recByte is a huge value, then
> etcd may run out of memory. So …

manager/state/raft/storage: TestReadRepairWAL: fix for etcd v3.5.5

---

.github/workflows/ci.yml

Just checking out the repo to warmup GitHub Actions on this repo so we can open follow-ups to switch to GHA.
cc @thaJeztah 
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

ci: init gha workflow

---

.circleci/config.yml
Dockerfile

Includes security fixes for net/http (CVE-2022-41717, CVE-2022-41720), and os (CVE-2022-41720).
These minor releases include 2 security fixes following the security policy:
- os, net/http: avoid escapes from os.DirFS and http.Dir on Windows
The os.DirFS function and http.Dir type provide access to a tree of files rooted at a given directory. These functions permitted access to Windows device files under that root. For example, os.DirFS("C:/tmp").Open("COM1") would open the COM1 device. Both os.DirFS and http.Dir only provide read-only filesystem access.
In addition, on Windows, an os.DirFS for the directory \(the root of the current drive) can permit a maliciously crafted path to escape from the drive and access any path on the system.
The behavior of os.DirFS("") has changed. Previously, …

update to go1.18.9

---

.circleci/config.yml
.github/workflows/ci.yml
.github/workflows/validate.yml
Dockerfile
README.md
containerized.mk
direct.mk
docker-bake.hcl

Create GHA workflows to validate and run unit/integration tests. This should have the same behavior as CircleCI workflow with some enhancements to reduce build time:
* run unit/integration tests in //
* each validation (lint, fmt-proto, check protos, vendor) is also done in //
Dockerfile has been changed to handle proto, vendor, lint and fmt-proto validation so we don't need to build the whole image as it is currently. Also adds a bake definition to handle the new stages easily.
In follow-up we can remove the CircleCI workflow if we are happy with GHA ones.

ci: validation and unit/integration tests

---

codecov.yml

`codecov.yml` config is invalid: https://app.codecov.io/gh/moby/swarmkit/commit/481f030e3561065657b091b6588d01e97916ff4b
```
$ curl --data-binary @codecov.yml https://codecov.io/validate
Error at ['ignore']: 
must be of list type
```
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

chore: fix invalid codecov config

---

manager/orchestrator/constraintenforcer/constraint_enforcer.go
manager/orchestrator/constraintenforcer/constraint_enforcer_test.go

AssignedGenericResources in constraint_enforcer.go were falsely checked inside a case that enforced Reservations to be set Furthermore, the if statement had a missing !
Signed-off-by: Martin Braun <braun@neuroforge.de>
Fixed a inverted logic bug in constraint_enforcer.go that should fix https://github.com/moby/moby/issues/44378
I added a test for constraint_enforcer_test.go that checks for proper enforcement of generic resources being present. While doing so, I noticed that the checks for AssignedGenericResources were done inside a check for the resources. This seemed wrong, so I moved the logic outside of the if statement.
Fixed a inverted logic bug in constraint_enforcer.go that should fix …

Fixes https://github.com/moby/moby/issues/44378

---

manager/orchestrator/jobs/orchestrator.go
manager/orchestrator/jobs/orchestrator_test.go

Previously, the jobs orchestrators were missing the appropriate code to handle the deletion of a service. As a result, when a service was deleted, the tasks for that service would hang around indefinitely. It's likely that on a leadership change or restart, the tasks would have been deleted, but that's generally not an acceptable process as leadership changes or restarts aren't guaranteed.
Fixes this issue by adding event handling for services, similar to global or replicated services, that moves all tasks for a deleted service into Remove state, flagging them for deletion.

Fix removing tasks when a jobs service is removed

---

agent/csi/plugin/plugin.go
agent/csi/plugin/plugin_test.go
internal/csi/capability/capability.go
manager/csi/convert.go
manager/csi/plugin.go

I was packing  NFS CSI for Swarm on https://github.com/olljanat/csi-plugins-for-docker-swarm/tree/master/csi-driver-nfs when noticed that it was able to create volume and folder to NFS share but mounting volume to didn't worked but instead of it ended up looping these messaged on Docker engine log:
```
INFO[2023-02-04T19:21:08.939610819+01:00] attempting to publish volume                  attempt=1 module=node/agent/csi volume.id=0f9wq7wvz41wxw81u4gfsiy55
DEBU[2023-02-04T19:21:08.939765667+01:00] staging volume succeeded, attempting to publish volume  attempt=1 module=node/agent/csi volume.id=0f9wq7wvz41wxw81u4gfsiy55
INFO[2023-02-04T19:21:08.939788029+01:00] publishing volume failed                      attempt=1 error="rpc error: code = FailedPrecondition desc = volume …
```

CSI: Allow NodePublishVolume even when plugin does not support staging

---

.circleci/config.yml

follow-up https://github.com/moby/swarmkit/pull/3117#issuecomment-1422313753
Similar to https://github.com/docker/cli/pull/3444, adds a dummy CircleCI config file to avoid GitHub status failures reported on branches that don't use CircleCI. This file should be deleted when all branches are no longer dependent on CircleCI.

ci: dummy circleci config

---

go.mod
go.sum
vendor/github.com/docker/docker/client/container_wait.go
vendor/modules.txt

- client: improve error messaging on crash
full diff: https://github.com/docker/docker/compare/v23.0.0-rc.3...v23.0.0

vendor: github.com/docker/docker v23.0.0

---

manager/csi/plugin.go
manager/csi/plugin_test.go

When I was working on to packaging DigitalOcean CSI driver for Swarm in https://github.com/olljanat/csi-plugins-for-docker-swarm/pull/15 I found that PublishVolume gets called before Node ID value is stored.
Returning error on this case looks to trigger Swarm logic to trying publish again until it works. 
However it looks to be that Docker engine need to be restarted once after plugin was installed before NodeID have value so there is more work need ton this area.
Implemented simple value check. Also added separate error message logging because it looks to be that error returned by `PublishVolume` does not appear to log.
Should be fine as long it passes CI.

CSI: Manager PublishVolume verify CSI node ID is not empty

---

manager/allocator/cnmallocator/drivers_network_windows.go
manager/allocator/cnmallocator/manager.go

This PR takes generic driver manager which @corhere built on https://github.com/moby/moby/pull/44983 and includes it to Swarmkit instead of libnetwork like proposed on https://github.com/moby/moby/pull/44983#discussion_r1106200444
In additionally that driver manager is used to register `internal` , `nat` and `l2bridge` drivers for Windows so scenarios explained on https://github.com/moby/moby/pull/44983 can be solved.
Copy/paste from that another PR, minimal refactoring to existing code to support it and revendor to remove libnetwork code which is not needed here anymore.
If we get CI to 🟢 it should enough.

Windows: Support local drivers internal, l2bridge and nat

---

manager/state/raft/transport/peer.go

Rationale is in a comment in the diff explaining the two removed lines.
fixes https://github.com/moby/swarmkit/issues/3113

Fix timeouts from very large raft messages

---

manager/state/raft/transport/peer.go

Address https://github.com/moby/swarmkit/pull/3122#discussion_r1161904910 by taking the recommendation to reduce resource churn.

man/state/raft/trans/peer: use AfterFunc for context watchdog

---

internal/idm/idm.go
internal/idm/idm_test.go
manager/allocator/cnmallocator/portallocator.go

Swarmkit's CNM port allocator is the only remaining user of the libnetwork idm package. Fork the package and cut it down to just what Swarmkit needs so that libnetwork's copy can go away.
Added a copy of the idm package to Swarmkit and cut out the features that Swarmkit doesn't need: datastore persistence or concurrency safety.
I copied package idm from libnetwork into this repo without retaining history. Nothing of value was lost.
I converted package idm to use a plain bitmap instead of a bitseq and did not add any synchronization.
CI

Migrate to local version of package idm

---

manager/scheduler/scheduler.go
manager/scheduler/volumes.go
manager/scheduler/volumes_test.go

Freeing volumes is only done on scheduling ticks, but not every scheduling tick resulted in freeing volumes. This change makes it so that volumes are freed every time a scheduling tick happens, regardless of whether there were any scheduled task changes.
See comments in code

Free unused volumes in more cases

---

api/genericresource/validate.go
api/genericresource/validate_test.go
manager/orchestrator/constraintenforcer/constraint_enforcer_test.go

While fixing https://github.com/moby/moby/issues/44378 for named resources in https://github.com/moby/swarmkit/pull/3082, we inadvertedly broke scheduling for people with discrete resources.
Investigated the code and added more unit tests.
Run the unit tests. Broken behaviour can be reproduced with a setup with gpu_test=5:
https://github.com/moby/moby/issues/44378#issuecomment-1900982928

Fix HasResource inverted boolean error

---

agent/csi/plugin/manager.go
agent/csi/plugin/manager_test.go
agent/csi/plugin/plugin.go
agent/csi/plugin/plugin_fake_test.go
agent/csi/plugin/plugin_test.go
agent/csi/volumes.go
agent/dependency.go
agent/worker_test.go
manager/csi/fakes_test.go
manager/csi/manager.go
manager/csi/manager_test.go
manager/csi/plugin.go
manager/dispatcher/dispatcher_test.go
manager/drivers/provider.go
manager/drivers/secrets.go
manager/manager.go
node/node.go
node/plugin/pluginapi.go
testutils/fake_plugingetter.go

Allow Moby plugins to be used without Swarmkit having to import github.com/docker/docker packages by defining our own interfaces which cover the subset of functionality we use. Adapters will have to be written on the Moby side as their API contains methods which return concrete struct types, [but they only need to be trivial wrappers as their `*plugins.Client` satisfies our `plugin.Client` interface.](https://github.com/moby/moby/blob/6fe7928c8c9b29bcd2d0232c356e76134656901f/daemon/cluster/convert/pluginadapter.go)
The manager/allocator/cnmallocator package was not modified and continues to import the plugin types defined in github.com/docker/docker. It also imports many other packages under github.com/docker/docker. The package will be moved out of Swarmkit into …

agent,manager,node: define our own plugin ifaces

---

agent/exec/errors.go
swarmd/dockerexec/controller.go

Add `Unwrap() error` to custom error types to work with standard library

Add Unwrap error to custom error types

---

manager/csi/fakes_test.go
manager/csi/plugin.go

CSI plugin does not implement plugin.PluginAddr interface so plugin manager will not load any CSI plugins at all. (see agent/csi/plugin/csi/manager.go:111)
Basicly preventing load of any CSI plugin with following error message volume creation failed: plugin for driver "seaweedfs" does not implement PluginAddr
fixes https://github.com/hetznercloud/csi-driver/issues/680
https://github.com/moby/moby/issues/48133

fix CSI plugin load issue (plugin does not implement PluginAddr)

---

ca/config.go

- Added a new `strongTLSCiphers` list defining a secure, modern set of TLS cipher suites.
- Removed weak and deprecated algorithms (_CBC_-mode ciphers) by only allowing _AES-GCM_ and _ChaCha20-Poly1305_.
- Updated both server and client TLS configurations to use `strongTLSCiphers`.
- Created the `strongTLSCiphers` variable containing only secure ciphers.
- Configured `NewServerTLSConfig` and `NewClientTLSConfig` to use a clone of `strongTLSCiphers` via `CipherSuites`.
- Before enforcing strong TLS ciphers, weak _CBC_-mode ciphers were allowed, for example:
- https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256/
- https://ciphersuite.info/cs/TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA/
```
➜  swarmkit git:(master) ✗ nmap --script …
```

Remove weak TLS cipher suites
