moby/swarmkit

ca/config.go
ca/testutils/cautils.go

@aaronlehmann alternatively I can change them to normal `func`.
https://github.com/docker/swarmkit/pull/842

Changing top-level SigningPolicy from var to func

---

MAINTAINERS

Looks like the script in docker/opensource expects this format

fix maintainers TOML

---

manager/keymanager/keymanager.go
manager/manager.go

It fixes panic when node loses leadership and obtains it again later.

manager: create keymanager only when leader

---

cmd/swarmctl/cluster/update.go

This is not supported anymore, adds confusion to --help.

swarmctl: Remove `-f` flag for cluster update.

---

manager/controlapi/service.go

The client is expected to send auth tokens as labels inside the service spec. After this change, the manager will not expect to receive it as part of the context. This makes token handling simpler and easier to replace when we have a secret sharing mechanism.

Stop recovering auth tokens from context

---

Makefile

Makefile: Abort with useful error if build environment is incorrect.

---

manager/controlapi/service.go

```
root@JX:/# swarmctl service update bv7t8gn8hhjw6zracwul74fki --cpu-reservation 0.0001
Error: invalid cpu value 100000: Must be at least %!d(float64=1e+06)
```
I think here want to show this:
```
root@JX:/# swarmctl service update bv7t8gn8hhjw6zracwul74fki --cpu-reservation 0.0001
Error: invalid cpu value 0.0001: Must be at least 0.001
```

fix cpu error msg

---

cmd/swarmctl/node/inspect.go

`Hostname` is already shown in line 30. 

duplicate hostname in node inspect output

---

manager/orchestrator/drain_test.go
manager/orchestrator/restart.go
manager/orchestrator/services.go
manager/orchestrator/tasks.go

Desired state checking was wrong which lead to several race conditions.
Fixes #907

orchestrator: Use correct desired state checks.

---

manager/orchestrator/drain_test.go
manager/orchestrator/tasks.go

When the dispatcher starts, it sets all nodes status as UNKNOWN.
This is a valid state and we should not attempt to re-schedule tasks at
that time.
If the node still fails to reconnect, at that point the Dispatcher will
set the status to DOWN and the orchestrator will reschedule tasks.
Fixes #921

orchestrator: Only consider DOWN nodes invalid.

---

agent/task.go

To avoid heavy CPU usage when encountering ErrTaskRetry, backoff before
issuing a secondary task run. It would be better to do backoff with
jitter but this is sufficient to avoid runaway CPU usage.

agent: backoff on ErrTaskRetry

---

agent/agent.go

Current implementation doesn’t keep the order of incoming tasks list. Goroutines can be scheduled in a different order than they were created. This results multiple `taskManager` instances created for the same task and eventually some tasks getting rejected instead of running.
@stevvooe If you think it's important to not block the main loop you can implement some queue logic there, I went for a simple solution for now. Before #883 there also was no extra goroutine.

Remove parallel processing of task assignments

---

agent/task.go
agent/task_test.go

A flaky unit test exposed a bug in the agent that could lead to
deadlock. The change is simply to avoid the channel send if a run of the
task op is already queued.
Deals with the deadlock in https://circleci.com/gh/docker/swarmkit/2917.

agent: deal with flaky unit test

---

manager/state/store/clusters.go
manager/state/store/memory.go
manager/state/store/memory_test.go
manager/state/store/networks.go
manager/state/store/nodes.go
manager/state/store/services.go
manager/state/store/tasks.go

Names should adhere to DNS conventions, therefore we must make sure we
don't end up with duplicates having the same name with different casing.
Fixes #929

store: Make names case insensitive.

---

manager/controlapi/common.go
manager/controlapi/common_test.go

Restricts to the same names that are allowed for docker containers.
Prevents users from creating services that cannot start because their
names cannot be used as part of docker containers. fixes #897

Add regex to check if name is valid

---

ca/server.go
ca/testutils/cautils.go

Since Run is called in a goroutine, the server may not be ready to
handle RPCs immediately. Use a channel to block until the server is
ready.
cc @diogomonica @abronan
Fixes #958

TestCA: Wait for the CA server to be ready

---

manager/scheduler/filter.go
manager/scheduler/nodeinfo.go
manager/scheduler/scheduler.go

in `createOrUpdateNode`, node's resources are reset to the initial value, without checking whether there are some tasks running in the node and reserving resources. This commit fixes the bug.
Here is an example demonstrating this bug:
* boot 2 nodes, suppose both's nanocpu resource is 2e9
```
$ swarmd -d /tmp/node-1 --listen-control-api /tmp/manager1/swarm.sock --hostname node-1
$ swarmd -d /tmp/node-2 --hostname node-2 --join-addr 127.0.0.1:4242
```
* run a service, redis, and reserve 0.5 cpu resources
```
$ swarmctl service create --name redis --image redis:3.0.5 --cpu-reservation 0.5
```
redis will be assigned to node-1. node-1 cpu resource will be 1.5 e9
* drain node-1
```
$ swarmctl node drain node-1
```
while there is still a task of redis in node-1 and about to shut down, cpu …

reconcile resource in scheduler

---

manager/state/raft/raft_test.go

In test, it says we need 5 nodes. But actually we boot 10 nodes and only use 5 of them.

remove redundant code in raft test

---

manager/state/raft/raft.go

The logic in sendToMember is slightly wrong. We look for a member other
than ourself to query, but there's no error case if we are the only
member in the list. Add a check to make sure
This code should normally not be reached if we are the only member, but
appears to run when an invalid address is passed to Join. A separate
change will prevent nodes with invalid addresses from being added to the
cluster.
Related to #983

raft: Fix edge case panic

---

manager/dispatcher/dispatcher.go
manager/state/raft/raft.go

This PR should fix the deadlock with the dispatcher on loss of quorum, this:
- Removes `sync.WaitGroup` on dispatcher waiting for proposals to be completed
- Keeps track of the proposals on the raft side and cancel the proposals on node shutdown
This impacts the dispatcher though as this will give:
```
ERRO[0099] failed deregistering node after heartbeat expiration  error=failed to update node 3p7qdlm85il8a status to down: context canceled
```
My guess is that this should be harmless as this should retry or recover on Manager(s) restart but I may be missing something so this is worth a careful review.
Please let me know if you have a better approach.
/cc @LK4D4 @aaronlehmann @tonistiigi 

dispatcher, raft: cancel proposals on node shutdown

---

manager/manager.go

One of the necessary parameters for creating a manager is the TCP
address where it will listen for GRPC traffic. It's okay to use a
wildcard address like 0.0.0.0:4242, but the port is still important, so
an empty string isn't a usable value.
Return an error from (*Manager).New if no listen address (or listener)
is provided. This avoids bad behavior in raft if the address is omitted.
cc @abronan @dhiltgen @LK4D4
Closes #983

manager: Return an error if no TCP listen address is provided

---

agent/node.go

In case `LoadOrCreateSecurityConfig` returns before a goroutine is scheduled we may not catch `NodeID`. This logic for cleaning up goroutine turned out to be unnecessary because the only case when `nodeIDChan` is not being written to is the error case and this is already handled by closing the context.
@diogomonica  

Fix possible race on saving NodeID

---

cmd/swarmctl/service/common.go
cmd/swarmctl/service/inspect.go
cmd/swarmctl/service/list.go

For replicated services, we now show replicas as a quotient of running
tasks over desired number of tasks. While the query is expensive, the
wow factor is more than worth it.
Example: 
```
ID                         Name    Image                 Replicas
--                         ----    -----                 --------
c69kj7q8whljylvpl55kvxilp  alpine  alpine                10/10
dhrhzorbf6akupexh5qp1mtsr  redis   localhost:5000/redis  20/20
```
Try it with several services and scale them up and down for maximum OMGZ.

swarmctl: show replicas as a quotient against running

---

agent/node.go

- Don’t setup new CA, it can be recovered from state.
- Fix attempt to join empty address.

Don’t try to join empty address on force-new-cluster

---

cmd/swarmctl/cluster/update.go
cmd/swarmctl/node/inspect.go
cmd/swarmctl/service/inspect.go
cmd/swarmctl/task/inspect.go

This makes "task inspect", "service inspect", and "node inspect" query
the API for only a subset of tasks, not every task in the system.
cc @aluzzardi

swarmctl: Use filters to avoid listing all tasks in queries

---

agent/node.go

There was non-zero chance to get <-waitRole if the context was cancelled,
but the role was unchanged. Because the behavior of "demote" and context cancel
is different(wait for a manager to stop vs. stop manager) it could lead to
forever hanged managers.
ping @tonistiigi @aaronlehmann

node: let manager handle demoting itself

---

ca/server.go
ca/testutils/cautils.go

No one uses `Started` from the `CAServer`, but in general we should fix this pattern because it leads to this bug: https://github.com/docker/swarmkit/issues/998
/cc @aaronlehmann

Removing Started from CA

---

agent/exec/container/adapter.go
agent/exec/container/controller.go
agent/exec/container/controller_test.go

To avoid out of date images when using mutable tags, we now always pull
when preparing a task. This avoids needing a flag, since those who want
to lock an image name can use immutable tags and those who want to
update images on every task creation get the behavior for free.
cc @samalba @tonistiigi @aluzzardi

agent/exec/container: always pull when preparing

---

picker/picker.go
picker/picker_test.go

fix exclude bug in picker select
related to [PR#1001](https://github.com/docker/swarmkit/pull/1001)
ping @stevvooe @sqleejan

picker: exclude some peers in select

---

agent/exec/container/controller.go
agent/exec/container/controller_test.go
agent/exec/container/errors.go

This PR supports health check defined in container image. #975 is relevant, which add the support of health check in cli. 
ping @aluzzardi @stevvooe @nishanttotla 

support health check in image

---

manager/state/raft/raft.go

Demotion depends on raft's Run function noticing that it has been
removed from the cluster, and returning an error.
Before it returns the error, it calls stop() to shut down raft. This
could deadlock in some cases if a proposal was in progress.
Change the context passed to Propose so the proposal will get cancelled
when stop() cancels the context.
cc @LK4D4 @abronan

raft: Avoid deadlock on demotion

---

manager/orchestrator/updater.go

This checks the task's Endpoint field against the service's Endpoint
field to see if tasks need to be replaced to take into account new
endpoint settings.
Endpoint is not a spec, but it is copied directly from the service, so
it's safe to do this comparison. It's actually better than comparing the
specs, because if an arbitrary port is allocated at runtime, this will
ensure that the task and service share the same port value.

orchestrator: Trigger rolling updates when endpoints change

---

manager/allocator/networkallocator/networkallocator.go
manager/controlapi/service.go
manager/controlapi/service_test.go

Currently endpoint spec is not validated at the control api to see if
there are duplicate port configs. Also fixed a duplicate VIP problem
when the endpoint spec was getting updated.

Validate endpointspec in control api

---

ca/certificates.go

A race condition is possible when we renew a certificate at the same
time as another update is being made to a node object.
NodeCertificateStatus is meant to wait until the certificate is issued,
but it does so by waiting for an update to the node object that has the
certificate issuance status set to "issued". If another certificate is
issued shortly before the renewal request, or an unrelated change to the
node object happens at the same time, NodeCertificateStatus may return
the old certificate instead of waiting for the new one.
To work around this, the caller of NodeCertificateStatus must verify
that it's getting a certificate corresponding to the CSR it submitted,
and retry if the CSR does not match.
@jlhawn hit this while testing support for external root CAs.

ca: Verify that CSR in NodeCertificateStatus response matches

---

manager/controlapi/service.go
manager/controlapi/service_test.go

This PR did validate duration to be positive
When using `./bin/swarmctl service create --name=aa --image=redis --update-delay=-100s` and other negative flags, 
Output will be : 
```
root@ubuntu:~# ./bin/swarmctl service create --name=aa --image=redis --update-delay=-100s
Error: TaskSpec: update-delay cannot be negative
root@ubuntu:~# ./bin/swarmctl service create --name=aa --image=redis --restart-window=-100s
Error: TaskSpec: restart-window cannot be negative
root@ubuntu:~# ./bin/swarmctl service create --name=aa --image=redis --restart-delay=-100s
Error: TaskSpec: restart-delay cannot be negative
```
This PR did:
1. validate heartbeatperiod in the client;
2.validate restart-window, restart-delay, update-delay in daemon side;
3.add unit tests for service
Signed-off-by: allencloud …

validate duration to be positive

---

manager/keymanager/keymanager.go
manager/keymanager/keymanager_test.go

Having the keyring size 3 allows the key rotation to happen across the cluster without packet loss even if nodes receive the new key set with some time difference.
Signed-off-by: Santhosh Manohar <santhosh@docker.com>

change keyring size to 3.

---

manager/manager.go

Reading the code and find unused `once` variable.
Feel free to close this PR if have something meaningful here.

Remove unused variable - once

---

picker/picker.go

PickAddr sets p.peer to peer, then returns p.peer.Addr after unlocking
its mutex. It should return peer.Addr instead to avoid triggering a data
race.
Fixes #1052
cc @stevvooe

picker: Fix data race in PickAddr

---

ca/server.go
ca/server_test.go
ca/testutils/cautils.go

We start the CA server when we become the leader. We stop the CA server
when we're no longer the leader.
The Run function has protection against being called multiple times,
which is good. But if we shut down the CA, we need to be able to start
it again later, so Stop needs to reset this channel.
cc @tonistiigi @diogomonica

ca: Fix restarts of the CA server

---

manager/orchestrator/updater.go

The updateTask method atomically shuts down a task and replaces it with
a new one. Calls to updateTask are queued through a channel, and this
happens outside a channel. It's possible that once updateTask is called,
the old task has already been shut down. In this case, shutting down the
task is a no-op, but creating a task adds a new task that shouldn't
exist, and puts us in a bad state. We need to check that the task hasn't
already been shut down to avoid this problem.
Fixes #1054
Fixes #907
cc @tonistiigi @aluzzardi @dongluochen

orchestrator: Fix rolling update race that could create extra tasks

---

cmd/swarmctl/service/flagparser/restart.go

command `./swarmctl service create --name hello --image busybox --args sleep --args 5s --restart-delay 5s` will create a `restart` and set `condition` as `NONE`, as indicated [here](https://github.com/runshenzhu/swarmkit/blob/5c0c815bd465dbb086bca58701e1a86603dfe311/cmd/swarmctl/service/flagparser/restart.go#L46)

set RestartOnAny as default restart condition

---

manager/allocator/networkallocator/networkallocator.go
manager/controlapi/network.go
manager/controlapi/network_test.go

Since we do not support any other driver for both IPAM and network other
than the default, it is better to block a network creation backed by a
non-default driver, right when the network is created.

Block creating network with a non-default driver

---

manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
manager/orchestrator/replicated.go
manager/orchestrator/updater.go

To trigger rolling update reliably and more importantly to not trigger
false rolling updates, updater should compare against change in
EndpointSpec between service and what is present in task. For that task
needs to have a copy of EndpointSpec. Made the necessary changes to fix
rolling update of a service.
Fixes #1057 
/cc @aaronlehmann 

Keep a copy of EndpointSpec in Task for update

---

manager/manager.go
manager/orchestrator/drain_test.go
manager/orchestrator/replicated.go
manager/orchestrator/replicated_test.go
manager/orchestrator/restart_test.go
manager/orchestrator/services.go
manager/orchestrator/task_reaper_test.go

The existing replicated orchestrator scales down by deleting tasks with
the highest slot numbers. This means that if you have a service with the
following tasks:
task slot 1 on node A
task slot 2 on node A
task slot 3 on node A
task slot 4 on node B
task slot 5 on node C
... then scaling from 5 replicas to 3 replicas will shut down all tasks
on nodes B and C, and you end up with 3 tasks on node A.
Improve downscaling to be aware of how many tasks are on each node, and
prefer to shut down tasks in a way that balances the resulting tasks.
After this change, the result in the example above would be one task
each on nodes A, B, and C.
In addition to improving the behavior, this provides an important workaround
for the current lack of rebalancing: one can scale a service up and then scale it …

orchestrator: Better balancing on scale down

---

manager/scheduler/scheduler_test.go

This benchmarks scheduling with constraints, where only 1/3 of the nodes
are eligible to run the tasks.
Under the current implementation, this converges towards the worst-case
linear behavior, because the nodes that meet the constraints end up at
the end of the heap, and findMin has to scan much of the heap to find
them.

Add constrained scheduler benchmarks

---

manager/state/raft/raft.go

to avoid resource leak
ping @abronan @aaronlehmann 

Raft/Node: stop ticker when node is shutdown

---

manager/keymanager/keymanager.go
manager/keymanager/keymanager_test.go

Now that libnetwork has the complete support for overlay datapath encryption generate ipsec keys also by default.
Signed-off-by: Santhosh Manohar <santhosh@docker.com>

Generate keys for gossip & IPSec subsystems by default.

---

agent/exec/container/container.go
api/specs.pb.go
api/specs.proto
cmd/swarmctl/service/flagparser/container.go
cmd/swarmctl/service/flagparser/flags.go

To address some issues with using `Command`/`Args`, the field
documentation has been updated to clarify that Command should only be
used when overriding Entrypoint. For most docker uses, only `Args`
should ever be used, as is done in `runc`.
`Args` is now appended to `Command` if both are present.
A `--command` flag has been added to be able to test that the feature is
working correctly across systems.
cc @aluzzardi

api: clarify Command/Args distinction

---

cli/external_ca.go
cli/external_ca_test.go

When I changed the name of this field in the API, I neglected to make a
matching change to the CLI. Change the parsing so that the format is:
protocol=cfssl,url=https://example.com
instead of
type=cfssl,url=https://example.com
cc @stevvooe @tonistiigi

cli: Change external CA "type" to "protocol"

---

BUILDING.md

The instructions in BUILDING.md say to run
go get github.com/docker/swarmkit/...
This won't work correctly on most platforms because at least one of the
packages is platform-specific.
Change the file to describe downloading swarmkit with go get -d, and
building only with the makefile.
Fixes #1067
cc @stevvooe

Fix building instructions

---

manager/scheduler/indexed_node_heap.go
manager/scheduler/nodeinfo.go
manager/scheduler/scheduler.go

processPreassignedTasks runs through a list of preassigned global tasks
and tries to see if they can be advanced to the next state. If a node is
deleted, there is a brief window where the global tasks assigned to that
node have not been deleted yet. processPreassignedTasks may call
taskFitNode on one of these global tasks, and since taskFitNode does not
check if the nodeInfo call returns a valid node from the heap, this may
cause a nil pointer dereference.
Fix this by checking if nodeInfo returns a valid result.
See https://github.com/docker/docker/issues/24227
BTW: The original idea here was to have `nodeInfo()` return an empty node struct if the node does not exist, and have functions that operate on the node struct check for this and do nothing in that case. This simplifies the code a …

scheduler: Fix panic processing preassigned tasks on node removal

---

agent/node.go

#1046 added new context for single manager session. This resets manager connection if this context is cancelled(on demotion) before connection state changes.
@LK4D4 @aaronlehmann 

Reset connection on manager context cancellation

---

manager/controlapi/node.go
manager/controlapi/node_test.go
manager/controlapi/server.go
manager/state/raft/membership/cluster.go
manager/state/raft/membership/cluster_test.go
manager/state/raft/raft.go

Simply rolls back the role on `node demote` if this fails. There is opportunity for a refactoring here as we can add a check upstream and only selectively update node Spec fields, but not sure if really necessary.
/cc @aaronlehmann @tonistiigi 

raft membership: fix promotion/demotion workflow

---

cmd/swarmctl/cluster/inspect.go

Currently, swarmctl prints out the bcrypted secret and makes it look
like this is the secret that can be specified to join the cluster.
Change it to only indicate whether a secret is set or not.
Fixes #1123 

swarmctl: Don't print out hashed secret

---

manager/state/raft/raft.go
manager/state/raft/storage.go

This fixes the restart process on a single raft Manager node to bypass waiting for the `ElectionTick`. This way the node elects itself instantly.
Related to docker/docker#24077
/cc @aaronlehmann

raft: Fast daemon restart on single Manager cluster member

---

agent/agent.go

There is non-zero chance that select will choose session.errs before
registered if they occured at the same time. So it's possible to get
sequence session.errs -> registered -> session.closed. In that case
backoff will be zero and rand.Int63n will panic.
Fix #1131
ping @stevvooe

agent: don't handle registered on error

---

manager/controlapi/service.go
manager/scheduler/constraint.go
manager/scheduler/expr_test.go

Malformed constraints like `node.name ~ node-2` should fail the service. 

Validate constraint form at controlapi

---

agent/agent_test.go

These additions to agent_test.go passed originally, but after being
merged to master, they fail since the behavior has changed. Remove the
newly-added lines causing the failure.
cc @LK4D4 @stevvooe

Fix bad merge in agent_test.go

---

Godeps/Godeps.json
manager/allocator/networkallocator/networkallocator.go
vendor/github.com/docker/libnetwork/drvregistry/drvregistry.go

swarmkit currently doesnt support remote network drivers (via plugins). But it was dependent on libnetwork's drvregistry which was loading remote IPAM driver by default. This causes https://github.com/docker/docker/issues/23990
The fix is to remove such built-in dependencies in drvregistry and move it to the caller similar to remote network driver.

Removing dependancy on remote IPAM driver

---

manager/state/raft/membership/cluster.go
manager/state/raft/raft.go

If a manager is unresponsive, we may report it as reachable as long as
the TCP socket hasn't closed.
To fix this, bounce the GRPC connection when a ProcessRaftMessage RPC
times out.
This is the manager-side version of the problem in #1136.
See https://github.com/docker/docker/issues/24329
cc @abronan @tonistiigi

raft: Handle unresponsive managers even when the TCP socket stays open

---

agent/agent.go
agent/config.go
agent/node.go

This will cause the picker to open a new connection for the next attempt
at establishing a session.
cc @stevvooe @tonistiigi @LK4D4

agent: Reset picker on a session error

---

manager/state/raft/membership/cluster.go

ReplaceMemberConnection was overwriting field in a Member struct, and
this same member struct (not a copy) was being returned by GetMember. So
a different goroutine could potentially be using this struct while it's
being mutated.
Change ReplaceMemberConnection to make a copy of the struct and replace
the entry in the members map with the copy.
See https://circleci.com/gh/docker/swarmkit/3500
cc @abronan

raft: Fix data race caused by ReplaceMemberConnection

---

manager/manager.go

grpc closes listener twice: in Close and in Server. Second Close can
unlink file created by a new listener. This can happen on fast
promote-demote.
I filled grpc/grpc-go#762 also, not sure if it'll be accepted.

manager: prevent double close on unix listener

---

agent/node.go

If the ready channel is already nil, it's not necessary to assign
it to nil.

Assign ready channel to nil only if it is not nil

---

manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/networkallocator_test.go

When creating a service, the `service.Endpoint.Sepc` gets a copy of
`service.Spec.Endpoint`, however when performing an update,
`service.Endpoint` was not being updated.
This adjusts the network allocator for services to set
`service.Endpoint.Spec` after everything has been allocated.

Ensure endpoint spec is updated on service update

---

agent/exec/container/executor.go

Plugin names in node description aren't sorted right now, this is a short change that sorts them and makes the output stable.
cc @stevvooe 

Sort plugin names in description

---

agent/node.go

Updating role to agent directly in node, so we'll know about demotion early.
Updating role to manager only when certificate issued to avoid starting manager with invalid certificate.
ping @tonistiigi @aaronlehmann @diogomonica 
Fix #1165

node: return waitRole logic and change logic of n.role updates

---

manager/allocator/allocator_test.go
manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go

Make sure once a vip is allocated for a service it is persisted across
restarts and failovers.
Also fixed an issue in task/node allocation tracking logic.

Persist vip allocs for a service across restart

---

manager/allocator/networkallocator/networkallocator.go

If we have already allocate the VIPs for a service, do not allocate them
again when a service update for ports is attempted.

Avoid VIP allocation during service update

---

manager/controlapi/node.go

Currently if a node is in the process of joining as a Manager,
it is being issued a Manager cert and role. Although if this
node issues a 'docker swarm leave', it is impossible to remove
it as we check on the role as a failed precondition.
This PR allows to remove a node with 'docker node rm' if a
node has the manager role but is not yet accepted and
registered in the raft memberlist.
Fixes #1180 
/cc @aaronlehmann @runshenzhu

controlapi: allow removing Manager node if not in raft memberlist

---

manager/state/raft/raft.go

if there are only 2 nodes in the cluster, and leader is leaving before closing the connection, leader has to ensure that follower gets noticed about this raft conf change commit. 
Otherwise, follower would assume there are still 2 nodes in the cluster and won't get elected into the leader by acquiring the majority (2 nodes). Check out [my repo](https://github.com/runshenzhu/swarmkit/commits/raft-leave-join) to reproduce this bug.
This PR fix the problem by sending commit ack back to follower manually, before leader closing connection.
An alternative approach is to keep leader from leaving when there are only 2 nodes in the cluster.
ping: @dperny @aaronlehmann @abronan 
fix #1178

Raft: send commit ack back to follower before closing connection

---

manager/keymanager/keymanager.go

Given the key's clock may be used to derive some key material and security indices by the datapath encryption layer, it is better to add some random offset.
Otherwise the key's clock value is very well predictable today on a freshly started swarm cluster.
Signed-off-by: Alessandro Boch <aboch@docker.com>

Add a random offset to the key's clock

---

agent/task.go

To avoid calling Controller methods concurrently, `Controller.Remove`
is now called only *after* the last operation has proceeded. We do this
by checking to see if the cancellation is available to detect an
outstanding operation needs to be completed. Once the operation returns,
we proceed with the shutdown procedure.
cc @jinuxstyle

agent: call remove after operation is finished

---

manager/controlapi/service.go
manager/controlapi/service_test.go

On create/update to determine if the requested port is already in use
and returns an error immediately if so.
This is unoptimized and must traverse all services to determine what
ports are already in use.

Check for port conflicts on service create/update

---

agent/storage.go
agent/task.go

while profiling swarmkit with pprof, I find that lots of cpu cycles are wasted on unnecessary task copy. It takes about 5% -- 8% total cpu cycles, as shown in the graph:
This PR removes unnecessary task copy.
ping @stevvooe

agent: avoid unnecessary task deep copy

---

manager/orchestrator/restart.go
manager/orchestrator/restart_test.go
manager/orchestrator/task_reaper_test.go
manager/orchestrator/tasks.go

We used to put restarted tasks in READY state. This makes sense because
then they can go ahead and pull an image while we wait for the restart
delay to elapse. However, #715 changed the restart supervisor to put
restarted tasks into ACCEPTED to work around a tight restart loop when
an image doesn't exist. The problem was that the task would fail
immediately, leading the orchestrator to request a new restart, which
would cancel the ongoing restart delay.
As a better fix for this, put tasks in READY, but when a restart is
requested and there is already one in progress for the old task, we wait
for that restart to complete before starting the new one.

Put restarted tasks in READY state

---

manager/controlapi/service.go
manager/controlapi/service_test.go

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

Return error if ports are specified in dnsrr mode

---

agent/agent.go
agent/session.go

This PR makes the node inventory dynamic i.e. changes to node info are passed to the dispatcher. A ticker checks the node info periodically (currently every 20 seconds) and closes the session if changes are found, so that a new one can be created with an updated node description.
I'm trying to test this change thoroughly since it can likely cause race conditions in the main agent loop. The update period will likely have to be tuned to make sure that it doesn't interfere with the dispatcher's rate limiting or the agent's backoff mechanism.
The underlying assumption is that node updates aren't super frequent.
Fixes #279 
Depends on #1172
cc @stevvooe @aluzzardi 

Dynamically update node inventory

---

manager/manager.go

This didn't prove as usable as we hoped, since often cloud setups have
separate network interfaces for internal and external communication.
Instead, we're taking the approach of requiring the user to specify an
address or interface if there's any ambiguity.
Remove the logic that finds the IP address associated with the default
route, since it will no longer be used.
Do not merge until after https://github.com/docker/docker/pull/24237

Remove dial-based address detection logic

---

ca/auth.go
ca/forward.go
manager/manager.go
manager/state/raft/raft.go

Previously, we required a joining node to provide its remotely-reachable
address in the Addr field of the Join request. This places a burden on
admins because they must set up every node that may potentially become a
manager with an IP address in mind.
Allow an address of the form "0.0.0.0:4242" in Addr, and if this is
found, replace it with the address seen by the manager. Add support for
forwarding remote addresses in GRPC headers, for cases where the join
request is proxied.
**Depends on #1119**

raft: Detect remote address on Join

---

agent/node.go
manager/manager.go

This enables us to advertise a different address than the one we listen
on.
Depends on #1119
Should be merged in sync with https://github.com/docker/docker/pull/24237.

Add AdvertiseRemoteAPI node config parameter

---

agent/agent.go
agent/session.go

This reverts commit eb840e19ab40041e96c1957dec8778cadaa0afb3.
This appears to be making certain Docker integration tests flaky after swarmkit is vendored. I'm not 100% sure it's this commit, but reverting it appears to solve the problem in my testing so far. The other commits that I tried reverting did not make a difference.
This may be causing spurious session rebuilds. @aboch reported that with a version of Docker that vendors swarmkit master, he saw errors like this:
```
DEBU[0032] agent: rebuild session                        module=agent
DEBU[0032] (*session).start                              module=agent
ERRO[0032] agent: session failed                         error=rpc error: code = 13 desc = transport: crypto/tls: use of closed connection module=agent
DEBU[0032] agent: rebuild …
```

Revert "Dynamically update node inventory"

---

manager/orchestrator/updater_test.go

This test ran an update that encountered an error and checked that it
stopped after the first task. Because there was no update delay, the
updater could update more than one task before the failure was noticed
(the notification would race with the next update). Add an update delay
to prevent this from happening.
cc @LK4D4 @dongluochen

Fix flaky test TestUpdaterFailureAction

---

manager/scheduler/pipeline.go
manager/scheduler/scheduler_test.go

Since plugins are lazy loaded on use in the engine, tasks that require a
plugin that hasn't been used yet will never be dispatched until the
engine description reports it.
Rather than remove all this code, we have left it in place to be used
when plugin scheduling is added in the future.
cc @aluzzardi @tiborvass

manager/scheduler: disable plugin filter

---

manager/state/raft/raft.go

When restarting a node from its state, logs are reapplied to
restore the cluster membership with `ConfChangeAddNode` log
entries.
There is a chance to reach the portion calling `Campaign` to
restart a single cluster member faster when we are still
in the process of restoring the memberlist. In this case
the node may not appear in the progress list and we might
call `MaybeUpdate` on the node id from the map without
sanity checking thus resulting in a panic.
To avoid that, check if the node is present in the Progress
list before trying to Campaign on node restore.
Fix #1196 
/cc @aaronlehmann @LK4D4 

raft: fix Campaign on restore if the node id is not in the progress list

---

agent/task.go
api/equality/equality.go
api/equality/equality_test.go
manager/dispatcher/dispatcher.go
manager/dispatcher/dispatcher_test.go

From issue #1209 @aluzzardi's comment:  
> The dispatcher sends tasks down to the agent for ANY reason, including task status change. There's no point in sending tasks down to the agent if the status changes since it's the agent updating the status in the first place. Every time the agent updates the status of a task (e.g. From PREPARING to READY), it sends an update to the dispatcher which in turn sends back the list of tasks which is pointless
This change uses `TasksEqual` to decide if a task change should trigger a dispatcher notification to agent. `TasksEqual` is moved from agent to apiutils so that it can be used by agent and dispatcher.  
This change is based on #1216. 
cc @aluzzardi @runshenzhu @stevvooe @aaronlehmann.

Dispatcher sends task modifications in batches

---

manager/dispatcher/dispatcher.go
manager/dispatcher/dispatcher_test.go
manager/dispatcher/nodes.go

dispatcher: Give a couple of minutes for nodes to recover on re-election

---

manager/dispatcher/dispatcher.go
manager/dispatcher/dispatcher_test.go
manager/dispatcher/nodes.go

Reverts docker/swarmkit#1238
Breaks docker/docker integration tests.

Revert "dispatcher: Give a couple of minutes for nodes to recover on re-election"

---

README.md
agent/exec/container/controller.go
agent/task.go
cmd/swarmd/main.go
manager/state/raft/raft.go

1. Fix some comments
2. Update README to indicate that an valid taken is required when
joining a swarm cluster.
3. Remove an useless statement. The ctx variable is never used before
it's re-assigned, so the statement is useless.
Fixes: #1247

Fix doc and remove an useless statement

---

manager/state/raft/raft_test.go
manager/state/raft/storage_test.go
manager/state/raft/testutils/testutils.go

raft test sometime fails because of exceeding proposing time, as shown [here](https://circleci.com/gh/docker/swarmkit/3775).
This PR tries to fix it by make proposing time in test configurable.
ping @aaronlehmann @abronan 

raft test: make proposing time in test configurable

---

manager/manager.go

m.connSelector is set in Run while the manager is starting up. If Stop
is called before this point, m.connSelector might be created after there
is any possibility of stopping it, which would result in a goroutine
leak.
Make Stop wait for the connSelector to be created, to avoid this
situation.
cc @LK4D4

manager: Fix start/stop race

---

ca/server.go

"started" is closed slightly too early, so tests could start sending
requests to the CA server before it was ready to handle them. This bug
was present for awhile, but it was hidden before the join-token changes
because context was also set too early, so isRunning would return true.
This only affects unit tests, since the "started" channel is just used
to make the tests wait for the server to start up. So there should be no
impact on real-world use.
Fixes: #1255
cc @abronan @diogomonica

ca: Don't close "started" channel until the CA server is actually ready

---

picker/picker.go
picker/picker_test.go

I'm trying to keep diffs relatively small, just enough to fix a situation with hard-crashed managers.
ping @aaronlehmann @stevvooe

picker: modify constants so donweights occur rarely

---

agent/node.go
manager/dispatcher/dispatcher.go
picker/picker.go
picker/picker_test.go

To allow the weighting algorithms to work properly, the values of
observation weights need to be selected to be greater than 1. Without
this, the observations, positive or negative, will always converge to 1.
We also relax the smoothing factor to allow the observations to react
faster to changes.
Arguably, we could remove the weight parameter from `Observe` and then
make the manager state truly discrete but that is a much larger change.
cc @LK4D4 @aaronlehmann

picker: increase range of peer observation

---

cmd/swarmctl/service/list.go

When a node was down, and the tasks on the node have been migrated to
other nodes, the result of listing service is a bit confusing like
following, the Replicas is 3/2. It means the number of running tasks
is three while the number of replicas is two. To avoid the confusion,
we should not count the tasks whose hosting node is down as running
tasks.
```
$ swarmctl service ls
ID                         Name         Image           Replicas
--                         ----         -----           --------
974qragx7kjotucroesg17hcx  busybox-top  busybox:latest  3/2
```
v3: check node status not down, suggested by @dongluochen.
v2: ported from docker swarm client based on suggestion from
@aaronlehmann.

Fix confusing result of listing service

---

manager/dispatcher/dispatcher_test.go
manager/dispatcher/nodes.go

ping @aaronlehmann @dongluochen

dispatcher: increase heartbeat period for unknown nodes

---

agent/agent.go
manager/manager.go

We need to recover from "failed node" case as fast as possible.
ping @aaronlehmann @aluzzardi @dongluochen @stevvooe

agent, manager: decrease backoff for session and raftproxy

---

agent/node.go

Closes #1274.
cc @LK4D4 @aaronlehmann @tonistiigi

agent: shutdown connection on node stop

---

ca/certificates.go
ca/certificates_test.go
ca/config.go

Changing minimum certificate rotation period and backdating to 1h

---

manager/scheduler/scheduler.go

When loading a state that contained large numbers of nodes and tasks,
but no ready nodes that could accept the tasks, swarmd used large
amounts of CPU repeatedly trying to schedule the full set of tasks. The
allocator caused many commits on startup (see #1286), and this produced
a large backlog of commit events, each one of which caused a full
scheduling pass.
To avoid this pathological behavior, debounce the commit events
similarly to how the dispatcher's Tasks loop debounces events. When a
commit event is received, that starts a 50 ms countdown to wait for
another commit event before running the scheduling pass. If commit
events keep being received and resetting this timer, the scheduler will
run the scheduling pass anyway after a second.
I think we should consider this for 1.12.1. …

scheduler: Debounce commit events

---

manager/dispatcher/dispatcher.go

The use of TaskEqualStable in the dispatcher to avoid sending
unnecessary task updates is problematic for global services. These tasks
only move to the ASSIGNED state once the scheduler confirms resources
are available. Since state changes are not considered relevant changes
and do not trigger assignment set updates, the dispatcher may never send
this update, and tasks can become stuck in the ASSIGNED state.
If a task is in the state ASSIGNED or below, always count a state change
as a modification, even if nothing else has changed.
Fixes #1291
I know this isn't the cleanest solution, but it seems like the simplest and lowest risk approach for 1.12.1. We can try to find something better for 1.13.
cc @dongluochen @aluzzardi

dispatcher: Always send task updates to agent when state <= ASSIGNED

---

manager/state/raft/raft.go

During debugging, I noticed that there are many calls to n.send
with empty messages array. Add a check to avoid unnecessary
locking.

Check empty messages array

---

cmd/swarm-bench/benchmark.go
cmd/swarm-bench/collector.go
cmd/swarm-bench/main.go
cmd/swarmd/main.go

The context has been correctly plumbed for future use for cancellation
and timeouts. This PR is a little silly but I thought it would be good
to show how to do this correctly.

cmd: correctly plumb context in swarmd, swarm-bench

---

agent/agent.go
agent/node.go
agent/task.go
agent/worker.go
ca/server.go
log/context.go
manager/dispatcher/dispatcher.go
manager/keymanager/keymanager.go

To improve the output of module logging, we now include a path that
represents the modules that a context has passed through. This makes it
easy to tell if a log line came from a particular module hierarchy.
A helper function, `WithModule`, provides an easy way to mark a context
with a module and inject that module into the logger.
The following log lines are an example:
```
DEBU[0005] Root CA updated successfully                  cluster.id=0iaidzbs0zgfngbj5hk66y56r method=(*Server).updateCluster module=ca
DEBU[0005] (*session).start                              module=node/agent
DEBU[0005] RequestAddress(GlobalDefault/10.255.0.0/16, 10.255.0.3, map[])
DEBU[0005] Root CA updated successfully                  cluster.id=0iaidzbs0zgfngbj5hk66y56r method=(*Server).updateCluster module=ca …
```

log: improve module-oriented logging

---

manager/dispatcher/dispatcher.go
manager/dispatcher/dispatcher_test.go

When setting nodes to ready, down, or disconnected, do so in a batch
instead of one node at a time. This can avoid very slow responses to
network partitions or recovery from network partitions.
Tested manually and with the Docker integration tests (needs a slight tweak to one integration test, PR https://github.com/docker/docker/pull/25342).
Fixes #1289
cc @dongluochen @aluzzardi

dispatcher: Batch node updates

---

manager/orchestrator/restart.go

When I was debugging integration test failures a week ago, I dug deep
into the recent restart supervisor changes, and noticed a possible race
which is almost impossible in practice.
This is the sequence of events that has to happen:
1) Restart task A -> new task B.
2) B fails before the restart delay has elapsed (pull failure):
Restart(B) starts waiter goroutine.
3) B's node fails at exact moment after the restart delay finishes. The
orchestrator calls Restart(B) again, this time there's no delay in
progress so Restart proceeds to set B.DesiredState = SHUTDOWN and create
a new task.
4) The waiter goroutine from step 2 is scheduled. It calls Restart(B) to
resume the first restart attempt. This sets B.DesiredState = SHUTDOWN
(which means no change) and creates a new task.
We'd end up with …

orchestrator: Avoid restarting a task that has already been restarted

---

manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

The logic in `setupTasksList` was incorrect. It treated dead tasks as if
they were running. We didn't catch this because this function only runs
on leader failover.
Corrected the function and added a test.
Fixes #1296 
cc @thaJeztah @LK4D4 @dongluochen

scheduler: Properly handle dead tasks when populating data structures

---

manager/state/raft/raft.go
manager/state/raft/testutils/testutils.go

It looks like the election loops on startup are caused by something
proposing a value before all entries in the log have become committed.
This would cause ApplyStoreActions to try and get a lock on the raft
store, while processInternalRaftRequest is holding the lock (since it's
called by the memory store with the lock held). This situation is a
deadlock. It blocks the loop in Node.Run and prevents further
participation in the cluster.
To try and solve the issue, don't signal that the local node has become
the leader until it has committed all the uncommitted entries from
before. Also, block proposals until it is caught up.
WIP because we still need to test and confirm that this fixes the problem.

raft: Fix infinite election loop

---

agent/agent.go
agent/agent_test.go
agent/config.go
agent/node.go
agent/session.go
manager/testcluster/manager_cluster_test.go

Instead call grpc.Dial and (*grpc.ClientConn).Close() directly. Picker
has pretty bad problems when call Reset concurrently - it can block
for a long time and then suddenly close connection which was just
created.
So, in this particular case - less magic is better. There are some other
usages of a picker in ca package, but they seem harmless because there is
no calls to Reset now.
This is part of the fix for slow recovering nodes on leader stop - which leads to wrong scheduling decisions.
ping @aaronlehmann @stevvooe

agent: remove picker usage

---

manager/state/raft/raft.go

ForceNewCluster tells raft to use the existing state to create a new
cluster with a single member. This means that when first reading the
WAL/snapshot, the other existing managers are removed.
However, it doesn't make sense to do this more than once. For example,
if other managers are added to the cluster, and one of them takes over
as the leader, and sends the initial leader a snapshot, that snapshot
should be accepted without modifications.
Change the ForceNewCluster flag to only apply on startup.
cc @abronan

raft: ForceNewCluster flag should only apply at startup

---

ca/config.go
ca/config_test.go

Several tests created certs that expire in 1 minute, and then waited up
to 2 seconds for them to be renewed. But the logic for renewing a cert
only renews it quickly if the cert is expiring in *less than* one
minute. Since CFSSL rounds NotBefore/NotAfter to the nearest minute, we
could end up with a cert that expires in slightly more than one minute,
and it would take some random fraction of that minute to get renewed.
Change the renewal logic to renew certs after a second if they expire
in <= 1 minute, not < 1 minute.
Clean up the related tests (remove an unnecessary for/select loop).

ca: Fix flaky test, clean up test code

---

api/ca.pb.go
api/control.pb.go
api/dispatcher.pb.go
api/health.pb.go
api/raft.pb.go
manager/manager.go
manager/raftpicker/raftpicker.go
protobuf/plugin/raftproxy/raftproxy.go
protobuf/plugin/raftproxy/test/service.pb.go

Just recreate connection on leader change.

raftpicker: do not use picker

---

manager/controlapi/service.go

Currently when there is a collision in port mapping, swarm returns error with service ID:
```
Error response from daemon: rpc error: code = 3 desc = port '80' is already
in use by service cquoc5o30b8c9qlv9x1x1wu4n
```
This might be improved by returning the service name as well, e.g.:
```
Error response from daemon: rpc error: code = 3 desc = port '80' is already
in use by service 'myservice' (cquoc5o30b8c9qlv9x1x1wu4n)
```
This fix adds the service name to the error message.
This fix is related to the comment in:
https://github.com/docker/docker/pull/25428#issuecomment-237841041

Improve the error message for port collision

---

manager/state/raft/raft.go

while `n.IsStopped() ` returns value by checking if `n.Node` is nil, we didn't set `n.Node` correctly in `n.stop()`. This PR fixes it by using `isMember` to tell if the node is stopped.
Also, it should fix #1272.
ping @abronan @LK4D4  

raft: set n.Node and n.isMember to correct value in stop/removeNode

---

manager/state/raft/testutils/testutils.go

If there is only one node (leader) in the cluster, `WaitForCluster` would return directly without checking if this leader is ready for proposal. This PR fixes it.
Fixes #1337 
ping @aaronlehmann @abronan 

raft test: wait until leader node is ready for proposal in WaitCluster

---

api/ca.pb.go
api/control.pb.go
api/dispatcher.pb.go
api/health.pb.go
api/raft.pb.go
protobuf/plugin/raftproxy/raftproxy.go
protobuf/plugin/raftproxy/test/service.pb.go

Before it was Reset only on transport.ErrConnClosing
This was probably the case of problem which @thaJeztah saw with his setup.

raftproxy: Reset connection grpc.ErrClientConnClosing

---

agent/agent.go
agent/errors.go
agent/node.go

After finding a possible race condition, `Agent`/`Node` `Start` and
`Stop` methods have been greatly simplified. While this race condition
is very unlikely to occur in the wild, there are possible panics if the
caller is not careful about calling `Start` and `Stop` from multiple
goroutines.
Related to #1269.
cc @LK4D4 @aaronlehmann

agent: simplify Start and Stop

---

manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go

A service's endpoint spec can be updated by the user such as changing
the resolution mode from vip to dnsrr or vice-versa or update exposed
ports or completely remove them. The allocator needs to do proper
deallocations and allocations (if any) during those updates. This PR
fixes the allocator logic to handle all these scenarios cleanly.

Handle endpoint spec changes properly

---

CONTRIBUTING.md
manager/allocator/networkallocator/networkallocator.go
manager/manager.go

What I did:
1. fix typos 
2. judge if keymanager is nil.
Since in initialization of keymanager, scheduler, dispatcher, and so on, in keymanager.go:
```
// New creates an instance of keymanager with the given config
func New(store *store.MemoryStore, config *Config) *KeyManager {
for _, subsys := range config.Subsystems {
if subsys != SubsystemGossip && subsys != SubsystemIPSec {
return nil
}
}
return &KeyManager{
config:  config,
store:   store,
keyRing: &keyRing{lClock: genSkew()},
}
}
```
There is possibility that returned keymanager is nil. As a result, I think we need to judge if it is a nil in manager.

judge if key manager is nil and fix typos

---

api/ca.pb.go
api/control.pb.go
api/dispatcher.pb.go
api/health.pb.go
api/raft.pb.go
protobuf/plugin/raftproxy/raftproxy.go
protobuf/plugin/raftproxy/test/service.pb.go

Because proxy is both client and server it can receive errors wrapped as
rpc errors or plain errors.
I hope this time I covered them all. It covers:
* ClientConn errors and their rpc wrapped versions
* transport.ConnectionError ("connection error" string check)
* rpc wrapped transport.ConnectionError (codes.Internal check)
Lol, I'm sorry that I didn't spend enough time for research before. Now I've read the grpc code and verified most common case(client side rpc wrapped error) with integration tests.

raftproxy: handle all errors

---

manager/state/raft/storage.go
manager/state/raft/storage_test.go

We currently garbage collect snapshot files (keeping only
KeepOldSnapshot outdated snapshots, which defaults to 0). However, we
don't garbage collect the WAL files that the snapshots replace.
Delete any WALs which are so old that they only contain information that
predates the oldest of the snapshots we have retained. This means that
by default, we will remove old WALs once they are supplanted by a
snapshot. However, if KeepOldSnapshots is set above 0, we will keep
whichever WALs are necessary to catch up from the oldest of the retained
snapshots. This makes sure that the old snapshots we retain are actually
useful, and avoids adding an independent knob for WAL retention that
might end up with an inconsistent setting.
Also, fix serious brokenness in the the deletion of old snapshots (it …

raft: Garbage collect WAL files

---

manager/controlapi/service.go

This fix update the documentation/comment for checkPortConflicts so
that it is clear conflicts check will skip against the service that
is being udpated.
This fix is related to the dicsussion in 1349:
https://github.com/docker/swarmkit/pull/1349#discussion_r74348186
cc @stevvooe 

Update documentation/comment for checkPortConflicts

---

Godeps/Godeps.json
agent/exec/container/adapter.go
vendor/golang.org/x/time/LICENSE
vendor/golang.org/x/time/PATENTS
vendor/golang.org/x/time/rate/rate.go

Closes #935. Limits how frequently log messages are spammed during image
pulls to avoid clutter in the log.
If someone thinks a longer (or shorter) ticker is ideal, just say something and I'll push up a change with the new value. This only spams like 20 log messages for a pull of `fedora`.
@stevvooe PTAL. Not ideal change but very simple and gets the job done.

Adds a rate limiter to logspam during image pull

---

manager/state/raft/membership/cluster.go
manager/state/raft/raft.go

ReplaceMemberConnection takes a new GRPC connection for a specific
member as an argument. It sets that member's connection to this new one,
and closes the existing GRPC connection.
The problem is that there may be a concurrent invocation of sendToMember
that's trying to send over the old connection. In this case, it will
also call ReplaceMemberConnection, which now closes the new connection
that it put in place, instead of the one where the error was actually
seen. If calls to sendToMember are likely to overlap, then this produces
a cascade of failures that are hard to recover from. Each invocation
closes the connection that another is using.
Fix this by having ReplaceMemberConnection only replace the connection
if the old connection is the one in the Member record. If it's not,
close the …

raft: Avoid closing the wrong connection on an error

---

manager/state/raft/storage_test.go

Generally, restarting a follower node will not cause a leader election.
But our test advances the fake clock as part of its polling, and on a
slow machine this can make enough time pass from raft's point of view to
trigger an election.
Don't assume that node 1 will still be the leader after the restart.
cc @abronan @tonistiigi

raft: Make TestRaftSnapshotRestart more robust

---

manager/manager.go

This is the first step of a brainless refactoring of the `manager.Run` function.
My work started when I read this comment:
```
// TODO(aluzzardi): /!\ This function is *way* too complex. /!\
// It needs to be split into smaller manageable functions.
func (m *Manager) Run(parent context.Context) error {
```
The Run function still contains a lot of domain logic and it is still too complex,
but a little bit less now.

manager.Run refactoring

---

manager/controlapi/task.go
manager/orchestrator/replicated.go
manager/state/store/memory_test.go
manager/state/store/tasks.go

This fix is related to
https://github.com/docker/docker/pull/24850
The task name is defined as (`servicename.slot`) yet the index for task name in memdb was using service name only.
This fix assigns Task name to:
`<e.ServiceAnnotations.Name>.<Slot>.<TaskID>`
when Task is created (`newTask()`)
Below is the item list to be done based on the discussion in this thread.

Use `servicename.slot` for Task name index.

---

ca/certificates.go

Changing root key to P-256

---

agent/exec/container/adapter.go
agent/exec/container/controller.go
manager/manager.go

I found that in the struct controller in agent/exec/container, client is no need, because it will be stored in adapter field.
What I did:
1. remove field client in struct controller in agent/exec/container;
2. remove parameter in createVolumes;
3. fix some typos.

remove field client in struct container controller

---

cmd/swarmctl/node/cmd.go
cmd/swarmctl/node/common.go
cmd/swarmctl/node/inspect.go
cmd/swarmctl/node/update.go
cmd/swarmctl/service/flagparser/flags.go

This change supports add and remove node labels. 
```
dchen@vm2:~/go/src/github.com/docker/swarmkit/bin$ ./swarmctl  node label --help
Update labels for a node
Usage:
./swarmctl node label <node ID> [flags]
Flags:
--add value   add node labels (key1=value1,key2=value2) (default [])
--rm value    remove node labels (key1,key2) (default [])
Global Flags:
-n, --no-resolve      Do not try to map IDs to Names when displaying them
-s, --socket string   Socket to connect to the Swarm manager (default "./swarmkitstate/swarmd.sock")
dchen@vm2:~/go/src/github.com/docker/swarmkit/bin$ ./swarmctl  node inspect vm2
ID                        : a28i8j8zat8b5jlc86o4pk1bw
Hostname                  : vm2
Node Labels               :  nextmaintenance=07-14-2016  security=medium
Status:
State …
```

Support node labels

---

ca/config_test.go

The 2 second timeouts were apparently insufficient on a slow ARM
machine.
This shouldn't cause any impact on normal test runtime - it will just
allow more time for the operations to complete.

ca: Boost test timeouts to 10 seconds

---

manager/state/raft/raft.go

Without mutex lock it's possible that we'll hit State() call during
Stop() and it will hang forever.

raft: fix race in LeaderAddr call

---

manager/dispatcher/dispatcher.go
manager/dispatcher/dispatcher_test.go
manager/state/raft/membership/cluster.go
manager/state/raft/raft.go

Now they update almost immediately on membership list change. This
change is free and I think makes dispatcher code more consistent.

dispatcher: make peers updates better

---

README.md

Removed the line about acceptance policies, which is out of date, in
favor of a line explaining join tokens.

README.md now reflect up-to-date join workflow

---

manager/orchestrator/drain_test.go
manager/orchestrator/global.go
manager/orchestrator/replicated.go
manager/orchestrator/replicated_test.go
manager/orchestrator/services.go
manager/orchestrator/slot.go
manager/orchestrator/updater.go
manager/orchestrator/updater_test.go

This commit prepares for an upcoming change that will allow a
configurable rollout strategy (either shut down the old task before
starting the new one, or start the new one before shutting down the old
one). The issue that was blocking having a rollout strategy with an
overlap between the lifetime of the new and old tasks was that
service-level reconciliation couldn't properly handle situations where
there was more than one active task per slot or node. This change
attempts to solve this by moving to *instance-level* reconciliation.
Before, the orchestrator counted tasks. With this change, it counts
instances (slots or nodes) that are satisfied with at least one task
that has a desired state > `NEW` and <= `RUNNING`.
When service-level reconciliation calls the updater, it passes …

orchestrator: Reconcile instances, not tasks

---

ca/testutils/cautils.go
manager/allocator/allocator_test.go
manager/controlapi/server_test.go
manager/dispatcher/dispatcher.go
manager/keymanager/keymanager_test.go
manager/orchestrator/drain_test.go
manager/orchestrator/global_test.go
manager/orchestrator/replicated_test.go
manager/orchestrator/restart_test.go
manager/orchestrator/task_reaper_test.go
manager/orchestrator/updater_test.go
manager/scheduler/scheduler_test.go
manager/state/raft/membership/cluster.go
manager/state/raft/raft.go
manager/state/store/memory.go
manager/state/watch/watch.go
manager/state/watch/watch_test.go

This was introduced by the change from using a simple channel to a
broadcaster for leadership events.
This was noticed in the stack trace from https://github.com/docker/docker/pull/25833. I don't think this fixes the hang discussed there, though.
cc @tonistiigi @LK4D4

Fix goroutine leak when manager shuts down

---

manager/dispatcher/dispatcher_test.go

This test calls Recv twice, but there doesn't seem to be a good reason.
The second call blocks for awhile until the node heartbeat expires
(because this test isn't sending heartbeats).
Presumably in the past the list of managers was only sent in the second
message, but now it's sent in the first one. So only call Recv once.
Fixes #1406
cc @LK4D4

dispatcher: Fix long-running TestSession unit test

---

Godeps/Godeps.json
vendor/github.com/docker/go-events/LICENSE
vendor/github.com/docker/go-events/README.md
vendor/github.com/docker/go-events/broadcast.go
vendor/github.com/docker/go-events/channel.go
vendor/github.com/docker/go-events/filter.go
vendor/github.com/docker/go-events/queue.go
vendor/github.com/docker/go-events/retry.go

This fixes a race when closing the broadcaster that can cause a hang. In
the old version, the Write and configure functions can receive from the
"closed" channel, which causes "run" to try to write to a nil channel.
cc @LK4D4 @stevvooe

Update go-events to fix race

---

ca/testutils/cautils.go

This field was never filled in, so tc.Server.Close() did nothing. We
would leak the GRPC server in unit tests.
@LK4D4 @diogomonica

ca: Fill in Server field in TestCA struct

---

manager/allocator/network.go

In the log message, I found that it is listing nodes while displaying services. I think it may be an error, so I tried to fix this.
Thanks
Signed-off-by: gexinlu <gexinlu.services@gmail.com>

correct msg display in allocator

---

manager/manager.go

Use s instead of m.RaftNode.MemoryStore() in Manager.becomeLeader()

---

Godeps/Godeps.json
vendor/github.com/coreos/etcd/pkg/fileutil/fileutil.go
vendor/github.com/coreos/etcd/raft/log.go
vendor/github.com/coreos/etcd/raft/node.go
vendor/github.com/coreos/etcd/raft/raft.go
vendor/github.com/coreos/etcd/raft/storage.go
vendor/github.com/coreos/etcd/raft/util.go
vendor/github.com/coreos/etcd/wal/wal.go
vendor/github.com/coreos/etcd/wal/wal_unix.go
vendor/github.com/coreos/etcd/wal/wal_windows.go

This brings in a fix contributed upstream that holds the WAL file lock
during rename on non-Windows platforms. It should address integration
test failures that were caused by a second process holding the lock (due
to inheriting the fd) between fork and exec.
cc @tonistiigi

Revendor etcd to fix locking flakiness

---

agent/agent_test.go
agent/config.go
agent/node.go
agent/session.go
ca/certificates.go
ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/testutils/cautils.go
manager/dispatcher/dispatcher.go
manager/testcluster/manager_cluster_test.go
remotes/remotes.go
remotes/remotes_test.go

Also, renamed picker package to remotes. There is still one picker for
controlapi, I'm going to rewrite it.
I sorta went mad with renaming and it was too late to stop, so commit is mess :(

all: remove picker usage

---

Godeps/Godeps.json
vendor/github.com/docker/go-events/broadcast.go
vendor/github.com/docker/go-events/channel.go
vendor/github.com/docker/go-events/retry.go

This should hopefully fix race detector errors in CI, now that go-events
does not directly dump objects with synchronization primitives to the
log.
Fixes #1441

Vendor go-events

---

manager/state/raft/membership/cluster.go
manager/state/raft/raft.go
manager/state/raft/raft_test.go
manager/state/raft/testutils/testutils.go

I found that the tests were leaking a lot of goroutines for various
reasons. This was a mix of problems in the test and problems in the raft
code.
Actual problems:
- `Cluster.Clear()` did not close active connections, so it would leak
these connections.
- Resources were not being released when `JoinAndStart` fails, or when the
node shuts down because it has left the cluster.
- Errors from `ReplaceMemberConnection` were not handled. This could
caused connections to be leaked in some cases.
Test problems:
- `TestRaftJoinWithIncorrectAddress` did not close the listener for the
node it attempts to join.
- `WrappedListener` could leak a goroutine if it receives an incoming
connection and there are no more calls to Accept to hand the
connection off to. Increase the channel buffering to prevent …

raft: Fix resource leaks in code and tests

---

remotes/remotes_test.go

Using MaxInt32 instead of MaxInt64 in TestRemotesLargeRanges. Stops an
overflow on 32 bit systems. Closes #1384

Fixes remotes_test.go on 32 bit platforms

---

manager/state/raft/raft.go
manager/state/raft/testutils/testutils.go
manager/state/raft/util.go

It's important to know when the node is not a member of the cluster.
Also, it fixes race in accessing n.Config.ID, which might be accessed only when node is member.

raft: make Leader method return error

---

manager/controlapi/node_test.go
manager/state/raft/membership/cluster.go
manager/state/raft/membership/cluster_test.go
manager/state/raft/raft.go

We need this commit for grpc update because there are no State methods
for *grpc.ClientConn in the grpc release.

raft: use heartbeat for detect nodes reachability

---

manager/controlapi/service.go
manager/controlapi/service_test.go

fixed #1494 
Currently, swarmkit checks the whole `*port` to avoid duplication.
This PR makes swarmkit to check the published port of `PortConfig`.

validate duplicate published port in ServiceSpec

---

manager/orchestrator/updater.go

Currently, updater checks `isServiceDirty` to decide whether an existing
update should be restarted. This only checks the task spec and the
endpoint spec, so it will ignore changes to fields like UpdateConfig.
For example, it's not possible to change just the parallelism while an
update is already in progress. Fix this by comparing the whole spec.
cc @dongluochen @pnickolov

updater: Check entire service spec when deciding whether to replace ongoing update

---

manager/dispatcher/dispatcher.go

Otherwise it's possible to call stop before run and leave them unclosed.

dispatcher: set queues in Run

---

ca/certificates_test.go
ca/config_test.go
ca/server_test.go
manager/controlapi/node_test.go
manager/dispatcher/dispatcher_test.go
manager/orchestrator/restart_test.go
manager/orchestrator/updater_test.go

Add t.Parallel() to more tests that involve sleeps or polling.
before:
```
ok      github.com/docker/swarmkit/manager/controlapi   9.348s
ok      github.com/docker/swarmkit/manager/orchestrator 5.852s
ok      github.com/docker/swarmkit/manager/dispatcher   4.538s
ok      github.com/docker/swarmkit/ca   6.807s
```
after:
```
ok      github.com/docker/swarmkit/manager/controlapi   7.566s
ok      github.com/docker/swarmkit/manager/orchestrator 3.960s
ok      github.com/docker/swarmkit/manager/dispatcher   2.680s
ok      github.com/docker/swarmkit/ca   1.637s
```

Run more tests in parallel

---

manager/state/raft/raft.go

It seems like in new grpc timeouts for dial are not applied to calls.
This is last piece for grpc update.

raft: use separate timeout for health api calls

---

agent/exec/controller.go

Requires docker/docker#26432 for the full fix but can be merged at leisure.

agent/exec: don't log context cancelled errors

---

agent/exec/container/adapter.go

During the normal course of operation, http requests may get canceled.
While listening the events API, this error was being reported when
decoding events. This should really just be shutdown with no log message
in this case.
@diogomonica @aaronlehmann PTAL

agent/exec/container: filter out useless error

---

agent/agent_test.go
agent/node.go
ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/server.go
ca/server_test.go
ca/testutils/cautils.go
ca/transport_test.go
manager/dispatcher/dispatcher_test.go
manager/testcluster/manager_cluster_test.go
manager/testcluster/manager_test.go

This changes the name of the constant to reflect its actual value. It
is purely an internal cosmetic change and won't affect interoperability.

ca: rename AgentRole to WorkerRole

---

agent/node.go
ca/certificates.go
ca/config.go

@aaronlehmann: I removed a few messages, added one with the "Next renewal scheduled at: %s" and prepended `[TLS]` in all the relevant logs. 
Let me know if you like this.

Prefixing TLS certificate messages with [TLS]

---

api/ca.pb.go
api/control.pb.go
api/dispatcher.pb.go
api/health.pb.go
api/raft.pb.go
api/resource.pb.go
protobuf/plugin/raftproxy/raftproxy.go
protobuf/plugin/raftproxy/test/service.pb.go
protobuf/plugin/raftproxy/test/service.proto

This is for a unifying track of closed and unavailable connections. New
grpc will return transient errors from calls, so we need to prepare.
On grpc update I will just add transient errors check in addition to "is closing" check. Probably closing connection won't be needed too.

raftproxy: use healthcheck instead of just polling

---

manager/allocator/allocator_test.go
manager/allocator/network.go
manager/allocator/networkallocator/portallocator.go

fixes #1480 
This PR did:
1. in service update request, if there is no endpointSpec in service and there is endpoint in service, it means user no longer wants the allocated endpoint, then swarmkit needs to deallocate this.

fix panic in portallocator and deallocate endpoints when update with none EndpointSpec

---

manager/allocator/allocator_test.go

Addressing some of the potential allocator test flakiness as per @aaronlehmann's comment here:  https://github.com/docker/swarmkit/pull/1470#issuecomment-245048511
> About the allocator tests, I think we should make the sleep depend on expectTimeout. In the case where we do expect a timeout, the timeout should be short, because it's not very useful to wait long amounts of time just in case an unexpected event comes in - a short timeout should catch an incorrect event at least often enough to make the test flaky and alert us to the problem. But in the cases where we don't expect a timeout, the timeout should be on the order of serveral seconds, so the test doesn't fail just because it's run on a relatively slow system, or there's a load spike.

Increase timeouts for TestAllocator if a timeout is not expected

---

manager/orchestrator/restart.go
manager/orchestrator/updater.go

This corrects some problems with #1492. That PR avoided tasks getting
stuck in READY by continuing to start the new task if old one couldn't
be stopped. The problem with this is that the old task may have been
restarted due to a failure, which effectively causes that slot to get
updated to the latest version - so there would be two up-to-date tasks
running in that slot. The Docker 1.12 behavior, which is the correct
behavior, is to avoid creating a new task if the old one can't be
stopped.
Also, fix DelayStart to avoid waiting for oldTaskTimeout if no old task
was given.
Finally, change oldTaskTimeout to use a timer which is stopped when the
function returned, instead of a time.After which can leak a long-running
timer.

updater: Don't create a new task when the old one can't be stopped

---

manager/state/raft/raft.go
manager/state/raft/raft_test.go
manager/state/raft/wait.go

This includes three commits that fix possible deadlocks between `ApplyStoreActions` and `processInternalRaftRequest`:
**raft: Fix race that leads to raft deadlock**
PR #1310 ("Fix infinite election loop") solved a problem with election
loops on startup, by delaying new proposals until the leader has
committed all its existing entries. This ensures that the state machine
doesn't call `ApplyStoreActions` to commit a previous entry from the log
while an new proposal is in process - since they both acquire a write
lock over the memory store, which would deadlock.
Unfortunately, there is still a race condition which can lead to a
similar deadlock. `processInternalRaftRequest` makes sure that proposals
arent't started after the manager loses its status as the leader by
first registering a wait …

raft: Fix possible deadlocks

---

agent/agent.go
agent/session.go

Previously, failed calls on an agent session to UpdateTaskStatus weren't
causing the agent to fall back into the session creation retry loop.
Without the retry loop, the agent ends up pounding the dispatcher with
status updates that will never drain.
This PR closes the session on a fatal error, ensuring that the agent
will fallback into a retry loop.
Consider backporting this change to 1.12.2.
cc @aaronlehmann 
Closes #1533

agent: bounce session after failed status update

---

manager/manager.go

I found that in manager, when initializing to start listener, hard code to be 2 chan err.
I think it is better to be flexible for errServe to follow length of listeners.
Just a little bit change, feel free to close it if I missed something.

make errServe in manager dynamical

---

api/ca.pb.go
api/control.pb.go
api/dispatcher.pb.go
api/health.pb.go
api/raft.pb.go
api/resource.pb.go
protobuf/plugin/raftproxy/raftproxy.go
protobuf/plugin/raftproxy/test/service.pb.go

Looks like on arm some syscall returns different from amd64 code and
grpc returns different error:
connection error: desc = "transport: read tcp 127.0.0.1:51302->127.0.0.1:2477: read: connection reset by peer"
Handle this error as well.
I've tried this on docker arm CI.

raftproxy: handle more errors

---

manager/controlapi/network.go
manager/controlapi/network_test.go

This fix tries to address the issue raised in:
https://github.com/docker/docker/issues/24538
where the error message is unclear when removing pre-defined networks:
```
docker network rm ingress
Error response from daemon: rpc error: code = 7 desc = 4vlxuzpk8bxdsxpyvkxluol5g is a pre-defined network and cannot be removed
```
This fix improve the error message so that if network's name is specified
in the `RemoveNetwork`, then error message will contain the name and the ID
(instead of just an ID).
```
docker network rm ingress
Error response from daemon: rpc error: code = 7 desc = ingress (4vlxuzpk8bxdsxpyvkxluol5g) is a pre-defined network and cannot be removed
```
The unit test has been updated to cover the changes.

Improve error message for removing pre-defined (e.g., `ingress`) network

---

manager/state/raft/storage.go
manager/state/raft/storage_test.go

The currently vendored version of etcd/wal produces files that are
incompatible with the version of this package that 1.12 vendored. When
reading files created by this version, the WAL decoder in 1.12 will
panic.
To avoid causing crashes in downgrade scenarios, copy existing WAL files
to a new path that Docker 1.12 doesn't read from. The old files will be
preserved in case there is a downgrade. The downgraded version would
read the old state and catch up through raft.
Fixes #1475
cc @icecrime @aluzzardi @dongluochen @LK4D4

raft: Migrate WAL files to new directory

---

manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go

Wrap errors with github.com/pkg/errors instead of using fmt.Errorf.
cc @stevvooe

allocator: Use errors.Wrap

---

manager/manager.go

Wrap errors with github.com/pkg/errors instead of using fmt.Errorf.
cc @stevvooe

manager: Use errors.Wrap

---

manager/state/raft/raft.go
manager/state/raft/storage.go

Wrap errors with github.com/pkg/errors instead of using fmt.Errorf.
cc @stevvooe

raft: Use errors.Wrap

---

manager/manager.go

Otherwise, initManagerConnection just exits if SetServingStatus is not called.

node: handle transient NotFound error on health check

---

manager/controlapi/task.go
manager/orchestrator/global.go
manager/orchestrator/replicated.go
manager/orchestrator/restart.go
manager/orchestrator/services.go
manager/orchestrator/updater.go
manager/orchestrator/updater_test.go
manager/state/store/tasks.go

This fix is based on the discussion in:
https://github.com/docker/docker/pull/24850#issuecomment-243518250
Previously Task Name has been defined as `<ServiceAnnotations.Name>.<Slot>.<TaskID>` in both replicated and global mode. That means in global mode, the Task Name is `<ServiceAnnotations.Name>.0.<TaskID>` which does not carry any information in `0`.
In this fix, the Task Name has been changed to `<ServiceAnnotations.Name>.<NodeID>.<TaskID>` in global mode.
This fix is related to:
https://github.com/docker/docker/pull/24850

Change Task Name to `<ServiceAnnotations.Name>.<NodeID>.<TaskID>` in global mode

---

manager/controlapi/service.go
manager/controlapi/service_test.go

Duplicate mount points are not allowed in serviceSpec.
Validation for same was missing in swarmkit.
Ref: https://github.com/docker/docker/issues/25772
Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>

Check for duplicate mount points in ServiceSpec

---

agent/node.go

This reverts commit ab756e027570ffb531220cb2b8dc3c1cfa788ba5.
The original PR was based on a misunderstanding of the code. It treats a
nonexistent state file as a fatal error, but this is meant to be
ignored.
This revert is necessary to make node initialization work again. See https://github.com/docker/swarmkit/pull/1087#issuecomment-249774565
cc @allencloud @LK4D4 @stevvooe @dperny

Revert "rewrite part of NewNode to handle all kinds of err"

---

Makefile

...Since go test already builds packages without tests (see https://github.com/docker/swarmkit/pull/1572, and https://github.com/golang/go/issues/17248.

Don't invoke build target as part of "ci" or "all"

---

manager/orchestrator/drain_test.go
manager/orchestrator/replicated_test.go
manager/orchestrator/services.go
manager/orchestrator/updater_test.go

When scaling down, we don't want to preserve task history for the slots
that are being removed. These historic tasks are distracting to users
and never get garbage collected.
Make the orchestrator delete these tasks instead of simply shutting them
down.
Always do this for slots that have no runnable tasks on service
reconcilation, so this isn't limited to scale-down operations. This
should properly clean up tasks that were left over by earlier versions.
Fixes #1372

replicated orchestrator: Delete tasks on scale down

---

manager/state/raft/raft.go

Leader steps down as follower when quorum is lost. This option enabled
by default in etcd as well.

raft: use CheckQuorum option

---

manager/controlapi/service.go

This check is not needed, as it is already validated by `validateServiceSpec()`.
/cc @aaronlehmann

remove redundant nil check for request.Spec

---

manager/state/raft/membership/cluster.go
manager/state/raft/raft.go
manager/state/raft/raft_test.go

One of the things necessary to unblock full support for swarm mode in Docker for Mac/Windows is support for dynamic IP addresses on managers. Users of Docker for Mac/Windows are much more likely to be running in an environment like a laptop with WiFi. Of course, this will also be useful in other setups.
This PR begins to explore allowing address changes at the raft level. Each manager keeps track of the last source address it saw in RPCs from each other manager. When a send fails, and the most recently seen source address differs from the address we're sending to, and the observed address passes a health check, we switch to that address. Also, if this happens on the leader, the new address will be written to raft. Nodes are protected from election loops during an address change by …

Support manager address changes

---

agent/agent.go
agent/session.go

* Do not close session anywhere apart from session.errs branch, because
direct session.close() won't trigger backoff increase.
* Do not set sessionq until registration is finished, otherwise tasks
won't wait and report error about session which still in process of
registering.
I will port this to 1.12.2 if it's approved.
ping @stevvooe @aaronlehmann @mrjana

agent: handle errors better

---

manager/state/raft/raft.go

In #1221, the code was changed not to call Campaign on restart unless
n.Node.Status().Progress[n.Config.ID] was set. The problem is that this
is never set unless the node is already the leader, so this effectively
disabled the quick leader election on restart for a single-node cluster.
Instead of checking Progress, figure out whether it's safe to call
Campaign by setting a flag when we apply the config change that adds the
local node to the raft state machine. This flag is set in registerNode,
which is technically also called when loading a snapshot, but in this
case the node is restored into the state machine through ConfState, so
setting the flag in both cases is correct.
Also, only enable the calls to Campaign when the node was restarted from
state on disk.
This PR is against the …

[1.12] raft: Fix campaign on restart

---

ca/certificates.go
ca/config.go

Change the renewal time detection to always look the full validity period of an old certificate so that restarts don't start to delay the initial renewal time.
cc @diogomonica @aaronlehmann 

Update certificate renewal to use whole validity period

---

manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

The constraint logic in the HA scheduler has a bug. Constraints get
ignored when assigning more than one task at once to the same node. This
is caused by a bad "continue" that skips the constraint check. Remove
this check, and also add a unit test.

scheduler: Fix constraint evaluation when assigning more than one task

---

manager/controlapi/common.go

The regex string in the error message was out of sync with the actual
regex being used to validate a service name.
The actual regex (`isValidName`) being used is here: https://github.com/tombee/swarmkit/blob/fa4be1382a605f7ff645e734b7754f95803ed1ff/manager/controlapi/common.go#L13
Signed-off-by: Tom Barlow <tomwbarlow@gmail.com>

Update service name validation regex error message

---

manager/manager.go
manager/state/raft/raft.go
manager/state/raft/raft_test.go
manager/state/raft/storage.go
manager/state/raft/testutils/testutils.go

The Node structure has too many fields. One small step in the right
direction is removing fields that are directly copied from the
NewNodeOptions struct, which is also referenced in Node. There is less
potential for error if there is a single source of truth for these
options rather than storing the values in two places.
Rename NewNodeOpts to NodeOpts, since it's really used for more than
NewNode.

raft: Deduplicate node-level options

---

manager/controlapi/service.go
manager/state/store/networks.go

Related to https://github.com/docker/docker/issues/27147
```
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
9303692245a0        bridge              bridge              local
c4f927d72329        docker_gwbridge     bridge              local
1de6d5796506        host                host                local
640eymcv5g3c        ingress             overlay             swarm
7af0bf63afad        none                null                local
$ 
$ docker network inspect ingress | grep Id
"Id": "640eymcv5g3cabu4jdffrandw",
$ 
$ docker service create --network 640eymcv5g3cabu4jdffrandw busybox top
Error response from daemon: rpc error: code = 3 desc = Service cannot be explicitly attached to "ingress" network which is a swarm internal network
$ 
$ docker …
```

Do not allow service creation on ingress network

---

manager/state/raft/raft.go

This brings the code on master in sync with the 1.12 changes in #1588. The code on master does not have the same problem (since a newer etcd/raft library lets it skip the problematic check), but the version being adopted by 1.12 should be a bit more robust.
This is a separate PR against master instead of cherry-picking from master to bump_v1.12.2 because the code has diverged and needs to be a bit different on master anyway (different etcd/raft version).
cc @LK4D4 @mrjana

raft: Forward-port improvements to campaign on restart

---

manager/controlapi/node_test.go
manager/state/raft/raft.go
manager/state/raft/raft_test.go

Such embedding hurts readability and also exposes many public methods
from underlying type.

raft: unembed etcd/raft.Node

---

manager/state/raft/membership/cluster.go

This allows us to use connection for some time. For example if we're
demoting leader, then we executing request to leader to do it and it's
not wise to close its connection.
That's sorta proposal. This case is very rare, but possible. Some of my integration tests might be flaky because of that.

raft: defer closing conns on applyRemoveNode

---

integration/cluster.go
integration/integration_test.go

It seems like CI sometimes exceeds timeout because of slow disks. And it's not stress-test anyway.

integration: reduce number of nodes in TestServiceCreate

---

api/types.pb.go
api/types.proto
manager/controlapi/service.go
manager/state/store/networks.go

PR #1600 added a FindNetwork function to the store package to resolve a
NetworkAttachment's target by ID, name, or name prefix. I think this is
based on a misleading comment in the NetworkAttachment definition saying
that the target can be a name or an ID. In fact, it's always an ID, and
existing code passes it directly to GetNetwork.
Clarify the comment and remove FindNetwork.
cc @aboch @mrjana @aluzzardi

Clarify that NetworkAttachment target is an ID

---

manager/allocator/networkallocator/drivers_ipam.go
manager/allocator/networkallocator/drivers_linux.go
manager/allocator/networkallocator/drivers_unsupported.go
manager/allocator/networkallocator/networkallocator.go
manager/controlapi/network.go
manager/controlapi/network_test.go
vendor.conf
vendor/github.com/docker/libnetwork/drivers/remote/api/api.go
vendor/github.com/docker/libnetwork/drivers/remote/driver.go
vendor/github.com/docker/libnetwork/ipams/remote/api/api.go
vendor/github.com/docker/libnetwork/ipams/remote/remote.go

In Docker 1.12, swarmkit is hard-coded only to accept `overlay` network driver and builtin ipam driver. That practically eliminates all other global network and IPAM plugins.
This PR enables the network and ipam plugins be used with swarmkit as well.

Honor Network and IPAM plugin

---

manager/scheduler/filter.go
manager/scheduler/pipeline.go
manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

When a task can't be scheduled on any node, the scheduler fills in the
Status.Message field with a message of the form:
no suitable node (insufficient resources on 7 nodes; scheduling constraints not satisfied on 4 nodes; 1 node not ready)
Fixes #324

scheduler: Provide a reason for unschedulable tasks

---

manager/controlapi/common.go
manager/controlapi/service_test.go

There is a regexp to validate that service/network names follow the DNS label grammar, but there is no check on the length of these names. For them to be valid labels, they can be at most 63 characters.
Add such a check and test coverage.
This is a narrow fix that just adds the check. As @stevvooe suggested, there's an opportunity to refactor naming into a separate package. Let's do that as a separate PR after this.
Fixes #1576

controlapi: Validate that names aren't too long for DNS label

---

manager/allocator/networkallocator/drivers_darwin.go
manager/allocator/networkallocator/drivers_unsupported.go

Enable the drivers on Darwin as well as Linux.
cc @mavenugo @mrjana

allocator: Fix unit tests on Mac

---

manager/controlapi/service.go
manager/controlapi/service_test.go

Fix controlapi to allow duplicate published ports as long as different
protocols are in use. This is a 1.12.2 regression.

controlapi: Allow duplicate published ports when they use different protocols

---

api/control.pb.go
api/objects.pb.go
api/raft.pb.go
api/snapshot.pb.go
api/specs.pb.go
api/types.pb.go
manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
protobuf/plugin/deepcopy/deepcopy.go
protobuf/plugin/deepcopy/test/deepcopy.pb.go

In cases where append(a, b...) can be used, don't replicate the same
functionality with a for loop.
Modify the deepcopy plugin to generate code that uses the former syntax.
Fix an instance in allocator. Also change a slice == nil check to
len(slice) == 0, which caused some fun to debug problems.
@stevvooe @mrjana

all: Avoid unnecessary "append" loops

---

agent/agent_test.go
manager/orchestrator/services.go

Also use "require" instead of "assert" when checking an error from a
function that allocates a new object in agent_test.go.

Fix unchecked error values

---

Makefile
ca/server_test.go
manager/dispatcher/dispatcher_test.go
manager/orchestrator/restart_test.go

This is a check like lint/vet that fails CI if there are dead stores in the code.

Add ineffective assignment checker

---

Makefile

The integration tests take about a minute to run. It's nice to run the
unit tests first so a developer can quickly see if those tests are
passing.
cc @LK4D4

Run integration tests after unit tests

---

integration/cluster.go

It can be difficult to tell which node a log message comes from. This
adds a logger to the context that has a log field identifying which node
produced the log message.
Right now this is only somewhat useful because a lot of log messages
come from grpc and etc/raft, but in the future as more is converted to
use the context for logging it will be increasingly useful.
cc @LK4D4

integration: Inject logger that differentiates nodes

---

manager/controlapi/node_test.go
manager/manager.go
manager/state/raft/membership/cluster_test.go
manager/state/raft/raft.go
manager/state/raft/raft_test.go
manager/state/raft/storage.go
manager/state/raft/storage_test.go
manager/state/raft/testutils/testutils.go

* Remove Ctx field from struct, use `stopped` channed as stop signal
instead.
* Add WithContext method which returns child context which also cancelled
on close of `stopped` channel.
* All top level functions use WithContext (Run, RemoveNode, grpc
handlers).
This is sorta intersects with #1580 

raft: rethink context usage

---

manager/state/raft/membership/cluster.go
manager/state/raft/raft.go

There is not much overhead (if any) in creating client each time, but
having embedded RaftClient hurts readability very much IMO.

raft/membership: remove RaftClient field

---

ca/certificates.go
ca/external.go
ca/server.go
ca/server_test.go
ca/testutils/cautils.go
ca/testutils/externalutils.go

When there is no signer, or when using an external CA that's
unreachable or not responding properly, add the node to a list of
pending certificate requests. Every 10 seconds, run through this list
and try to issue the certificates again.
Fixes #1596
cc @alexmavr @diogomonica

ca: Retry certificate issuance on non-fatal errors

---

manager/controlapi/service.go
manager/controlapi/service_test.go

This fixes a 1.12.2 regression.
See https://github.com/docker/docker/issues/27469
cc @thaJeztah @allencloud

controlapi: Allow multiple randomly assigned published ports on service

---

manager/allocator/allocator.go
manager/allocator/network.go

`a.netCtx` is initialized too late, so if allocations happen as part of
`doNetworkInit`, a nil pointer dereference will cause a panic.
Initialize `a.netCtx` earlier and use `a.netCtx` directly in member
functions instead of passing the network context separately, so there is
no confusion about which to use.
Also change allocator.go to have separate entries in the waitgroup for
initialization and actually running the allocator, and defer `Done` for
both. This should prevent a panic like this from leading to a deadlock,
since the deferred `Done` will be reached.
See docker/docker#25432
cc @mrjana @LK4D4 @tonistiigi

allocator: Fix panic when allocations happen at init time

---

manager/allocator/allocator_test.go

Add a specific test case to test allocation of a task which is already
in store and has no network attachments created before allocator is run.

Add an allocator test for preinit task object

---

cmd/swarmctl/secret/create.go

#1589 This would read the secret from the file instead of STDIN. 
This PR also servers as a platform for continuing the discussion from https://github.com/docker/swarmkit/pull/1567#discussion_r80588914 and doing a design discussion of what `docker secret create <secret-name>` should look like.
A summary of that discussion and some IRL discussions:
@aluzzardi suggests the following UI:
- Pass as an argument:  `docker secret create foo bar`
- Pass to stdin: `echo bar | docker secret create foo -`
- Pass as a file:  `echo bar > value.txt && docker secret create foo -f value.txt` 
The reason the current design does not to accept the secret itself as an argument is that we do not want to encourage users to type the secret into a command.  If we did accept a secret as a direct argument, then it …

Add a `-f` option to let a user pass a filename for creating secrets

---

manager/manager.go
manager/orchestrator/constraint_enforcer.go
manager/orchestrator/constraint_enforcer_test.go
manager/orchestrator/global.go
manager/scheduler/scheduler.go

If a node is updated in a way that makes its tasks no longer satisfy constraints or resource requirements, shut down the affected tasks.
This is not done in the scheduler because the scheduler should not be shutting down tasks. DesiredState is a field owned by the orchestrator, and should not be written by other components.
Instead, introduce a ConstraintEnforcer inside the orchestrator package. It waits for node updates, and checks that the tasks on the node still satisfy constraints and resource requirements.
Change the scheduler to atomically check that nodes where tasks are assigned haven't changed during the time the scheduling decision was made, since this could cause a new task to be assigned to node that was just updated in a way that makes it incompatible with the task.
Fixes …

Remove tasks that no longer satisfy constraints

---

manager/controlapi/secret.go
manager/controlapi/secret_test.go

Allowing GetSecret to return the secret data. Intentionally leaving ListSecrets with redaction enabled.
/cc @cyli @aaronlehmann 

Allowing GetSecret to return the secret data

---

manager/scheduler/nodeinfo.go
manager/scheduler/scheduler.go
manager/scheduler/scheduler_test.go

There's a bad failure mode when a node ends up rejecting or failing all
tasks. The scheduler will continue to prefer this node, because it's the
least loaded. It ends up in a loop where it's assigning a task to this
node forever, and it always gets rejected.
To avoid this, have the scheduler track recent failures for each service
on each node. If a service has failed 5 times in the last 5 minutes, we
take that into account in the function that sorts nodes, and prefer
nodes that have fewer recent failures.
This is a rough heuristic, but keeps the scheduler simple, and should
fix the vast majority of cases where things grind to a halt due to a
faulty node.

scheduler: Monitor nodes for excessive failures

---

manager/orchestrator/global/global_test.go
manager/orchestrator/replicated/restart_test.go
manager/orchestrator/replicated/task_reaper_test.go
manager/orchestrator/testutils/testutils.go
manager/state/watch.go

The global orchestrator tests were pausing 200 ms to wait for some events to pass. It's more reliable to just consume these specific events. This changes them to do that, and also replace testutils.Expect* with a single Expect function. This is nicer than having a separate function for every event type. The Checks in the event structure can be used to match specific event properties.
In the future, I may also convert testutils.Watch* to a similar Watch function.

orchestrator: Make global tests more robust; use generic Expect function

---

manager/controlapi/service.go

Updating a services' name has has various side-effects (e.g., existing tasks are not renamed), and was never intended to be supported.
This produces an error if the service is renamed.
relates to https://github.com/docker/docker/pull/26988

Disallow renaming services

---

manager/state/raft/raft.go

This should make calling RemoveNode from controlapi safer because it
checks more stuff. Also, it allows to move WithContext up to two public
functions - Leave and RemoveNode and it looks nicer.

raft: create internal removeNode function

---

manager/allocator/network.go

On startup, the allocator can do many separate raft writes to allocate services and nodes. Solve this by batching those writes.
Split allocation functions into one function that does the allocation, and another function that commits it to the store. Always do the allocations first and then commit them in a single batch.
This also converts task allocation not to hold the raft store lock while doing allocations, which will be important as plugin support is added.
Fixes #1286
This turned out to be a more involved change than I expected, so I'm not as confident in it as I'd like to be :(. I'd appreciate some careful review and testing.
cc @mrjana

allocator: Batch service and node allocations

---

agent/agent.go
agent/agent_test.go
agent/exec/container/adapter.go
agent/exec/container/controller.go
agent/exec/container/controller_integration_test.go
agent/exec/container/controller_test.go
agent/exec/container/executor.go
agent/exec/controller.go
agent/exec/controller_test.go
agent/exec/executor.go
agent/secrets.go
agent/worker.go
agent/worker_test.go
integration/exec.go

This just cherry-picks the commit from https://github.com/diogomonica/swarmkit/pull/1 - I just renamed "name" to "id" since we now do lookups by ID.
Enables lookup of the local secret assignment from the agent, which is needed from core side.

secrets: enable secret lookup from agent

---

manager/scheduler/nodeinfo.go
manager/scheduler/nodeset.go

There is a possible nil pointer dereference in taskFailed. The map gets
initialized in the constructor, but not all NodeInfo objects are created
with the constructor.
Change addOrUpdateNode to make sure all maps are allocated. Remove
various checks that tried to do this lazily.

scheduler: Always initialize maps when nodes are inserted in the nodeset

---

agent/exec/container/container.go
api/naming/naming.go
api/naming/naming_test.go
manager/controlapi/task.go
manager/orchestrator/task.go
manager/state/store/tasks.go

This change consolidates task naming into a single package. The names of
tasks was at risk of diverging over time, since it is a calculated
property. We can further extend this package to do more naming and
validation work.

naming: consolidate task naming into single package

---

manager/state/store/memory.go

It's more correct to check if len(slice) == 0. In the current code, this
doesn't make a difference, but the nil check was fragile.

Avoid checking if slice is nil

---

agent/agent_test.go
agent/exec/container/adapter.go
agent/exec/container/controller.go
agent/exec/container/executor.go
agent/exec/controller.go
agent/exec/controller_test.go
agent/exec/executor.go
agent/secrets/secrets.go
agent/worker.go
agent/worker_test.go
integration/exec.go

Previous changes tightly coupled the secrets storage with the agent
package. The evidence of this lies in the addition of an argument to
`Executor.Controller`, which typically means something isn't quite
right. Controllers should be resolvable with only the task information.
We now defer the entireity of secret storage to the executor. The
existing map-based implementation is now in a package `secrets` which
can used by executors.
No interface changes are required by upstreams. Secrets support is
declared by executor implementation via the `SecretsProvider` interface.

secrets: decouple secrets from agent package

---

manager/manager.go

The advertise address was being forced to the same value as the listen
address, by some code added to `(*Manager).New` for integration testing.
This code was overwriting `tcpAddr` (which is supposed to contain the
advertise address) with the bound address of the listening socket. The
idea was to support passing a :0 address into the manager, through node
(so a listener can't be bound beforehand). Fix this to only override
`tcpAddr` if a 0 port was actually given.
cc @LK4D4 @dperny @aluzzardi

manager: Fix advertise address regression

---

protobuf/plugin/raftproxy/test/raftproxy_test.go

#This test fails randomly. As much as I hate disabling a test instead of
fixing it, this has been a problem for months and we currently just ignore
the failures.
@LK4D4

Disable TestClientServerStreamRedirect

---

manager/manager.go
manager/manager_test.go
node/node.go

Previously, we had a ProtoAddr map and a ProtoListener map. These maps
were awkward because keying on the protocol doesn't really make sense.
Replace these with RemoteAPI and ControlAPI fields. RemoteAPI is a
struct that contains a listening address and an optional advertise
address. ControlAPI is just an address string, because the concept of
advertise address does not apply to the control API.
Remove the capability to pass in listeners. This was only used by a
single unit test. The concept can't extend to node, because node may
start the manager multiple times, and a listener can't be reused.
Change the unit test to pass in an address with a 0 port and let the
manager bind.
cc @dperny @LK4D4 @aluzzardi

manager: Clean up address configuration

---

cmd/swarmctl/service/flagparser/secret.go
manager/controlapi/secret.go
manager/controlapi/service.go
manager/dispatcher/dispatcher.go
manager/dispatcher/dispatcher_test.go

- Fixes a secret assignment bug
- Fixes swarmctl to add SecretID to the SecretReferences
- Adds a validation that all secret references have a name and an ID
- Adds simple logging to the secrets control api

Fixed bug in secrets assignment, added logging

---

manager/state/raft/raft.go

raftpb.ConfChange also include ConfChangeUpdateNode, log info should add this type.

raftpb.ConfChange also include ConfChangeUpdateNode

---

manager/orchestrator/global/global.go

add detail information when removeTasksFromNode batch failed, so as to differ from other exception.

add detail information when removeTasksFromNode batch failed

---

vendor.conf

It's subset of crypto and breaks vndr :(
The interface of vndr is not cool in that case, will try to fix it.

vndr: remove nacl from vendor.conf

---

ca/external.go
cmd/external-ca-example/main.go

Use original pakcage name 'logrus' in the every file. 
Realated PR in other project are like.
https://github.com/docker/docker/pull/24745
https://github.com/docker/libnetwork/pull/1527
Signed-off-by: Daehyeok Mun <daehyeok@gmail.com>

Refactoring for logrus import Instead of 'log' use original package name logrus

---

manager/allocator/networkallocator/portallocator.go
manager/allocator/networkallocator/portallocator_test.go

Currently the port allocator depends on the order of the ports in the
Spec and the Endpoint to be the same to determine if it is allocated or
while reconciling ports. This results in unnecessary false negatives
while testing for allocated and go through unnecessary
allocations. Fixed this by treating the list of ports as a set and check
if the same set of ports are available in the Endpoint as in Spec.

Make port allocator not depend on order of ports

---

agent/exec/container/container.go
agent/exec/container/controller.go
template/context.go
template/context_test.go
template/expand.go
template/template.go

To better support common use cases that require injected service and
task information, we now treat ContainerSpec fields as templates. A
common, simplified context is defined that contains commonly needed
values, with access to names, identifiers and labels.
This initial PR focuses on supporting mounts and environment variables.
By supporting these, users will be able to locate mounts based on task
context or service name, unlocking many use cases that were previously
challenging or impossible. Environment variables open up further
possibilities.
Signed-off-by: Stephen J Day stephen.day@docker.com
cc @aluzzardi @mgoelzer @ehazlett @NathanMcCauley @diogomonica

template: support templating of task runtime parameters

---

integration/integration_test.go

This fix tries to fix logrus formatting by removing `f` from
`logrus.[Error|Warn|Debug|Fatal|Panic|Info]f` when formatting string
is not present.
Signed-off-by: Daehyeok Mun <daehyeok@gmail.com>

Fix logrus formatting

---

xnet/xnet_windows.go

This is an amendment to the named pipe changed merged last. It includes a more restrictive ACL for the named pipe we create. This change was recommended in the review of docker/docker#27838 by @jhowardmsft. 
(@jhowardmsft if you would take a look and make sure this looks right to you, that would be really, really helpful. I tried reading up by my understanding of Windows ACLs is still VERY basic)

fix ACL for named pipe

---

manager/controlapi/network.go
manager/orchestrator/global/global.go
manager/orchestrator/replicated/services.go
manager/orchestrator/update/updater.go
manager/state/store/by.go
manager/state/store/memory.go
manager/state/store/services.go
manager/state/store/tasks.go
vendor.conf
vendor/github.com/hashicorp/go-memdb/index.go
vendor/github.com/hashicorp/go-memdb/schema.go
vendor/github.com/hashicorp/go-memdb/txn.go

Previously, it was not possible to have indices which could have more
than one value per object. This vendors a fork of go-memdb that adds
this feature, from a PR that has been pending for more than eight
months. It then adds indices over tasks and services for the network and
secret IDs referenced by the tasks and services. Network deletion is
updated to use the new index instead of listing all services.
cc @aluzzardi @mrjana @diogomonica @mavenugo

Add indices over tasks and services by referenced network and secret IDs

---

manager/controlapi/secret.go
manager/controlapi/secret_test.go
manager/controlapi/service_test.go

Added best-effort verification of secrets in use before Removal, unless Force is specified.
/cc @cyli @aaronlehmann 
```
➜ swarmctl secret rm diogo1.txt
Error: secret 'diogo1.txt' is in use by the following service: elnerd6rd37mf1su17xp120x0, r07u2ung4h3mt41myom3exews, xk6cohgr2yc54q70rwgh5rmwx
```

Graceful secret removal

---

manager/state/raft/raft_test.go
manager/state/raft/storage/storage.go
manager/state/raft/storage/storage_test.go
manager/state/raft/storage/walwrap.go
manager/state/raft/storage/walwrap_test.go

This fixes bugs introduced in #1598 in windows:
1. the wal directory cannot already exist, or `wal.Create` will not be able to rename
1. when migrating WALs from an older directory, close the temporary writer first.  Otherwise, windows will not be able to rename the temporary directory because the temporary writer has a lock.

[encryption] Fix WAL directory manipulation in windows

---

agent/exec/container/container.go
agent/exec/container/container_test.go
api/specs.pb.go
api/specs.proto

This fix is a followup for `Hosts` field in `ContainerSpec`, from the comment in:
https://github.com/docker/swarmkit/pull/1729#pullrequestreview-8044827
and from docker PR:
https://github.com/docker/docker/pull/28031
In the docker PR, it has been specified that `Hosts` in `ContainerSpec` should only follow the standard format:
```
IP_address canonical_hostname [aliases...]
```
The docker PR 28031 already takes the above into consideration so no implementation updates needed.
This fix corrects the comment in the specification of `Hosts`.

Update the comment for `Hosts` field in `ContainerSpec`

---

manager/controlapi/secret.go
manager/controlapi/secret_test.go

Allow secret updates that do not modify the current secret data.
/cc @aluzzardi 

Allow updates that don't change the secret value

---

agent/reporter_test.go

According to Go documentation functions with FailNow should be
called in same goroutine with test.

agent: do not call Fatalf in goroutine

---

manager/logbroker/broker.go
manager/logbroker/broker_test.go
manager/logbroker/subscription.go
manager/manager.go

Put together something quick, this is not polished just wanted to get some feedback.
Looking at roughly what the changes would be, and given the logs feature is experimental, do you think this should get in now or for 1.14?
/cc @aaronlehmann @stevvooe @vieux

broker: Send down subscriptions only to relevant nodes.

---

manager/orchestrator/global/global.go

The updater is wrongly called from inside a store transaction, which can
lead to a deadlock if an update is already running. The new update tries
to cancel the running one, but that existing update may be stuck trying
to start a store transaction and therefore the new update waits forever
for it to stop. To fix this, keep track of tasks that need to be
updated, and call the updater outside the transaction.
See https://github.com/docker/docker/issues/28039
cc @dongluochen @aluzzardi

orchestrator/global: Fix deadlock on updates

---

ca/certificates.go
ca/certificates_test.go
ca/config.go
ca/config_test.go
node/node.go

This is an alternative proposal to #1751 
Fixes #1731
- Split `LoadOrCreateSecurityConfig` into `LoadSecurityConfig` and `RootCA.CreateSecurityConfig`. The latter is a method on `RootCA` because the `RootCA` object issues the certificate.
- Create a `CertificateRequestConfig` struct that configures a certificate request. It includes things such as the remote CA addresses and the token needed to authenticate with them. Use this in `CreateSecurityConfig` and some of its downstream methods.
- Only use the `NodeInfo` channel when an actual remote certificate request is taking place. It's not necessary in the case where the certificate is loaded from disk or issued locally, because `n.nodeID` and `n.nodeMembership` will be set right inside `loadSecurityConfig`.
- Remove unused …

Refactor LoadOrCreateSecurityConfig

---

ca/external.go
ca/server.go

If the context is cancelled while trying to communicate with an external
CA, the `Sign` method should return immediately. Without this, it can take
a long time to shut down the manager, because it waits for this method
to finish. If the external CA is not reachable, it can take especially
long.
Fixes #1484

ca: Honor context in (*ExternalCA).Sign

---

agent/session.go

If the manager is too old to support the LogBroker service, the agent
should not bounce the session.
See https://github.com/docker/docker/issues/28496
cc @aluzzardi @stevvooe

agent: Handle managers that don't implement LogBroker

---

agent/agent.go
agent/exec/controller.go
agent/worker.go
agent/worker_test.go
manager/logbroker/broker.go
manager/logbroker/broker_test.go
manager/logbroker/subscription.go

Just wanted to get feedback - it lacks tests and may need some cleanup but it works.
This PR adds `Wait` and `Done` to `subscription`, allowing `service logs` to wait for completion when in non-follow mode.
In non follow, the selectors are matched only once - if new tasks come in after that, no match will be attempted.
When a `PublishLogs` session finishes, we assume that subscription is completed for that node.
If a node disconnects (e.g. drops out of `ListenSubscriptions`), we assume all its active subscriptions are completed
/cc @aaronlehmann @stevvooe

service logs: Support for non-follow mode

---

ca/config.go

`updateKEK` runs `RenewTLSConfigNow` in a goroutine. If a manager is
switched between locked and unlocked mode quickly, some of these
certificate renewal goroutines could run at the same time. They could
potentially also overlap with a scheduled renewal.
This is bad because the `SecurityConfig` may end up using a different key
from the one on disk. The client and server credentials could
potentially get out of sync.
Limit `RenewTLSConfigNow` to one concurrent invocation.

ca: Prevent concurrent certificate renewals

---

manager/state/raft/raft.go
manager/state/raft/storage.go
manager/state/raft/storage_test.go

There is an error if the following happens:
1. uncommitted raft entry at index N comes in and is written to disk
2. raft DEK rotation + snapshot happens, snapshot finishes and root key is rotated. however, the snapshot is at index N-1, because N hasn't been committed yet
3. raft entry at index N is now committed
4. restart - we load the snapshot, at index N-1, and then the entry N is encrypted with the old key, so we can't bootstrap from disk
This PR changes the DEK rotation process.  Instead of starting to rotate when we begin a snapshot, we now always store the last written index whenever we write WALs to disk and we begin a snapshot after the applied index is >= the written index at the time we rotated the DEK.
cc @aluzzardi @aaronlehmann

Fix raft DEK rotation edge case bug

---

manager/allocator/networkallocator/networkallocator.go

On a leader change, the new leader restores the state for the existing networks from the store. But the overlay network's vxlan id was getting allocated afresh instead of restoring the current vxlan id allocated for the network.
related to [docker #28493](https://github.com/docker/docker/issues/28493) 
Signed-off-by: Santhosh Manohar <santhosh@docker.com>

On leader switchover preserve the vxlan id for existing networks

---

agent/worker.go

Fix https://github.com/docker/docker/issues/28915
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

Fix a goroutine misusage in the implementation of Worker.Subscribe()

---

Makefile

CI terminates early on the bump_v1.12.4 branch because the latest
version of golint doesn't like our argument positions. Rather than
change this in a patch release, change this branch to use an older
version of golint that won't interfere with CI.

[1.12.x] Use old golint version to unblock CI

---

log/grpc.go

log: mark grpc messages with module

---

manager/orchestrator/update/updater_test.go

The updater used to use StopGracePeriod to figure out how long to wait for stopping a task to timeout. In 47ddece4c66bcafc0563bedcc2d5db77033da003, this was changed to use an updater-level parameter instead. So there is no reason for tests to set StopGracePeriod or refer to it.

updater: Change tests not to set StopGracePeriod

---

agent/session.go

It turns out that no error is returned until we actually try to receive
from the stream. Move the check to the right place.

agent: Correct fix for pre-LogBroker managers

---

manager/state/raft/raft.go

If the ProcessRaftMessage RPC returns an error, the client treats that
as a potential transport-level error, and tries to reestablish a
connection.
In some cases this can cause a feedback loop. If ProcessRaftMessage
can't successfully check the health of the sending node, it returns an
error. That causes the sending node to bounce its outgoing connection,
which results in another health check failure.
To solve this, only return an error from ProcessRaftMessage when it is
necessary to communicate to the client that it has been removed from the
cluster. Ideally, I would fix this by having the client check
specifically for a transport-level error before bouncing the connection,
but there doesn't seem to be a reliable way to do this. Transport errors
can end up with many different codes that …

raft: Avoid returning errors from ProcessRaftMessage

---

manager/state/raft/raft.go

Fix silly race in ProcessRaftMessage logging introduced by #1779.
cc @LK4D4 @cyli

Fix race in ProcessRaftMessage logging

---

integration/cluster.go
integration/integration_test.go

Make graceful node removal optional. For existing tests, remove nodes
forcefully. This makes the integration tests run about 20s faster.
cc @LK4D4 @cyli

integration: Don't wait for dispatcher heartbeats to timeout

---

integration/cluster.go
integration/integration_test.go
integration/node.go
manager/manager.go
node/node.go

Do not stop the node if the manager returned with error `ErrMemberRemoved`.  The new test case does not deterministically trigger the `ErrMemberRemoved` case, but tends to do so after a few runs.
I think this fixes #1782.  Thanks to @tonistiigi for figuring out my test failure!
Currently running tests to see if it addresses https://github.com/docker/docker/issues/28987.

Propagate manager removal error

---

manager/logbroker/broker.go
manager/logbroker/subscription.go

Encountered a data race while running the unit tests on the 1.13.x
branch. The `Close` field is set without locking. Make sure it is only set
and checked with the subscription's lock held.
I also considered creating a copy of the subscription before setting
`Close` to true and sending it over the queue, but this seems a bit more
straightforward.
cc @aluzzardi

logbroker: Fix race on subscription.message.Close

---

manager/state/raft/raft.go

This deals with the edge case where a snapshot could be provided by a peer
that is much higher than the current written WAL index.  Also provide
additional logging in the case of a Docker test failure decrypting the
snapshot, which has been difficult to reproduce.

Update waitForAppliedIndex to always be > than the current snapshot index

---

manager/state/raft/raft.go

This function was recently changed to synchronize sends to the same
member, so that sending goroutines wouldn't impact each other by closing
the connection on an error.
To prevent the number of waiting goroutines from growing without bound,
`SendTimeout` was applied to both waiting for the last sender to finish,
and doing the actual I/O.
This may have unwanted consequences if two sends to the same member are
started around the same time and the first times out. The second will
only have a tiny amount of time to complete after waiting. It will
probably time out too, and bounce the connection as a result. So the
connection may be closed and reopened more than necessary, and this may
impact health checks, which reuse the same connections.
Change this function to reset the timeout after it …

raft: Add grace period to sendToMember

---

manager/state/raft/raft.go
manager/state/raft/storage.go
manager/state/raft/storage/storage.go

When completing a raft DEK key rotation, (which only happens when a snapshot is completed using the new DEK key, and the snapshot's index must be >= the index of the last WAL written with the old
key), remove the previous snapshots and WALs, since the old DEK will no longer be available and
they can't be decrypted anymore anyway.
Also, when a manager is removed from the cluster, the raft DEK will be removed and the TLS key
rotated to be that of a worker.  Since the DEK won't be available anyway, just remove the old
wal and snapshot directories instead of backing them up.
cc @aaronlehmann @diogomonica

Remove old snapshots when completing a raft DEK key rotation

---

manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/networkallocator_test.go

Attempt to fix docker/swarmkit issue https://github.com/docker/swarmkit/issues/1804 where IPAM options are not passed to RequestPool request in network allocator.
This is also related to the docker/swarmkit PR https://github.com/docker/swarmkit/pull/1789 which makes the IPAM options available.

Fix IPAM options not passed to RequestPool request

---

agent/exec/container/executor.go
manager/scheduler/filter.go
manager/scheduler/pipeline.go
manager/scheduler/scheduler_test.go

This carries #1517:
> Fix #1231. It was disabled in #1224, due to lazy loading by the engine.
> 
> Using the plugins API, it is possible to list installed plugins.
> 
> One issue is that we don't have a way of storing arbitrary plugins in the TaskSpec, from which to match them against the node on which `PluginFilter` is applied. For volumes and networks, this happens via a separate code path that allows for attaching to networks or mounting volumes. This is something we might want to build to support general plugins, and will require proto changes. This PR will work for volume and network v2 plugins.
On top of this, it adds:
- Fixes to the plugin filter to improve safety and consistency
- Don't fail `Describe` if `PluginList` is unimplemented
- Support for tags in plugin names
cc …

[Carry #1517] Support v2 plugins; re-enable scheduler plugin filter

---

agent/agent.go
agent/task.go
agent/task_test.go
agent/worker.go
agent/worker_test.go
integration/exec.go
node/node.go

One of the problem shown in https://github.com/docker/docker/issues/27124 is that overlay networks are not removed when a node leave swarm. The networks are associated with tasks. Node should remove all swarm tasks before leaving. 
On todo list, a more graceful leave would coordinate with manager. It'd inform manager of leaving, let manager drain tasks from the node, then stop the node. It'd require new message from node to manager. And manager putting node into a `leaving` state. 
cc @LK4D4 @stevvooe @mrjana @aaronlehmann. 

swarm leave should clean up assignments

---

MAINTAINERS

@cyli led the development of secrets (#1511, #1544, #1567) and at-rest encryption (#1598). These features not only involved a formidable engineering effort, but also patience with repeated design changes requested by maintainers, and hard work behind the scenes tracking down esoteric test failures. All work has gone a long way in making SwarmKit better designed, better abstracted, and better tested.
Welcome @cyli!

Add cyli to maintainers

---

manager/state/raft/raft.go

If we failed to save some entries to durable storage, we must stop the manager. The existing code just logs an error and continues, but this means the state essentially becomes corrupted and the manager may panic later. It's better to fail immediately.
The code path that involves `Run` returning early is not especially robust, and we've noticed some issues on demotion related to this. Despite this, the alternative of letting `Run` continue in this situation is much worse. We will need to fix the code path where `Run` returns early anyway, because it is used in demotion.

raft: Stop manager on write error

---

manager/state/raft/raft.go
manager/state/raft/raft_test.go

If a manager's raft state is lost or corrupted, it may try to join the
Raft cluster as a fresh member. This must be avoided, because it will
influence the quorum of the Raft cluster, which can prevent leader
elections from succeeding.
Add a check to `Join` that prevents a node with the same identity from
joining twice.

raft: Prevent the same manager from joining raft twice

---

MAINTAINERS

@dperny has been contributing to SwarmKit for several months. Recently he has been working on https://github.com/docker/docker-e2e, a framework for end-to-end testing of Docker, with a particular focus on testing SwarmKit.
Welcome @dperny!

Add dperny to maintainers

---

MAINTAINERS

@yongtang is a prolific contributor to swarmkit, frequently providing bug fixes before other maintainers even hear about the bugs. These fixes and improvements have helped a lot with stability and UX.
Welcome @yongtang!

Add yongtang to maintainers

---

vendor.conf
vendor/github.com/hashicorp/go-memdb/index.go
vendor/github.com/hashicorp/go-memdb/txn.go

The multi-index PR was merged upstream. We no longer need to vendor the
fork that adds this feature. Changes between the fork and the latest
master branch are minimal.

Unfork go-memdb

---

node/node.go

It allows to use defers for proper cleaning up.
Also, wait for workerRole only for 16 seconds, so if we missed role
change we wont stuck forever.

node: move running manager to separate function

---

manager/logbroker/broker.go
manager/logbroker/broker_test.go

The issue appears to be that stream RPC handlers are invoked
asynchronously. When `ListenSubscriptions` is called and returns a stream,
we don't have a guarantee that any code inside that RPC handler has
executed yet. When we call `SubscribeLogs`, `ListenSubscriptions` may not
have called `registerSubscription` yet, in which case `SubscribeLogs` will
think the associated node is down, and will call `Done` for that node
automatically.
Since the current API doesn't give us a way to ensure that the node has
registered as a log listener, insert a sleep to give
`ListenSusbscriptions` time to do its work. Ideally there would be a
better way to do this.
Also, remove some synchronization in `listenSubscriptions` that doesn't
help, and remove a capacity argument to `make` in a case where only a …

logbroker: Fix flaky test TestLogBrokerNoFollow

---

ca/config.go

Change "shuting" to "shutting"

ca: Fix log message typo

---

ca/certificates.go
log/context.go
manager/allocator/networkallocator/portallocator.go
manager/manager.go
manager/orchestrator/replicated/services.go

fix nits in func comments

---

design/task_model.md

This PR updates `design/task_model.md` for clarifying that multiple containers can share the single slot number because of a network partition between nodes.
Note that people may abuse the `{{.Task.Slot}}` template string without knowledge about this behavior. (https://github.com/docker/swarmkit/pull/1650, https://github.com/docker/docker/pull/28025)
The PR for the  "introspection mount" is related to this behavior as well. (https://github.com/docker/docker/pull/26331, https://github.com/docker/swarmkit/pull/1642)
- - - -
Below is the repro for the behavior I mentioned in this PR.
IMO we don't need to include this repro in `design/task_model.md` it self.
Consider that we have 1 manager node (`dm01`) and 2 worker nodes (`dm02` and `dm03`).
```console
dm01$ docker node ls
ID …
```

[doc] update description about the task slot

---

ca/config.go

RenewTLSConfig sends on a channel without checking if the context was cancelled. This can cause some goroutines to leak.
I noticed this while looking at stack traces from integration tests.

ca: Avoid blocking forever on channel send

---

node/node.go

Fix https://github.com/docker/docker/issues/29885. When manager or agent function fails, node run should exit and report error. 
cc @tonistiigi. 

node should exit from error

---

manager/state/raft/raft.go
manager/state/raft/wait.go

The demotion changes revealed an interesting race. If a proposal is
triggered at the same moment that something cancels it, the callback can
be called (which commits the transaction to memory), but an error can be
returned from `ProposeValue`, which causes the transaction to be aborted.
ProposeValue should return an error if and only if the callback was not
called.
Add a return value to `cancel()`. If `cancel` fails because the proposal was
already triggered, avoid returning an error.
Also, remove the `applyResult` type, since it isn't useful.

raft: Fix race when proposal is cancelled and triggered at the same time

---

cmd/external-ca-example/README.md
cmd/external-ca-example/main.go

Update this to reflect current `--external-ca` CLI option, and the lack of a `--manager` option in the current implementation.

external-ca-example: Correct example swarmd command

---

manager/state/raft/raft.go
manager/state/raft/wait.go

It's possible that the wait item is canceled and not triggered so that the result channel might be empty.

raft: fix deadlock in processInternalRaftRequest

---

manager/state/raft/raft.go

`Campaign` used to be passed a context that was derived from `Background`
(`n.Ctx`). Awhile ago, `n.Ctx` was removed, and this call to `Campaign` was
changed to use the context passed to `Run`.
This context may be cancelled before `Campaign` is complete. This leads to
a panic.
Remove the panic, because it can trigger accidentally and it serves no
purpose.
cc @aboch @LK4D4 @cyli

raft: Don't panic on Campaign failure

---

integration/integration_test.go

I should have noticed before merging it, but unfortunately `TestRestartLeader` roughly doubles the time it takes to run integration tests.
These changes take it from about 50s to 15s for me:
- Don't wait for the leader's agent to get marked as `DOWN`, as this takes
a long time.
- Lower the number of workers and managers. In principle, the test
doesn't need a high number of workers, since the workers are
completely independent.
cc @LK4D4

integration: Speed up TestRestartLeader

---

api/ca.pb.go
api/control.pb.go
api/dispatcher.pb.go
api/health.pb.go
api/logbroker.pb.go
api/raft.pb.go
api/resource.pb.go
ca/auth.go
ca/server.go
manager/manager.go
protobuf/plugin/raftproxy/raftproxy.go
protobuf/plugin/raftproxy/test/raftproxy_test.go
protobuf/plugin/raftproxy/test/service.pb.go

For swarm mode to function without exposing a TCP port, we need services
such as the dispatcher and node CA to be exposed on the control socket
(i.e. a unix socket). This commit changes the manager to expose those
services, and changes the raft proxy to inject some information into the
context when calling the handler directly that identifies the local
node. The authorization code in "ca" is updated to check for this
information on the context and make use of it, instead of returning an
error from RemoteNode. Also, the CA server now renewing a certificate
over the control socket.
This is the first part of #1826, broken out of that PR as requested.
cc @LK4D4 @cyli @diogomonica

Expose needed services on the control socket

---

connectionbroker/broker.go

This package is a small abstraction on top of `Remotes` that provides a
gRPC connection to a manager. If running on a manager, it uses the unix
socket, otherwise it will pick a remote manager using `Remotes`. This
will allow things like agent and certificate renewal to work even on a
single node with no TCP port bound.
This is a piece of #1826. The next PR will convert the CA and agent to
use connectionbroker.

Add connectionbroker package

---

ca/server.go
manager/dispatcher/dispatcher.go

The ca server's Stop method waits until all running handlers finish.
This may deadlock if quorum is not met at the time. Some of the other
services like dispatcher used to work like this, but it shouldn't be
necessary anymore. Remove the wait group.

ca: Don't block server's Stop until handlers finish

---

manager/allocator/networkallocator/portallocator.go
manager/allocator/networkallocator/portallocator_test.go

This fix tries to address the issue raised in docker/docker#29730 where a service with multiple published ports mapping to the same target port (e.g., `--publish 5000:80 --publish 5001:80`) can't be allocated.
The reason for the issue is that, `getPortConfigKey` is used for both allocated ports and configured (may or may not be allocated) ports. However, `getPortConfigKey` will not take into consideration the `PublishedPort` field, which actually could be different for different allocated ports.
This fix saves a map of `portKey:portNum:portState`,  instead of currently used `portKey:portState` so that multiple published ports could be processed.
A test case has been added in the unit test. The newly added test case will only work with this PR.
Signed-off-by: Yong Tang …

Fix issues of multiple published ports mapping to the same target port

---

ca/server.go

The `WaitGroup` was removed as a simplification in #1841, but this causes `(*Server).Stop` to potentially return before Run is finished. This is unwanted behavior that causes data races in tests. Readd the `WaitGroup`, but only use it to wait for Run to finish, not RPC handlers.
cc @dperny @cyli

ca: Readd WaitGroup to Server

---

agent/agent.go
agent/agent_test.go
agent/config.go
agent/resource.go
agent/session.go
ca/certificates.go
ca/certificates_test.go
ca/config.go
ca/config_test.go
ca/testutils/cautils.go
manager/manager.go
node/node.go
node/node_test.go

By using `connectionbroker` instead of using `remotes` directly, subsystems
like the agent can connect directly to the local manager when running on
a node that acts as a manager. This avoids the need for the manager to
expose a TCP port at all times.

Convert code to use connectionbroker package

---

ca/server.go
manager/dispatcher/dispatcher.go

This reverts #1841 and #1854.
`ca` unit tests appear to be hanging in CI runs against `master`. It's either because of these changes or #1851. Unfortunately I can't reproduce the problem locally. #1851 has passed CI several times, so I'm starting by trying to revert #1841 / #1854. If these turn out to be the problem, I'll figure out what's going on later, and open a fixed PR with that change.

Revert recent CA server changes

---

manager/state/raft/raft.go
manager/state/raft/raft_test.go
manager/state/raft/storage.go
manager/state/raft/storage_test.go

When loading a snapshot while forcing a new cluster, we need to avoid removing ourselves from the member list. This caused the restored swarm to show zero managers.
Add a test.
Also, fix a few small items:
- Remove unnecessary cast
- Change `map[uint64]bool` to `map[uint64]struct{}`
- Remove trailing space in log message
- Active members listed in the snapshot should be added to the removed list, not simply ignored.
- Use `assert.Len` in raft tests.
This is a 1.13-rc regression caused by #1469.
cc @LK4D4 @cyli

Fix remaining manager being removed from member list by --force-new-cluster

---

manager/controlapi/common.go
manager/controlapi/network.go
manager/controlapi/network_test.go

Due to multiple issues in both plugin-v1 and plugin-v2 support, 
this patch will disable the network plugin support by gracefully 
failing the network create if either network or ipam plugin is used. 😢 
We will revisit the support once the plugin issues are resolved.
Signed-off-by: Madhu Venugopal <madhu@docker.com>

Gracefully fail if Network and IPAM plugins are used

---

manager/dispatcher/dispatcher.go
manager/dispatcher/dispatcher_test.go

The Stop method did not wait for Run to complete, so in theory it would be possible to call Run again before the first instance is complete. Fix this by adding a waitgroup.
`d.ctx` is used in some places without locking. In a fast restart scenario, this could cause the wrong context to be used. Make sure that all uses of `d.ctx` use locking.

dispatcher: Correct problems with starting and stopping

---

ca/external.go

It shouldn't be necessary to manually close the request body when the
context is cancelled. ctxhttp should take care of this automatically.
Closing the body triggers a race on Go < 1.7, since it turns out ctxhttp
uses a wrapper around Body that is not reentrant.
Remove the goroutine that closes the body when the context is canceled.
cc @cyli @stevvooe

ca: Remove unneeded code to cancel requests to external CAs

---

manager/orchestrator/update/updater.go

If the manager is shut down during a task update, `updateTask` might still delay, and block the shutdown process.
Have the closure of `stopChan` abort `updateTask`.
cc @tonistiigi @dongluochen

updater: Fix hang on shutdown

---

api/specs.pb.go
api/specs.proto

The field `ServiceSpec.Networks` has been deprecated and is replaced by `ServiceSpec.Task.Networks`. There is no description for that field other than a tag of `[deprecated=true]`.
This fix updates the documentation on the deprecated `ServiceSpec.Networks` and directs user to use `ServiceSpec.Task.Networks` instead.
This fix is related to the comment:
https://github.com/docker/docker/pull/29463#issuecomment-271387898

Update the documentation on the deprecated `ServiceSpec.Networks`

---

cmd/swarmctl/cluster/common.go
cmd/swarmctl/network/common.go
cmd/swarmctl/node/common.go
cmd/swarmctl/service/common.go

The swarmctl tool resolves names with the `NamePrefixes` filter. This
doesn't seem right. The user should give full names, not abbreviated
ones. It causes problems with services whose names share prefixes - for
example it's difficult to remove a service named "busybox" when one
named "busybox-top" also exists.
A case could be made for supporting ID prefixes instead, but this
isn't currently implemented, so it doesn't seem like a priority.
Use `Name` instead of `NamePrefixes` to switch to exact name matching.
cc @stevvooe

swarmctl: Match full name, not name prefix

---

Makefile
cmd/swarm-rafttool/common.go
cmd/swarm-rafttool/common_test.go
cmd/swarm-rafttool/main.go

So we can view bits of information.  Currently this is just cluster data - not sure what else would be useful - creating a new directory with decrypted raft data for the user to debug?
Possibly this could be a docker image?  This PR is more of a discussion on what tooling we can provide for debugging.  Alternately we can kill this and create a tool that's not part of swarmkit.

[cmd] tool to decrypt or downgrade raft logs

---

manager/controlapi/service.go

SwarmKit: updateService does not return proper gRPC errors for some errors. Also, no error is returned if a service cannot be found. #1685
Signed-off-by: Daniel Zhang <jmzwcn@gmail.com>

SwarmKit:updateService does not return proper gRPC errors for some errors. Also, no error is returned if a service cannot be found

---

integration/integration_test.go

This decreases the runtime a lot. Before:
ok      github.com/docker/swarmkit/integration  77.224s
After, with -parallel 8:
ok      github.com/docker/swarmkit/integration  27.614s
It may put more stress on the machine and reveal races that don't
trigger otherwise, but that's good, right?
cc @LK4D4

integration: Run tests in parallel

---

manager/controlapi/common.go
manager/controlapi/network.go
manager/controlapi/network_test.go

With https://github.com/docker/swarmkit/pull/1876 in, we must revert https://github.com/docker/swarmkit/pull/1856.
This reverts commit 775a4bc0febbcace936511a36ca30144e81e2c63.

Revert "Gracefully fail if Network and IPAM plugins are used"

---

manager/allocator/allocator.go
manager/allocator/allocator_test.go
manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/networkallocator_test.go
manager/controlapi/common.go
manager/controlapi/network.go
manager/controlapi/network_test.go
manager/manager.go
node/node.go

Cherry-picking #1876 and reverts #1856 in 1.13.0 branch in order to bring in network plugin support into 1.13.1 release.

Cherry-picking #1876 and reverts #1856 in 1.13.1 branch

---

integration/integration_test.go

In rare cases, TestDemoteDownedManager can fail. The scenario involves
choosing the third manager to demote, and stopping it before it has a
chance to write any entries to its WAL. When it starts back up, it
doesn't know of any other members in the cluster (and no other members
will connect to it since it has been removed), so it has no way of
knowing it has been removed.
To avoid this case, we can simply avoid choosing the third manager.
Adding that manager is a synchronization point which guarantees that the
first and second managers will be caught up, and removing either at this
point wouldn't pose the same problem. In practice, we end up removing
the second manager, since the first is the leader.
cc @LK4D4

integration: Be choosy about which manager to demote

---

api/ca.pb.go
api/control.pb.go
api/dispatcher.pb.go
api/duration/duration.pb.go
api/health.pb.go
api/logbroker.pb.go
api/objects.pb.go
api/raft.pb.go
api/resource.pb.go
api/snapshot.pb.go
api/specs.pb.go
api/timestamp/timestamp.pb.go
api/types.pb.go
protobuf/plugin/deepcopy/deepcopy.go
protobuf/plugin/deepcopy/test/deepcopy.pb.go

To ensure that pointers get set to nil, we now set all the fields with a
shallow copy before copying each component. This should be both safer
and faster.

deepcopy: copy scalars with memset

---

vendor.conf

We used to vendor a fork which had fixes we needed. Now the fixes have
been merged upstream. This switches vendor.conf over to the latest
released version, which happens to be identical to the fork we were
vendoring before. This is also the version vendored by docker/docker.

Vendor upstream logrus

---

README.md
manager/constraint/constraint.go
manager/scheduler/constraint_test.go

Fix #1880. 
This change adds support for `node.ip` constraint. It matches IPv4/IPv6 address or CIDR subnet.
```
node.ip==192.168.42.5
node.ip!=192.168.42.5
node.ip==2001:db8::8/64
node.ip!=2001:db8::8/64
```

Support node IP constraint

---

integration/cluster.go
integration/integration_test.go
integration/node.go
manager/manager.go
manager/manager_test.go
manager/state/raft/membership/cluster.go
manager/state/raft/raft.go
node/node.go

We'd like Docker to support swarm services without needing to run `swarm init`. One of the preconditions for this is that the swarm manager needs to operate and be useful without exposing a port to the outside world.
This PR is split into multiple parts, which will each become a separate PR for ease of review. The first few commits are focused on allowing the agent and certificate issuance/renewal to work without relying on a TCP connection to back to the same process. This works by exposing servers such as the dispatcher and node CA on the unix socket (or equivalent), and using that instead of a TCP connection. In theory we could codegen something to patch the calls straight through to the handlers (with some stuff injected onto the context to identify the caller as the local node), but …

Allow managers not to expose a remote API port

---

manager/controlapi/common.go
manager/controlapi/network.go
manager/controlapi/network_test.go
manager/controlapi/server.go
manager/controlapi/server_test.go
manager/manager.go

In swarm mode, only network pluginv2 is supported; pluginv1 is not. When
the plugin support was re-enabled in 1.13.x, it inadvertently allowed
both pluginv1 and pluginv2. This commit fixes that.
Signed-off-by: Anusha Ragunathan <anusha.ragunathan@docker.com>

Explicitly disallow network pluginv1 creation in swarm mode.

---

manager/controlapi/common.go
manager/controlapi/network.go
manager/controlapi/network_test.go
manager/controlapi/server.go
manager/controlapi/server_test.go
manager/manager.go

This reverts commit 0b0e2a4bd9006c97356989abffa184f51a0058bb.
I realized this PR was merged directly to `bump_v1.13.1`, but it should have been opened against master and cherry-picked afterwards. Also @anusha-ragunathan mentioned that there are some additional fixes to add. We'll take care of these in a new PR and then cherry-pick everything.
cc @mavenugo

Revert "Explicitly disallow network pluginv1 creation in swarm mode."

---

manager/state/store/by.go
manager/state/store/memory.go

This is a leftover from when we had a RegisteredCertificate type. It
isn't used anywhere. Remove dead code.

store: Remove ByCN

---

manager/controlapi/common.go
manager/controlapi/network.go
manager/controlapi/network_test.go
manager/controlapi/server.go
manager/controlapi/server_test.go
manager/manager.go

In swarm mode, only network pluginv2 is supported; pluginv1 is not.
When the plugin support was re-enabled, it inadvertently allowed
both pluginv1 and pluginv2. This commit fixes that.
Signed-off-by: Anusha Ragunathan <anusha.ragunathan@docker.com>

Cherrypick 1899 to 1.13.1

---

manager/dirty.go
manager/dirty_test.go
node/node.go

As one of the requirements for enabling Swarm mode by default, we need
to prevent "swarm init" or "swarm join" commands from unintentionally
overwriting data that was added to Raft previously. We do this by adding
a `IsStateDirty` method that inspects the contents of the Raft store.
Any data other than a cluster object and object for the local node make
the state dirty.
Note that this function is inherently racy, since new data could be
added while the check is run, or shortly afterwards. However this is
considered acceptable, since the purpose is to check for old data that
the user may accidentally overwrite, not concurrent modifications.
cc @aluzzardi @ehazlett

manager: Add a function to check if the raft state is dirty

---

ca/server.go
ca/server_test.go
manager/dispatcher/dispatcher.go

This supersedes #1841 and #1854, which implemented part of this change, but were later reverted because they caused problems.
Change the CA server not to wait for handlers to finish before exiting. This isn't really necessary, and other subsystems like the dispatcher don't do it.
Fix `TestRestartRootCA` to do what was intended. It was calling a RPC that didn't depend on the server being up, and also wasn't waiting for the server to start.
Correct uses of `s.ctx` that were missing locking. These could have been races in cases where the server was restarted quickly.
The dispatcher (where this code originally came from) has some similar problems, and I'll open a separate PR for that.

ca: Server waitgroup/locking fixes, take 2

---

manager/allocator/network.go
manager/allocator/network_test.go
manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/portallocator.go
manager/allocator/networkallocator/portallocator_test.go

This fix tries to fix the issue in docker/docker#30199 where service update will not work when published ports is host publish mode.
The reason for the issue is that `isPortsAllocated()` does not capture host publish mode.
This fix address the issue by updating allocated ports if there is any change in ports of host (non ingress) mode as well.
Unit tests have been added.

Fix issue in service update of published ports in host mode

---

manager/state/raft/raft.go

This is causing problems in some real-world setups. Disable it until we can come back and make it more robust.
cc @LK4D4

[1.13] raft: Disable address change detection

---

manager/state/raft/raft.go

This is causing problems in some real-world setups. Disable it until we can come back and make it more robust.
I'll open a separate PR for 1.13.x.
cc @LK4D4

raft: Disable address change detection

---

manager/allocator/network.go
manager/allocator/network_test.go
manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/portallocator.go
manager/allocator/networkallocator/portallocator_test.go

This pull request is for cherry-pick of #1875 to v1.13.1:
[#1875]: Fix issue in service update of published ports in host mode
In additional to the above cherry-picked PR, this PR also includes a fix up with `allocatedPorts` definition. The `allocatedPorts` was added in #1835 which is not part of the v1.13.1.

[v1.13.1] Cherry-Pick [#1875]: Fix issue in service update of published ports in host mode

---

Makefile
api/ca.proto
api/control.proto
api/dispatcher.proto
api/logbroker.proto
api/objects.proto
api/raft.proto
api/resource.proto
api/specs.proto
api/types.proto
cmd/protoc-gen-gogoswarm/main.go
protobuf/plugin/customnameid.go

This fix tries to address the issue in #1785 where `gogoproto.customname` was repeatedly used  to manually map ID names conforming to golang convention.
This fix address the issue by preprocess the fields and
set `gogoproto.E_Customname` as needed, if name matches
certain pattern:
1. id -> ID
2. id_some -> IDSome
3. some_id -> SomeID
4. some_ids -> SomeIDs
This fix does not change the generated pb.go.
This fix fixes #1785.
/cc @aaronlehmann @stevvooe

Replace gogoproto.customname with plugin that maps ID name

---

manager/controlapi/service.go
manager/controlapi/service_test.go
manager/orchestrator/replicated/services.go

This parameter is declared as a uint64, but if an API user tries to put
a negative number in it and underflows the field, the replicated
orchestrator will panic when it converts the value to an int and tries
to use it as as slice index.
Fix this in the replicated orchestrator by avoiding the conversion to
int, and also add validation in controlapi that the sign bit is unset.
Fixes #1906
cc @alexellis @samoht

Add more validation around Replicas parameter

---

agent/exec/controller.go
agent/exec/controller_test.go

As @stevvooe pointed out in https://github.com/docker/docker/issues/30327, an error is leak when worker restarts and fails to resolve a task. I think if a `Running` task fails to resolve, we should move it to `Failed` so manager can restart/reschedule it.  
Ping @stevvooe @thaJeztah @aaronlehmann. 

fail task when it cannot be resolved

---

ca/certificates.go
ca/config.go
ca/config_test.go
integration/cluster.go
integration/integration_test.go
integration/node.go
node/node.go

This is based on https://github.com/docker/swarmkit/pull/1912.
This PR makes the following changes:
1.  Allows a node to start up with expired certs if `ForceNewCluster` is set
1.  Changes the certificate renewal loop renew immediately if the certificate is expired.  This allows a `ForceNewCluster`'d node to get new TLS certificates soon.  This means that a leader can also recover from expired certificates.  No other node can recover, however, since renewing TLS certs would mean that they have to request a new cert from the CA, and would not be able to establish a mTLS connection to the CA due to expired certs.   This mean that we keep making requests to the CA even when there's no chance of recovery, which may not be desirable.
cc @aaronlehmann @LK4D4

ca+node: Allow expired certs when forcing a new cluster

---

ca/certificates.go
ca/config.go
ca/config_test.go

This checks the format of the swarm token so that there would be a more obvious error if the token were mis-typed (for instance, copy-pasting the join token but leaving off the last character).
This also prints out more debugging information if a node certificate fails to validate (such as the issuer, and the "not before" and "not after" dates, making certificate expiry errors easier to debug.
cc @thaJeztah

ca: more informational error messages and debug logs

---

cmd/protoc-gen-gogoswarm/customnameid.go
cmd/protoc-gen-gogoswarm/main.go

This was located in `protobuf/plugin`, which is imported by swarmkit code.
Because it imports some extra protobuf packages, it was adding
dependencies to code that vendors swarmkit.
Move this code to `cmd/protoc-gen-gogoswarm`, since it's only needed for
this code generation tool. This avoids new dependencies for swarmkit
downstreams.
cc @yongtang

Relocate customnameid gogo plugin

---

ca/config.go
integration/cluster.go
integration/integration_test.go

#1919 inadvertently left a `logrus.Debug` setting in the integration test, which was causing a data race.
Also, add the following optimizations for the integration test added in #1919:
- make the renew TLS certificate loop's exponential backoff configurable, so it can be set for testing
- if a node exits before it's ready, bail `integration.cluster.StartNode` early so we don't have to
wait for the timeout

Fix integration test data race and slowness

---

cmd/swarmctl/service/logs.go
manager/logbroker/subscription.go
manager/state/raft/storage/storage_test.go
manager/state/raft/storage/walwrap.go
manager/state/raft/storage/walwrap_test.go
node/node_test.go

This allows to compile swarmkit with GO 1.6.
/cc @aaronlehmann @stevvooe @LK4D4 

Use `golang.org/x/net/context` instead of `context`

---

manager/controlapi/service.go
vendor.conf
vendor/github.com/docker/distribution/digestset/set.go
vendor/github.com/docker/distribution/reference/helpers.go
vendor/github.com/docker/distribution/reference/normalize.go
vendor/github.com/docker/distribution/reference/reference.go
vendor/github.com/docker/distribution/reference/regexp.go

Use normalizing parser to validate non-normalized names.
This change coincides with https://github.com/docker/docker/pull/30043 on the engine. Further updating the distribution dependency on the engine requires this update to handle stricter parsing in `ParseNamed`.

Update distribution reference package dependency

---

cmd/swarmctl/node/common.go
cmd/swarmctl/node/update.go

This PR includes the following:
- Fix usage of `swarmctl node update`
- Add a argument length validation into `updateNode()`
Signed-off-by: Kei Ohmura <ohmura.kei@gmail.com>

swarmctl: Fix usage and add a validation for 'swarmctl node update'

---

manager/allocator/network.go
manager/allocator/networkallocator/networkallocator.go
manager/allocator/networkallocator/portallocator.go

This fix fixes the issue raised in:
https://github.com/docker/docker/issues/29247
where duplicated ports (`PublishedPort`) is being allocated with restarted swarm nodes.
The reason for the issue was that `isPortsAllocated` relies on portSpace which does not capture the ports in restored services when swarm is restarted.
This fix add a flag in `isPortsAllocated` so that in case the allocator is still in initialization stage, dynamically allocated ports (`PublishedPort`) will always be reallocated.
See docker PR: https://github.com/docker/docker/pull/29277

Fix duplicated ports allocation with restarted swarm

---

agent/worker.go
integration/integration_test.go

This doesn't actually fix the flakey test yet - the `pollServiceReady` function is checking for all tasks on the node, instead of only the running tasks for that particular service, which masks the returned error.
The underlying cause is being fixed by @aaronlehmann in another PR.

Fix how TestForceNewCluster checks if a service is ready

---

manager/allocator/network.go

If the allocator starts up and sees a task in the NEW state that doesn't
need allocations, it should move it to PENDING immediately.
There was code in place for this but it wasn't actually updating the
task's state. The task would get stuck and never get assigned.
ping @cyli

allocator: Fix stuck tasks at startup

---

MAINTAINERS

I notice Charles was still listed, but not in the "people" list below 👍 . There's no documentation in this repository, but in case documentation changes _may_ be needed, keeping the "docs maintainers" list here for now 
/cc @mstanleyjones

Update docs maintainers list

---

manager/orchestrator/taskreaper/task_reaper.go

Currently, the task reaper only waits for a task's desired state to go
past "running" before deleting it. This can cause problems with rolling
updates when task-history-limit is set to 1. The old task can get
deleted by the reaper before the agent has a chance to update its actual
state to "shutdown", so the update never sees that the task has
completed, and has to wait awhile for a timeout.
This fixes it by making the task reaper only delete tasks whose desired
*and* actual state has moved past "running". It's also necessary to keep
slots in the "dirty" list until there is only one task in that slot with
desired state or actual state <= "running", so that the old task still
gets cleaned up once the actual state moves. Finally, "deleteTasks" is
changed to a map so that a task which is …

taskreaper: Wait for tasks to stop running

---

ca/certificates.go
ca/certificates_test.go
ca/external.go

This is not required as per RFC5246 section 7.4.2, and if we wanted to support cross-signed intermediates we probably should not include the self-signed root.

Do not append the root certificate to the leaf server/client TLS cert

---

manager/controlapi/service.go
manager/controlapi/service_test.go

I found that type `ServiceSpec` has fields like:
```
type ServiceSpec struct {
Annotations Annotations `protobuf:"bytes,1,opt,name=annotations" json:"annotations"`
Task TaskSpec `protobuf:"bytes,2,opt,name=task" json:"task"`
Mode isServiceSpec_Mode `protobuf_oneof:"mode"`
Update *UpdateConfig `protobuf:"bytes,6,opt,name=update" json:"update,omitempty"`
Networks []*NetworkAttachmentConfig `protobuf:"bytes,7,rep,name=networks" json:"networks,omitempty"`
Endpoint *EndpointSpec `protobuf:"bytes,8,opt,name=endpoint" json:"endpoint,omitempty"`
}
```
Then I think in https://github.com/docker/swarmkit/blob/master/manager/controlapi/service.go#L293-L318:
```
func validateServiceSpec(spec *api.ServiceSpec) error {
if spec == nil {
return …
```

move secret validation into task validation

---

manager/controlapi/service.go
manager/controlapi/service_test.go

validate more fields in update when creating a service or update a service.

validate more fields in update

---

manager/keymanager/keymanager.go

Related to [docker #25608](https://github.com/docker/docker/issues/25608)
Also seen by an UCP customer.
In a 3 manager 2 workers cluster I was able to recreate the issue by reloading all the managers at the same time. There are two symptoms: 
- encrypted gossip traffic failing with the error `No installed keys could decrypt the message`
- If there are networks with datapath encryption enabled a panic in the overlay driver sometimes.
When the leader goes down one of the other two nodes become a leader and does a key rotation and updates the store. But since its going down as well,there isn't enough time for workers to connect to that lead manager. When the managers come back up a new leader is elected and that does a key rotation again. In essence when workers get the keys from the new …

Avoid encryption key rotation on leader change

---

manager/orchestrator/global/global.go
manager/orchestrator/global/global_test.go
manager/orchestrator/replicated/replicated_test.go
manager/orchestrator/replicated/services.go
manager/orchestrator/replicated/tasks.go
manager/orchestrator/task.go
manager/orchestrator/taskinit/init.go

Fix #1812. 
Global orchestrator considers a `rejected` task not running and adds a new task to it. But this should be handled by task restart logic.  
```
gtest.0.tvi9nt4n7ghn  busybox:latest  ip-172-19-241-146          Ready          Rejected 1 second ago            "failed to allocate gateway (1…"
```

orchestrator should fix tasks before start

---

manager/orchestrator/global/global.go

Global orchestrator reconcileServices should look at desired state only to avoid creating multiple tasks. 

Global orchestrator reconcileServices should look at desired state only

---

manager/allocator/networkallocator/portallocator.go
manager/allocator/networkallocator/portallocator_test.go

- It needs to skip the configured to allocated port state check
when the configured host mode publish port is missing.
Because swarm will never get to know the currently published
port (state), which is being chosen by the engine on each
node, and therefore may be a different port in each host.
Related to docker/docker/issues/30938
Signed-off-by: Alessandro Boch <aboch@docker.com>

Fix portsAllocatedInHostPublishMode

---

cmd/swarm-bench/collector.go
cmd/swarmctl/cluster/inspect.go
cmd/swarmctl/node/inspect.go
cmd/swarmctl/service/inspect.go
cmd/swarmctl/task/inspect.go

Correct fmt.Fprintf and fmt.Printf, because the values used for formatting text does not appear to contain a placeholder.
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>

Correct fmt.Fprintf

---

manager/orchestrator/constraintenforcer/constraint_enforcer.go
manager/orchestrator/constraintenforcer/constraint_enforcer_test.go
manager/orchestrator/global/global.go

The constraint enforcer currently sets task desired state to "shutdown"
directly, which means the orchestrator will consider these tasks already
processed, and won't trigger restarts. While this is appropriate for
global services, replicated services should keep the desired number of
replicas running, so each task shut down by the constraint enforcer
should be restarted somewhere else.
This changes the constraint enforcer to trigger a task shutdown by
updating the actual state rather than desired state. This will cause the
orchestrator to restart the task when necessary. It's not a perfect
solution, because it bends rules about field ownership, and may cause
the replacement task to start before the old one stops. However, it's a
good compromise solution for this problem that doesn't …

constraintenforcer: Trigger task restarts when appropriate

---

cmd/swarm-rafttool/dump.go
cmd/swarm-rafttool/main.go

- Add dump-wal subcommand, which can dump all entries (or a subset) from
the WAL.
- Add dump-snapshot subcommand, which can dump the information from the
latest snapshot.
- Add dump-object subcommand, which can dump an object from the current
state of the store by its ID.
cc @cyli

swarm-rafttool: Add entry and object dumping capabilities

---

manager/controlapi/node_test.go
manager/role_manager.go
manager/state/raft/raft.go
manager/state/raft/transport/transport.go

When we demote the leader, we currently wait for all queued messages to be sent, as a best-effort approach to making sure the other nodes find out that the node removal has been committed, and stop treating the current leader as a cluster member. This doesn't work perfectly.
To make this more robust, use `TransferLeadership` when the leader is trying to remove itself. The new leader's reconcilation loop will kick in and remove the old leader.
cc @LK4D4 @cyli

raft: Use TransferLeadership to make leader demotion safer

---

cmd/swarmd/main.go
connectionbroker/broker.go
manager/manager.go
manager/state/raft/transport/transport.go
manager/state/raft/util.go
node/node.go
vendor.conf
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/LICENSE
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_reporter.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_reporter.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/util.go

This PR adds Prometheus metrics export (using `--listen-metrics`) as
well as gRPC interceptors to automatically collect gRPC metrics.
Eventually we'll instrument code where it makes sense but this change is
a good start since it already captures a lot of what the internals are
doing (e.g. Dispatcher/Agent communication, Raft, ...).
For now this only includes server metrics - client metrics will follow.
Note that metrics export is done in `cmd/swarmd` - for applications that
import swarmkit and already export Prometheus metrics (such as Docker),
these metrics will automatically be exported with whatever system is
already in place.
/cc @aaronlehmann @LK4D4 @stevvooe @crosbymichael

gRPC Metrics

---

agent/agent_test.go
agent/reporter_test.go
agent/task_test.go
manager/dispatcher/heartbeat/heartbeat_test.go
manager/scheduler/scheduler_test.go
manager/state/raft/storage.go
manager/state/store/memory_test.go
remotes/remotes_test.go

as the source code said:
```go
// Fatal is equivalent to Log followed by FailNow.
func (c *common) Fatal(args ...interface{}) {
c.log(fmt.Sprintln(args...))
c.FailNow()
}
// Fatalf is equivalent to Logf followed by FailNow.
func (c *common) Fatalf(format string, args ...interface{}) {
c.log(fmt.Sprintf(format, args...))
c.FailNow()
}
```
If there is no need string format, we can just use Fatal instead.
Signed-off-by: kevinetc123 <kaiwentan@harmonycloud.cn>

Simplify Fatalf to Fatal

---

manager/scheduler/constraint_test.go
manager/scheduler/nodeinfo.go
manager/scheduler/nodeset.go
manager/scheduler/scheduler.go

Currently, the scheduler counts tasks on each node with desired state of
RUNNING. This works fine for sequential updates, but in parallel
updates, the scheduler can assign tasks unfairly, because the ones it
already assigned may not have changed their desired state to RUNNING
yet. In an update with unlimited parallelism, all the tasks may end up
on the same node, even when there are multiple nodes that can accomodate
the tasks.
Fix this by considering all tasks with a desired state at or below
RUNNING to be active. For example, tasks at READY should be seen the
same way as RUNNING tasks by the scheduler - they were assigned to that
node and will eventually start running.
cc @jlhawn @aluzzardi @dongluochen

scheduler: Tasks with a desired state < RUNNING should count

---

manager/orchestrator/update/updater.go

If the `UpdateConfig` field in the service spec is nil, the update parallelism should default to `1` but it currently defaults to `0`.
To have "infinite" parallelism, you must now explicitly set update parallelism to `0`.

[update] Use default parallelism of 1

---

manager/orchestrator/update/updater.go

The updater monitors a tasks after they start to make sure they don't
fail immediately. The default time interval for this is 30s. However,
this is a bit long for synchronous updates to wait. Reduce it to 5s.
Users who would like a longer monitoring period should specify their own
value, or ideally use a health check in the service definition.

updater: Decrease default monitoring period

---

Makefile

This won't catch all spelling errors, but can help catch at least some.
I didn't see any false positives locally except for the MAINTAINERS doc where it thought "Sebastiaan" should be "Sebastian", so I excluded that file.

ci: Add a `misspell` make target and to the checks run during CI

---

.gitignore

These are obvious locations where `swarmkitstate` might be created during
testing, but the `swarmkitstate` should literally never be checked into
verison control, ever, and so shouldn't show up in git status.

Add swarmkitstate/ and bin/swarmkitstate/ to gitignore

---

ca/server.go
ca/testutils/cautils.go
manager/manager.go
manager/manager_test.go

Rather than just the leader that is running the CA server.  This way on root rotation, all managers will get root changes right away.
#1983 will actually update the TLS creds with the new root pool when the RootCA is updated

ca: all managers will update their security configs when cluster root CA updated

---

manager/controlapi/node_test.go
manager/state/raft/membership/cluster_test.go
manager/state/raft/raft_test.go
manager/state/raft/storage_test.go
manager/state/raft/testutils/testutils.go

Simple change to remove an unused argument.

raft/testutils: Remove unused argument in TeardownCluster

---

ca/certificates.go
ca/config.go
ca/config_test.go
ca/testutils/cautils.go
ca/transport.go

So that both can use the new root CA pool to validate peers.

ca: when the Root CA is updated in the security config, update all TLS creds too

---

ca/certificates.go
ca/certificates_test.go
ca/config_test.go
ca/keyreadwriter.go
identity/randomid.go
integration/integration_test.go
manager/encryption/encryption.go
manager/encryption/nacl.go
manager/encryption/nacl_test.go
manager/keymanager/keymanager.go

I'm a bit uncomfortable with importing crypto/rand as "rand", because
this name can clash with math/rand. The packages both define a Read
function. If code is moved around and an IDE helpfully imports math/rand
for something that needs cryptographic randomness, this can introduce a
big vulnerability.
Import crypto/rand as "cryptorand" instead to make this less ambiguous.

all: Import crypto/rand as "cryptorand"

---

integration/cluster.go
integration/integration_test.go
node/node.go

Currently, we wait 16 seconds for the role to change, and restart the
manager if it doesn't happen. This may be the right thing to do, because
if the node is promoted again, we might never see a role change. But
it's also possible that the 16 second timeout can be hit even with no
promotion, and this is a bad failure mode because it unexpectedly
re-adds the node to the Raft cluster.
Address this by being extra careful when the node was demoted, and
trying to force a certificate renewal in the case where we still don't
see a role change after 16 seconds.
This also adds `RenewTLSConfig` to node's waitgroup, to avoid some test
failures where `RemoveAll` returned an error because `RenewTLSConfig` was
still running.
Fixes #1991
Fixes #1997

node: Try to force TLS certificate renewal if role doesn't change after demotion

---

agent/exec/dockerapi/adapter.go

Fixes the format of the service logs since option in the reference
dockerapi implementation. Before this change, since failed silently
because the docker daemon cannot handle a timestamp in the format
RFC3339Nano.
This PR does not add a `--since` flag to swarmctl, because it is a
companion PR to reflect a PR I'm about to put into docker/docker.

Fix service logs since option

---

ca/certificates.go
ca/certificates_test.go
ca/config_test.go
ca/testutils/cautils.go
integration/integration_test.go
integration/node.go
manager/manager.go

Was thinking that intermediates could be stored in this object, since they're only used for signing.  It's just easier to see at a glance what is and isn't relevant to signing.
At a future point we might want to distinguish between the roots used for trust and the signing cert too, in case we want to be able to sign with intermediate CAs instead of self-signed roots.

[ca] proposal: move the RootCA key and cfssl signer object to a local signer object.

---

manager/manager.go

The CA key was recently moved inside a `Signer` object, which may
sometimes be nil. `defaultClusterObject` is called every time the manager
becomes a leader, even though its return value won't necessarily be
written to Raft. It needs to check if `Signer` is nil.
See https://github.com/docker/docker/pull/31535
cc @cyli

manager: Fix panic when Signer is nil

---

manager/logbroker/broker_test.go
manager/logbroker/subscription.go

When we're not following logs, we don't want any tasks that aren't
running yet; they don't have any logs to give us at the time of the
call. This is problematic because when a worker gets a subscription, if
that subscription includes a task that isn't running yet, it will wait
until the task is running to return logs. A task may be stuck in the
preparing state if an image takes a long time to pull, if, for instance,
if Amazon S3 were to go down.
Changes subscription to pass over adding tasks that aren't
running yet, and to add an error message explaining logs may be
incomplete.

Fixed logs hanging on preparing tasks

---

ca/config.go
ca/config_test.go
ca/transport.go
ca/transport_test.go

Rather than clone the config, since we already have utilities to create a new TLS configuration for the client and server using the TLS certs themselves and the root pool, just recreate a new TLS configuration rather than attempt to clone the existing one.
Accessing the certificates in the `tls.Config` object does not cause a data race:
```
package main_test
import (
"crypto/tls"
"fmt"
"net/http"
"net/http/httptest"
"testing"
"github.com/stretchr/testify/require"
)
// TestDockerTLSConfigClone attempts to trigger a data race when calling config.Clone while a server is running
func TestDockerTLSConfigClone(t *testing.T) {
client := http.Client{
Transport: &http.Transport{
TLSClientConfig: &tls.Config{
InsecureSkipVerify: true,
},
},
}
s := httptest.NewTLSServer(http.DefaultServeMux)
defer …
```

Do not use tlsconfig.Clone, which is unsafe in go 1.7 if the config is already being used

---

integration/cluster.go
integration/integration_test.go
manager/manager.go
manager/role_manager.go
manager/state/raft/raft.go
node/node.go

Since integration tests tests run in parallel, it can be very hard to tell which test a log line came from.
Add a "testname" field to the logger used for the tests.
Plumb context through roleManager so that its log messages will benefit from this.
Also preserve the logger in `(*Node).run` and `(*Node).runManager` so these
injected fields reach further.
I considered turning on debug logging, but it's an enormous amount of information.

integration: Improve logging
