moby/swarmkit

README.md
=> README: Update project description.

README.md
- Keep process names consistent
- Add missing command
- Consistent control socket path
Signed-off-by: Joe Gross <jgross@docker.com>
=> Fix README consistency

manager/allocator/networkallocator/networkallocator.go
Signed-off-by: Madhu Venugopal <madhu@docker.com>
=> NetworkAllocate must honor driver options

README.md
Adding crucial badge check to README.md
Signed-off-by: French Ben <frenchben@docker.com>
=> Adding missing badge-badge check

cmd/swarmctl/service/create.go, cmd/swarmctl/service/flagparser/container.go, cmd/swarmctl/service/flagparser/flags.go, cmd/swarmctl/service/flagparser/mode.go, cmd/swarmctl/service/flagparser/network.go, cmd/swarmctl/service/flagparser/placement.go, cmd/swarmctl/service/flagparser/port.go, cmd/swarmctl/service/flagparser/resource.go, cmd/swarmctl/service/flagparser/restart.go, cmd/swarmctl/service/flagparser/update.go, cmd/swarmctl/service/inspect.go, cmd/swarmctl/service/update.go
- Shared flag parsing between service create / update.
- Added a bunch of flags
@dongluochen @stevvooe Any obvious flags missing?
@vieux FYI
=> swarmctl: Expose much more functionality through flags

agent/node.go
=> Adding the path to the cert when returning LoadTLS errors

README.md, cmd/swarmctl/service/flagparser/port.go
=> README: Add more examples.

manager/controlapi/cluster.go, manager/controlapi/cluster_test.go
=> Adding a whitelist for Cluster fields to control-api

README.md
=> README: Add list of features.

agent/node.go
fixes #899
Note that to test this you need at least 3 managers.
@diogomonica 
=> Fix panic on promote after demote

BUILDING.md, README.md
=> building: add documentation on basic build steps

manager/controlapi/service.go, manager/controlapi/service_test.go
When create service or update service, should check image name. 
=> Validate image name

cmd/swarmctl/cluster/common.go, cmd/swarmctl/network/common.go, cmd/swarmctl/node/common.go, cmd/swarmctl/service/common.go
=> fix typo in error msg

agent/agent.go
This got lost in https://github.com/docker/swarmkit/commit/bdafd8beab3192d0d94d39bb8668819d327981d1#diff-6ea70e0a4de93ebcb83000a028edc163L72
ping @stevvooe 
=> Fix agent ready event

BUILDING.md
Signed-off-by: Kai Qiang Wu(Kennan) <wkq5325@gmail.com>
=> Fix the wrong format

agent/exec/controller.go
Info level messages were much too chatty. They are now debug level. The
state change log message is now in a helper function.
Addresses part of #904 
=> agent: use debug log level for task state change

ca/certificates.go
/cc @aaronlehmann for code review, @LK4D4 for the proverb review.
=> Доверяй, но проверяй - Trust, but verify.

agent/agent.go, agent/exec/controller.go
=> agent: soften up the logs

agent/exec/container/adapter.go, agent/exec/container/controller.go
Without this shutdown may get stuck in an infinite loop.
@stevvooe 
=> Skip stopped container on shutdown

manager/allocator/network.go, manager/allocator/networkallocator/networkallocator.go
Right now ingress network is not updated to store after allocation so it
fails to work properly after a restart. Fixed store update. Also
refactored network allocation to properly populate all the runtim state
of IPAM in the network.
=> Update ingress network in store after allocation

agent/agent.go
The sessionq allows access to the session. Previously, it was
initialized at startup. Now we only set while there is a current session
registration active, avoiding errors while sending status updates.
cc @icecrime @aluzzardi
=> agent: session available too early

manager/controlapi/node.go, manager/controlapi/node_test.go
Refuse to demote the last manager standing.
/cc @abronan @aaronlehmann @icecrime @tonistiigi
=> api: Node demotion sanity checks.

README.md
Signed-off-by: Xiaoxu Chen <chenxiaoxu14@otcaix.iscas.ac.cn>
=> update readme : display of "swarmctl node ls" is not correct

agent/agent.go, agent/node.go, agent/task.go, agent/worker.go
@diogomonica @aluzzardi @aaronlehmann @LK4D4 PTAL
=> agent: mark logs with modules

agent/exec/container/adapter.go
Follow up to #919 
cc @stevvooe 
=> Using ptypes conversion function for stop grace period

manager/controlapi/network.go, manager/controlapi/network_test.go
Added checks in control api to ensure networks which are still attached to services are not removed from the store.
/cc @aluzzardi @mavenugo
=> Do not allow removal of networks in use

cmd/swarmctl/cluster/inspect.go, manager/controlapi/cluster.go, manager/controlapi/cluster_test.go
=> Removing redaction of hash to unbreak spec guarantees

manager/orchestrator/services.go
The updater's Update method was being called from inside store.Batch,
which holds the store write lock. In some cases this would call Cancel,
which blocks until goroutines from the previous update finish, and this
can deadlock since those goroutines may be blocking on acquiring the
store write lock. The solution is to call Update outside of the
store.Batch callback, since there's no reason for this to be called
inside the batch.
cc @tonistiigi
=> orchestrator: Fix service scaling deadlock

manager/scheduler/filter.go, manager/scheduler/nodeinfo.go, manager/scheduler/scheduler.go
revert [PR#903](https://github.com/docker/swarmkit/pull/903)
ping @stevvooe @aaronlehmann
=> scheduler: re-calculate avaliable resources in scheduler

agent/node.go
=> Close boltdb on node stop

agent/node.go, ca/certificates.go, ca/certificates_test.go, ca/config.go, ca/config_test.go, cmd/swarmd/main.go
@aaronlehmann @diogomonica 
Docker changeset: https://github.com/docker/docker/commit/b40d97676428cc2dc9fe730374363796dacc45b5
=> Expose membership through node api

ca/certificates.go, ca/certificates_test.go, ca/server.go
Added support for root bundles, fixed lack of chaining in some signatures, added tests.
@aaronlehmann
=> Added support for root bundles, fixed lack of chaining

manager/dispatcher/dispatcher.go
=> dispatcher: send managers list before disconnect

agent/exec/container/controller.go
=> Correct error message when unhealthy container shutdown fails

manager/controlapi/service.go, manager/controlapi/service_test.go
Service network update is not supported yet. 
cc @mrjana @aaronlehmann .
=> Reject network change in service update

ca/certificates.go, ca/config.go
GetRemoteCA and GetRemoteSignedCertificate use GRPC Pickers, which do a
pretty good job of trying different remote hosts until they find one
that accepts the connection. However, there is a case they don't cover.
If the first manager they contact was recently demoted and is in the
process of shutting down, it will accept GRPC connections, but its CA
endpoints will return errors.
To work around this corner case, add bounded retry loops around the call
sites of GetRemoteCA and GetRemoteSignedCertificates. If a call fails
with an error, fetching the cert will be retried up to 4 more times
before giving up.
Fixes #1012
=> ca: Retry certificate retrieval operations

manager/dispatcher/dispatcher.go
There are several error messages that use the phrase "unknown node".
This sounds like it's a node that's not known to the system, but it's
really a node that was moved to the UNKNOWN state.
Clarify the messages to avoid this confusion.
cc @LK4D4
=> dispatcher: Clarify "unknown node" errors

agent/node.go
It solves problem when node is still unaware of its demotion and starts
the manager again, which tries to redirect requests with an invalid role.
Also, I think it's simpler because doing less stuff(notifying only
manager role).
ping @tonistiigi
=> node: use channel instead of waitRole func

ca/server.go, manager/dispatcher/dispatcher.go
=> release lock when stopping caServer and dispatcher

manager/scheduler/indexed_node_heap.go, manager/scheduler/indexed_node_heap_test.go
=> scheduler: fix remove node

agent/node.go
On demotion-promotion it's possible that issuing of demoted certificate
will be skipped, but manager will die anyway. So runManager goroutine
won't be notified that it should restart manager, because n.role is the
same.
ping @tonistiigi @aaronlehmann
=> node: notify manager role even if it's not changed

agent/node.go
Race was between ready in select in goroutine and setting ready to nil
outside. Also I think it fixes goroutine leak on demote/promote cycles.
ping @tonistiigi
=> node: fix race in using ready chan

manager/dispatcher/dispatcher.go
=> dispatcher: release lock when throwing err

api/README.md
=> Add readme for proto

cmd/swarmctl/service/create.go, cmd/swarmctl/service/flagparser/flags.go, manager/controlapi/service.go, manager/controlapi/service_test.go
See discussion in #771, #995. Corresponding change https://github.com/docker/docker/pull/23697 on Docker CLI.
cc @aaronlehmann @aluzzardi @cpuguy83 @vieux . 
=> Block mode change at controlapi

agent/agent.go, agent/node.go, agent/session.go, agent/storage.go, agent/worker_test.go, manager/controlapi/common_test.go, manager/controlapi/service.go, manager/keymanager/keymanager.go, manager/manager.go, manager/scheduler/indexed_node_heap.go, manager/state/raft/membership/cluster.go, manager/state/raft/raft.go, manager/state/store/memory.go
in addition used endpoint spec validation
=> all: remove some unused stuff

manager/orchestrator/restart_test.go
=> Removing unused variable

manager/state/raft/raft.go
There was subtle bug in the previous implementation. In some cases(probably
raft library problem) Ready() channel was never triggered.
This is the last bug which I found with repeat running integration tests from #916 
ping @abronan @aaronlehmann
=> raft: signal about cluster leaving earlier

cmd/swarmctl/service/flagparser/restart.go
fix [comment](https://github.com/docker/swarmkit/pull/1076#issuecomment-228886595)
ping @dongluochen @aaronlehmann 
sorry for the lack of consideration and introducing this bug.
=> set RestartOnAny as default restart condition

README.md, agent/exec/container/container.go, agent/exec/executor.go, api/specs.pb.go, api/specs.proto, ca/certificates.go, ca/server.go, manager/orchestrator/global.go
=> Fixing some typos

manager/dispatcher/dispatcher.go, manager/dispatcher/dispatcher_test.go, manager/dispatcher/nodes.go
=> dispatcher: simple rate limit for sessions

manager/state/raft/raft_test.go, manager/state/raft/testutils/testutils.go
relevant #300 
I use [this](https://github.com/runshenzhu/RaftGo/blob/master/src/raft/test_test.go#L638) as a reference and port one of these tests as our stress test.
ping @abronan 
=> Raft: add stress test in raft

cmd/swarmctl/cluster/inspect.go
Before: Dispatcher heartbeat period: &{5 0}
After: Dispatcher heartbeat period: 5s
=> swarmctl: Fix dispatcher heartbeat period output

README.md, manager/scheduler/constraint.go, manager/scheduler/constraint_test.go, manager/scheduler/expr.go, manager/scheduler/expr_test.go
Lost repo connection in #846. Repost the PR.
=> Constraint fix retry

manager/orchestrator/replicated_test.go, manager/orchestrator/services.go
We already make some attempts in the orchestrator to prefer certain
tasks over others when scaling down. The current logic is focused on
maintaining balance across the various nodes when scaling down - i.e.
not killing all the tasks on one node and leaving several running on
another node.
Another useful heuristic is to prefer removing non-running tasks over
running tasks. If our number of replicas is four, and we have two
starting tasks and two running tasks, scaling down to two replicas
should prefer to preserve the running tasks instead of causing a
temporary service interruption, all other things being equal.
This change prioritizes preservation of running tasks (vs
starting/completed/failed tasks) after node balance. So if the
orchestartor has to break a tie between nodes which could …
=> orchestrator: Prefer to remove non-running tasks when scaling down

README.md
Signed-off-by: Doron Podoleanu <doronp@il.ibm.com>
=> Clearer instruction

version/cmd.go
Signed-off-by: Doron Podoleanu <doronp@il.ibm.com>
=> All other descriptions have no dot

manager/dispatcher/dispatcher.go
=> Removing nodeID from register

agent/session.go
If the manager becomes unreachable, but the TCP connection has not been
torn down, I believe this RPC call would hang. Add a timeout so that if
the RPC is not serviced in a reasonable amount of time, this will cause
the agent to failover to a different manager.
See https://github.com/docker/docker/issues/24329
cc @stevvooe @abronan @tonistiigi
=> agent: Add a timeout for Heartbeat RPC

agent/session.go
Streams can't have a deadline per Recv call, so it's not correct to use
a context with a deadline in this case.
Instead, run the RPC call and first Recv in a goroutine, and time it out
if it takes too long.
cc @stevvooe @abronan @tonistiigi
=> agent: Use a goroutine to time out Session RPC

agent/exec/container/controller.go
fix #1113 
ping: @aluzzardi @stevvooe 
=> block controller.Start until container is healthy

manager/orchestrator/global.go
gccgo detected this as a no-op and refuses to compile
cc @stevvooe @aaronlehmann 
=> Fix setting cluster variable

NOMENCLATURE.md
Signed-off-by: Adam Avilla <aavilla@yp.com>
=> First pass at language clarity in NOMENCLATURE.md

manager/allocator/network.go
Global variable has problems with integration tests
ping @mrjana @aaronlehmann
=> allocator: use per-allocator ingressNetwork variable

agent/exec/container/executor.go
=> skip if engine already has overlay network plugin

manager/state/raft/membership/cluster.go, manager/state/raft/membership/cluster_test.go
If manager that is being demoted is already unreachable don't use it in quorum calculation.
cc @abronan 
=> Improve losing quorum detection on remove

manager/controlapi/node_test.go
~~Depends on #1179~~
/cc @aaronlehmann @runshenzhu 
=> raft: improve controlapi demote test to demote the leader

agent/exec/controller.go, agent/exec/controller_test.go
=> agent: timestamp task status on update

manager/orchestrator/replicated.go
Reading the code and find the `err` here we do not check.
Feel free to close this PR if have something meaningful here. :)
=> Check error when init serivce and cluster

README.md
=> Add missing period.

agent/node.go
I need this for integration tests to reliably detect if node is a
manager.
Also reordered some operations and call manager.Stop directly only once.
ping @tonistiigi @aaronlehmann
=> node: set n.manager to nil earlier

manager/manager.go
=> manager: Decrease default task retention limit.

README.md
=> Use Go instead of go in README.md

manager/dispatcher/dispatcher.go, manager/dispatcher/dispatcher_test.go, manager/dispatcher/nodes.go
Also, decrease rate limit period to match agent backoff
Fix #1183 
ping @tonistiigi
=> dispatcher: add rate limit counter

manager/state/raft/raft.go
When raft starts, the node inserts itself in the memberlist with its own
address. If the node is joining an existing cluster, this may be a
wildcard address. We need to update the node in the memberlist once we
find the real address.
=> Fix node's own address in raft memberlist

manager/manager.go
When a joining node had a particular listen address specified, but no
advertise address, the listen address was being leaked to the raft layer
instead of using remote autodetection. We should never leak the listen
address, because the advertise address how other hosts should reach the
new node.
If no advertise address is specified, change the address we pass down to
raft to `0.0.0.0:<port>`. This triggers the autodetection.
This only applies to "swarm join", since an advertise address is
*always* passed to Manager.New for "swarm init" (it may be
autodetected).
=> Allow remote address autodetection when bound to a particular address

manager/dispatcher/dispatcher.go, manager/manager.go
=> dispatcher: remove unused variable addr

agent/exec/container/controller.go
Allow `Prepare` to be properly re-entrant by forking the pull context
such that subsequent calls do not interrupt pulls. We do this by
creating a separate context for the pull that is only cancelled when
shutting down the task.
SwarmKit analog for #25043.
=> agent/exec/container: fork pull context

Makefile
Fix: https://github.com/docker/swarmkit/issues/1226
=> Fix gofmt help info

manager/manager.go, manager/raftpicker/raftpicker.go
ping @aaronlehmann @dongluochen @aluzzardi
=> raftpicker: reset connection if leader addr is changed

manager/raftpicker/raftpicker.go, manager/state/raft/raft.go
=> raftpicker: make raftpicker Stop blocking

manager/allocator/network.go
=> Fix error message

agent/agent.go
=> Fix typo in agent/agent.go

manager/dispatcher/dispatcher.go
Currently, the dispatcher Tasks loop wakes up every 50 ms to check if it
has modifications it needs to push out. This is an unnecessary wakeup on
a laptop running Docker, and potentially a lot of CPU use on a manager
servicing thousands of nodes.
This changes it to only create that timer when there are pending
modifications. It also is more efficient about reusing an existing timer
instead of creating new ones, so that 200 modifications don't result in
200 stale timers whose expiry will be ignored.
=> dispatcher: avoid creating timers when nothing has changed

cmd/swarmctl/node/remove.go
=> Adding force removal to swarmctl

ca/certificates.go, ca/config.go
=> Fixing backdating

agent/helpers.go
=> Fix typo in agent/helpers.go

cmd/swarmd/main.go
master branch is broken. This PR fixes the compiling problem.
ping @aaronlehmann @stevvooe 
=> compiling fix

log/context_test.go
Adds tests for #1302 and untested context logger.
=> log: add testing for context logger

manager/orchestrator/tasks.go
=> fix nits in log msg

agent/exec/container/adapter.go, agent/exec/container/controller_test.go, ca/config_test.go, manager/controlapi/cluster.go, manager/orchestrator/replicated_test.go, manager/orchestrator/restart_test.go
Fix a few typos and unused variable assignments.
=> Typo and unused variable fixes

manager/allocator/network.go
Fixes docker/docker#25200. This change should trigger an allocation when
the service has ports attached but the spec says none should be.
@mrjana @aaronlehmann PTAL.
=> Added check for change to 0 ports

picker/picker.go
=> Fix typo in picker/picker.go

manager/dispatcher/dispatcher.go
=> Fix typo in manager/dispatcher/dispatcher.go.

manager/allocator/doc.go
=> Fix typo in ./manager/allocatot/doc.go.

agent/exec/controller.go, api/equality/equality.go
=> agent: ignore timestamp on TaskStatus comparison

README.md
Signed-off-by: Peter Salvatore <peter@psftw.com>
=> Clean up feature list formatting.

manager/state/raft/raft.go
There is a possible deadlock on shutdown because LeaderAddr acquires
stopMu for reading, then calls WaitForLeader, which calls Leader (which
also acquires stopMu for reading). When Shutdown is called between these
read locks, Stop is blocking waiting for the readers to finish, but
Leader is blocking, preventing LeaderAddr from releasing the lock.
The isShutdown check does not look necessary anyway. If the context is
cancelled, WaitForLeader will return early, and its calls to Leader are
protected by acquiring stopMu individually. Remove the isShutdown check
and the locking that was related to it.
Fixes #1342
cc @tonistiigi @LK4D4 @runshenzhu
=> raft: Avoid double lock of stopMu

api/ca.pb.go, api/control.pb.go, api/dispatcher.pb.go, api/health.pb.go, api/raft.pb.go, manager/controlapi/hackpicker/cluster.go, manager/controlapi/hackpicker/raftpicker.go, manager/manager.go, manager/raftpicker/raftpicker.go, protobuf/plugin/raftproxy/raftproxy.go, protobuf/plugin/raftproxy/test/service.pb.go
ping @tonistiigi @aaronlehmann 
I did not try it with docker.
=> manager: use leader picker only for controlapi

manager/controlapi/service.go
This fix is related to
https://github.com/docker/docker/pull/25428
https://github.com/docker/docker/issues/25375
and:
https://github.com/docker/swarmkit/issues/1348
Basically, when service is updated, a different PortConfig might
be provided. This should be treated as an update (should be successful).
Currently, this is treated as an error in swarmkit.
This fix skips the check when comparing the PortConfig from the request
and the stored value so that the service could be updated.
=> Skip same service PortConfig check to allow PortConfig updating

ca/certificates.go, ca/certificates_test.go
Fixes #1268
/cc @aaronlehmann 
=> Add NodeID to the cert as a SAN

cmd/swarmctl/cluster/inspect.go, cmd/swarmctl/cluster/list.go, cmd/swarmctl/cluster/update.go, cmd/swarmctl/network/create.go, cmd/swarmctl/network/inspect.go, cmd/swarmctl/network/list.go, cmd/swarmctl/network/remove.go, cmd/swarmctl/node/common.go, cmd/swarmctl/node/inspect.go, cmd/swarmctl/node/list.go, cmd/swarmctl/node/remove.go, cmd/swarmctl/service/create.go, cmd/swarmctl/service/inspect.go, cmd/swarmctl/service/list.go, cmd/swarmctl/service/remove.go, cmd/swarmctl/service/update.go, cmd/swarmctl/task/inspect.go, cmd/swarmctl/task/list.go, cmd/swarmctl/task/remove.go
validate args number input of swarmkit in cli
=> validate args number input in cli

manager/orchestrator/task_reaper.go
The task reaper currently uses a ticker to check if there are dirty
tasks that might need to be reaped. This causes some unnecessary
wakeups. It's cleaner to only schedule a timer in cases where there are
dirty tasks.
This is similar to #1285.
=> task reaper: Only schedule wakeups when there are dirty tasks

manager/orchestrator/replicated.go
Fixing a bad merge where the PR was based on an out-of-date master
branch...
=> Fix compilation on master

ca/config_test.go
=> ca: do not create copy of cert

Makefile
Clean up Makfile and keep the same between rule and PHONY
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>
=> Clean up Makfile

agent/worker.go
=> agent: fix goroutine leak in worker on stop

agent/node.go
The ctx.Err() should be called after listening on ctx.Done().
It's pointed out by @stevvooe in PR #1283.
=> Fix incorrect use of ctx.Err()

manager/dispatcher/dispatcher.go
Signed-off-by: dbdd <wangtong2712@gmail.com>
=> fix comment

manager/manager.go
There is no leak on another side of channel, and it's dangerous to close
channel, so it should be collected by GC.
=> manager: fix handleLeadershipEvent leak

Godeps/Godeps.json, vendor/github.com/docker/go-events/CONTRIBUTING.md, vendor/github.com/docker/go-events/MAINTAINERS, vendor/github.com/docker/go-events/broadcast.go, vendor/github.com/docker/go-events/channel.go, vendor/github.com/docker/go-events/retry.go
It should fix races with logging.
=> vendor: update go-events

manager/state/raft/membership/cluster.go, manager/state/raft/storage.go
This may interfere with messages currently being sent to a peer.
Fixes an intermittent problem with TestRaftSnapshotRestart.
cc @nishanttotla @LK4D4
=> raft: Don't close connections when restoring from a snapshot

manager/manager.go
server.Stop closes underlying listeners
=> manager: consistent cleanup of grpc servers and listeners

manager/state/raft/raft.go
Add to zero-valued WaitGroup must be called before Wait. Also without
Lock this code is can process request after n.stop().
=> raft: fix race in WaitGroup usage

manager/state/raft/raft.go
I'm not sure where exactly deadlock is, but it's reproducible with integration tests 100%.
=> raft: fix stopMu deadlock

Godeps/Godeps.json, vendor/github.com/cloudflare/cfssl/certdb/README.md, vendor/github.com/cloudflare/cfssl/config/config.go, vendor/github.com/cloudflare/cfssl/errors/error.go, vendor/github.com/cloudflare/cfssl/helpers/helpers.go, vendor/github.com/cloudflare/cfssl/initca/initca.go, vendor/github.com/cloudflare/cfssl/log/log.go, vendor/github.com/cloudflare/cfssl/signer/local/local.go, vendor/github.com/cloudflare/cfssl/signer/signer.go, vendor/github.com/google/certificate-transparency/go/client/logclient.go, vendor/github.com/google/certificate-transparency/go/serialization.go
...and update its certificate-transparency dependency to match the
vendored version.
This fixes a data race I've been running into.
=> Revendor cfssl

agent/node.go, manager/manager.go
It's removed in the release of grpc. I've used health checking api to detect
when the connection is ready. DialContext might be a better choice, but it's
still experimental and we had painful experience with such things
before.
ping @tonistiigi @aaronlehmann
=> node: do not use conn.State

manager/dispatcher/nodes.go
=> fix minor nits in comment

manager/orchestrator/updater.go
The updater would incorrectly skip moving the new task to RUNNING if it
was replacing a task that had a desired state other than RUNNING. Fix
this to always move the new task to RUNNING.
This also fixes a case where the updater might move a preexisting task
to RUNNING before the running task in the slot had been shut down.
I could reproduce the problem on master every time I tried:
```
$ swarmctl service create --name foo --image busybox --args top --replicas 5
$ # wait for service to start, then:
$ swarmctl service update --update-parallelism 1 --update-delay 5s --args foobar foo
$ # wait a few seconds, then:
$ swarmctl service update --update-delay 5s --args top foo
$ # the service ends up with one task stuck in READY:
$ ./bin/swarmctl service inspect foo
ID                   : …
```
=> updater: Avoid getting tasks stuck in READY

manager/state/watch/watch.go
Sometimes, if an event is being written during the moment when a sink is
removed from the broadcaster, it triggers a long and scary log message
saying that an event was dropped. In the use of go-events in this watch
package, it's expected for this event to be dropped, because we are
closing down the sink and not intending to receive further events on it.
Add a wrapper around the channel that makes Write succeed even if
ErrSinkClosed is returned.
cc @stevvooe @diogomonica
=> watch: Drop ErrSinkClosed return values from Write

manager/dispatcher/dispatcher_test.go
We don't allow a task's state to move backwards. Add a test case that
makes sure this is enforced.
=> dispatcher: Add test case for moving a task's state backwards

Godeps/Godeps.json, vendor/github.com/boltdb/bolt/README.md, vendor/github.com/boltdb/bolt/appveyor.yml, vendor/github.com/boltdb/bolt/bolt_amd64.go, vendor/github.com/boltdb/bolt/bolt_arm.go, vendor/github.com/boltdb/bolt/bolt_arm64.go, vendor/github.com/boltdb/bolt/bolt_ppc.go, vendor/github.com/boltdb/bolt/bolt_ppc64.go, vendor/github.com/boltdb/bolt/bolt_s390x.go, vendor/github.com/boltdb/bolt/bolt_unix.go, vendor/github.com/boltdb/bolt/bolt_unix_solaris.go, vendor/github.com/boltdb/bolt/bolt_windows.go, vendor/github.com/boltdb/bolt/bucket.go, vendor/github.com/boltdb/bolt/db.go, vendor/github.com/boltdb/bolt/errors.go, vendor/github.com/boltdb/bolt/freelist.go, vendor/github.com/boltdb/bolt/node.go, vendor/github.com/boltdb/bolt/page.go, vendor/github.com/boltdb/bolt/tx.go
In the interest of good hygiene, pull in recent changes to boltdb. These
should be backwards compatible.
=> vendor: update boltdb dependency

manager/controlapi/service.go
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>
=> Change Parse to ParseNamed to remove extra import

agent/node.go
Fixes #1409 .
The manager part could exit due to various reasons including
demotion, raft node failure or Stop call. Upon raft node failure,
it would be meaningless to wait for role change to agent. We
should either recover or fail out. This patch chose the later
approach.
Pointed out by @tonistiigi in PR #1283.
=> Agent: handle errors of manager run

circle.yml
=> CI: Switch to protobuf 3.0.2 (stable).

circle.yml
=> CI: Update to go 1.7.1

README.md
Fixes #1521 
Signed-off-by: Michel Vocks <michelvocks@gmail.com>
=> Fixes #1521. Added protobuf 3.x to build requirements list

manager/allocator/networkallocator/portallocator_test.go
=> add portallocator test

.github/ISSUE_TEMPLATE.md
=> Make it even more clear where to file bugs

ca/certificates.go, ca/config.go, ca/external.go, ca/server.go, ca/testutils/cautils.go, ca/testutils/externalutils.go, ca/transport.go
Wrap errors with github.com/pkg/errors instead of using fmt.Errorf.
cc @stevvooe @diogomonica
=> ca: Use errors.Wrap

manager/scheduler/nodeinfo_test.go
=> add nodeinfo test

agent/config.go, agent/exec/container/adapter.go, agent/exec/container/errors.go, agent/node.go, cmd/swarmctl/service/flagparser/port.go, manager/dispatcher/dispatcher.go, manager/keymanager/keymanager.go, manager/state/raft/testutils/testutils.go
Change other code not covered by specific PRs to use errors.Wrap.
cc @stevvooe @LK4D4
=> all: Use errors.Wrap

agent/node.go
rewrite part of NewNode to handle all kinds of err
In the origin code, if `os.IsNotExist(err)` is true, it will ignore the err. 
=> rewrite part of NewNode to handle all kinds of err

manager/allocator/networkallocator/networkallocator.go, vendor.conf, vendor/github.com/docker/docker/pkg/plugins/client.go, vendor/github.com/docker/docker/pkg/plugins/discovery.go, vendor/github.com/docker/docker/pkg/plugins/discovery_unix.go, vendor/github.com/docker/docker/pkg/plugins/discovery_windows.go, vendor/github.com/docker/docker/pkg/plugins/errors.go, vendor/github.com/docker/docker/pkg/plugins/plugins.go, vendor/github.com/docker/docker/pkg/plugins/transport/http.go, vendor/github.com/docker/docker/pkg/plugins/transport/transport.go, vendor/github.com/docker/docker/plugin/getter/interface.go, vendor/github.com/docker/libnetwork/bitseq/sequence.go, vendor/github.com/docker/libnetwork/client/mflag/LICENSE, vendor/github.com/docker/libnetwork/datastore/datastore.go, vendor/github.com/docker/libnetwork/discoverapi/discoverapi.go, vendor/github.com/docker/libnetwork/driverapi/driverapi.go, vendor/github.com/docker/libnetwork/drvregistry/drvregistry.go, vendor/github.com/docker/libnetwork/ipamapi/contract.go, vendor/github.com/docker/libnetwork/ipamutils/utils.go, vendor/github.com/docker/libnetwork/netlabel/labels.go, vendor/github.com/docker/libnetwork/types/types.go
This is primarily to update driverapi, drvregistry and ipamapi, which
changed for pluginv2 support.
Signed-off-by: Anusha Ragunathan <anusha@docker.com>
=> Vendor libnetwork changes.

manager/controlapi/service.go, manager/state/store/networks.go
Signed-off-by: Alessandro Boch <aboch@docker.com>
=> Do not allow service creation on ingress network

agent/node.go, integration/api.go, integration/cluster.go, integration/exec.go, integration/integration_test.go, integration/node.go, manager/manager.go
Old integration tests don't work for some time, and it makes sense to test nodes now because that's entity in store.
Update: It passes every time.
=> add simple integration tests

agent/worker.go
Commit cb2eb0afbe49278b53a23648ae5e4cf91b3ac664 changed the agent to use a []api.Task instead of []*api.Task. This looked like an innocent change, but it causes very strange behavior. I think the problem is that some functions store the task pointer we pass it. Any reads from this pointer after the loop has advanced would read from the wrong task, since the pointer points to the task iterator.
Changing this back to []*api.Task.
Fixes #1613
cc @cyli
=> agent: Avoid task confusion

integration/cluster.go
Should fix flaky demotion tests with `unexpected error`.
=> integration: wait for role change

manager/state/raft/raft.go
* Embed raft_id to each log message
* Use logrus WithError feature
There is no logger in grpc contexts, so use just `n.Ctx`.  Also `n.Config.Logger` not flexible enough and there is no point in using it.
=> raft: use more structured logging

manager/manager.go
This should allow us to finish all controlapi calls
This is sort of "server-side defer connection closing". It should help with flaky demote integration tests.
=> manager: use GracefulStop

agent/errors.go, cmd/swarmd/main.go, integration/node.go, node/node.go
=> node: move Node to its own package

manager/manager.go
This nil check does not accomplish anything.
=> manager: Remove superfluous nil check

agent/exec/controller_test.go
=> Fix lint errors in checkDo

integration/cluster.go, integration/node.go
=> integration: remove SetAcceptancePolicy

manager/state/raft/raft.go
The integration tests found a problem when demoting the leader.
Sometimes the remaining members wouldn't know that the leader had been
demoted, and would lose quorum. This is despite the leader waiting until
the commit messages have been sent out to followers.
It turns out that all messages are sent concurrently, and this can
scramble their order. If a follower receives messages out of order, it
will reject the one that was supposed to come later. Normally this is
solved through retransmits, but that's not possible when the leader was
just demoted.
To solve this problem, and to avoid a lot of unnecessary retransmits in
general, only send one message at a time to any particular node. Do this
by setting up a chain of goroutines that each wait on the previous one
to finish. Arguably this …
=> raft: Send messages in order

ca/certificates.go
=> ca: Remove unnecessary cast

identity/randomid.go
The current identity package generates 16 bytes of entropy to fill in 25
base-36 characters. There is a slight mismatch between these - 25
base-36 characters actually corresponds to about 129.25 bits. This means
there will always be a leading 0 bit in the generated ID. The
user-facing consequence is that IDs always start with [0-9a-f], which
makes partial IDs less effective since the first digit is much more
likely to collide.
To fix this, generate an extra byte of entropy, and render the result
into a base-36 string with one extra character. Discard the leading
character, which will have a limited range. The returned 25 characters
should have uniform values.
cc @stevvooe @diogomonica
=> identity: Extend random ID domain to fill all 25 characters

manager/controlapi/secret.go, manager/controlapi/secret_test.go
This reverts commit 16729807bfa45aa5a5c9a342cb2363278b7481ec.
=> Revert "Allowing GetSecret to return the secret data"

README.md, manager/constraint/constraint.go, manager/scheduler/constraint_test.go
=> Support constraint on platform architecture and OS

ca/certificates.go
=> ca: downweight peer on grpc error in GetRemoteSignedCertificate

manager/manager.go, node/node.go, xnet/xnet_unix.go, xnet/xnet_windows.go
Integrate xnet package into the modern code
xnet package was authored by Chanwit Kaewkasi <chanwit@gmail.com>. Integration is largely also based his work PR #941. This is a separate commit because a rebase was prohibitively difficult
I can break this into two different commits, one with him as author, if he approves, so he gets git credit for his added code. I did this locally but then reverted it because of potential legal issues (and I didn't want to put words in his mouth). 
=> Support Windows Named Pipe REDUX

manager/controlapi/service.go, manager/controlapi/service_test.go
=> Fix lack of checking for secretName default in target conflict

manager/manager.go
Replace stopped channel with a bool variable and cancel top context
from Stop directly. Also, try to Stop manager cleanly after serving
error.
Fix #670 
=> manager: fix Run error on clean shutdown

manager/controlapi/service.go, manager/controlapi/service_test.go
Checks for secret existence on `ServiceCreate` and `ServiceUpdate`
=> Check for secret existence before allowing service creation or update

manager/controlapi/service.go
=> Moving the check secret reference spec to a better location

cmd/swarmctl/service/flagparser/container.go, cmd/swarmctl/service/flagparser/flags.go
Just to keep the cli flags a little bit in since with docker counterparts. If you feel it's not needed, feel free to close this PR 👼.
🐸
=> Add --hostname flag for service creation

manager/controlapi/service.go, manager/controlapi/service_test.go
This make the validation not fail when using templating when creating a Service. It populates the context with fake data and validate that the result is valid 🐯.
```bash
λ ./bin/swarmctl service create --name test --hostname "{{.Service.Name}}-{{.Task.Slot}}" --image busybox --command top
Error: ContainerSpec: {{.Service.Name}}-{{.Task.Slot}} is not valid hostname
λ ./bin/swarmctl service create --name test --hostname "{{.Service.Name}}-{{.Task.Slot}}" --image busybox --command top
hksc6qwxw82mgysel09wfq1w4
```
This is kinda required for docker/docker#28025 👼
/cc @stevvooe @aaronlehmann @aluzzardi 
🐸
=> Fix validation when templating is used on Tasks

manager/allocator/networkallocator/drivers_network.go, vendor.conf, vendor/github.com/docker/libnetwork/bitseq/sequence.go, vendor/github.com/docker/libnetwork/datastore/datastore.go, vendor/github.com/docker/libnetwork/discoverapi/discoverapi.go, vendor/github.com/docker/libnetwork/drivers/overlay/ovmanager/ovmanager.go, vendor/github.com/docker/libnetwork/drivers/remote/driver.go, vendor/github.com/docker/libnetwork/idm/idm.go, vendor/github.com/docker/libnetwork/ipam/allocator.go, vendor/github.com/docker/libnetwork/ipam/store.go, vendor/github.com/docker/libnetwork/ipams/builtin/builtin_windows.go, vendor/github.com/docker/libnetwork/ipams/remote/remote.go, vendor/github.com/docker/libnetwork/ipams/windowsipam/windowsipam.go
Windows will use the same overlay-manager and remote drivers.
Signed-off-by: Madhu Venugopal <madhu@docker.com>
=> Including windows to use the overlay and remote driver

manager/allocator/networkallocator/drivers_unsupported.go
Signed-off-by: msabansal <sabansal@microsoft.com>
=> Fixing build break for windows

manager/controlapi/service.go
With a more restrictive `ingress` network, which doesn't support SD and or `--network`, there is no reason to restrict `--publish` options for `dnsrr` mode for other back-end networks for publish-mode `host`. This will also help with the upcoming `--publish-host` functionality in windows.
=> Return error if endpoint-mode is dnsrr and publish-mode is ingress

manager/manager.go
Node can hang forever on WaitForLeader or WaitForCluster without context
cancellation which happens in m.Stop(). So, just stop kek watches on
same context cancellation.
=> manager: fix deadlock in waiting for kek to stop

manager/state/raft/raft.go
`saveToStorage` would ignore the errors returned by function calls, and
return its own, hardcoded errors. This makes debugging difficult. Also,
the errors it returned were misleading in some cases.
=> raft: Don't discard error strings

CONTRIBUTING.md, agent/agent.go, agent/exec/container/controller_test.go, agent/secrets/secrets.go, api/dispatcher.pb.go, api/dispatcher.proto, api/equality/equality.go, api/objects.pb.go, api/objects.proto, api/specs.pb.go, api/specs.proto, design/nomenclature.md, manager/deks_test.go, manager/scheduler/constraint_test.go, manager/state/raft/raft.go
Found some misspelled word with [client9/misspell](https://github.com/client9/misspell)
=> Fixed misspelling 

manager/controlapi/cluster.go, manager/controlapi/node.go, manager/controlapi/secret.go, manager/controlapi/service.go
simplify error dealing for api handler
=> simplify error

manager/controlapi/service.go
This is linked to https://github.com/docker/docker/issues/28985 and the associated PR(s) in `docker/docker` https://github.com/docker/docker/pull/28988 (and the same for 1.12.x).
This is to take care/discuss https://github.com/docker/docker/pull/28988#issuecomment-264281765
Ideally, if this is merged, should also be backported to 1.12.x :angel:.
/cc @stevvooe @tiborvass @aluzzardi 
🐸
=> Remove hostname validation

manager/state/raft/storage_test.go
When stress-testing raft encryption key rotation, wait for cluster to stabilize before restarting.
Because we're restarting as fast as possible and advancing the lcock, this may trigger leader election if one of the nodes doesn't respond quickly enough, which could happen because of the higher load.
If leadership changes, the proposer will no longer be able to propose because the leader may have changed.  
To try to avoid race conditions in the test, wait until the cluster has stabilized before restarting a node and also before proposing more values.
=> Make the raft encryption key stress test less aggressive

Makefile
Signed-off-by: Dominik Dingel <dingel@linux.vnet.ibm.com>
=> Enable race detection only on amd64 architectures

manager/allocator/networkallocator/networkallocator.go
This fix tries to fix the issue raised in:
https://github.com/docker/docker/issues/29044
where the IPAM options is missing in swarm network mode after the service is deployed.
Before the service is deployed, the IPAM options is available though.
The reason is that when network allocator updates the network, the IPAM.Options is not updated.
This fix fixes this issue.
This fix is also related to docker PR:
https://github.com/docker/docker/pull/29074
=> Fix missing IPAM options in swarm network mode

manager/state/raft/raft.go
=> raft: Remove outdated TODO

ca/server_test.go
This test fails intermittently for me when running locally, although it doesn't seem to have been spotted in CI before.
=> Poll instead of sleep in TestNewNodeCertificateRequiresToken

manager/state/raft/raft.go
This comment had become outdated. The old data is now deleted.
cc @cyli
=> raft: Correct comment

manager/logbroker/broker.go
Fix an issue reported by lint. Somehow I don't remember seeing this in CI.
=> Lint fix for logbroker

manager/orchestrator/replicated/replicated.go, manager/orchestrator/replicated/tasks.go
Signed-off-by: zhukj <zhu.kunjia@zte.com.cn>
Modify the wrong character.
=> Modify the wrong character

integration/integration_test.go
This test checks two important things:
* that workers are fast enough to reconnect to another manager
* that manager properly joins cluster after restart
=> integration: add restart leader test

manager/logbroker/broker_test.go
TestLogBrokerNoFollow was fixed to allow time for the log listeners to
be registered before creating a "no follow" subscription, however the
other NoFollow tests have the same problem. Add sleeps to those as well.
Allow these tests to run in parallel to make the sleeps a bit less
painful.
Fixes #1840
=> logbroker: Fix other flaky tests

agent/worker.go
The agent will warn about the executor not supporting secrets whenever
it receives an assignments update from the dispatcher. This adds a lot
of noise to logs from things like integration tests.
Instead of warning every time, we should only warn when the assignment
set contains at least one secret addition or removal.
=> agent: Quiet warning about executor support for secrets

agent/worker.go, ca/auth.go, ca/server.go, manager/allocator/networkallocator/networkallocator.go, manager/allocator/networkallocator/portallocator.go, manager/manager.go, remotes/remotes.go
fix typo in func comments.
Signed-off-by: zhukj <zhu.kunjia@zte.com.cn>
=> fix typo in func comments

manager/state/raft/raft.go
=> raft: update peer on applyNodeUpdate

manager/state/raft/transport/peer.go, manager/state/raft/transport/transport.go
Also reduce log severity for failed sends
=> Fix connection leak in transport

connectionbroker/broker.go
=> connectionbroker: fix weight observing on close

manager/scheduler/nodeinfo.go, manager/scheduler/scheduler.go, manager/scheduler/scheduler_test.go
fix repeated method,and fix typo in func comments.
Signed-off-by: zhukj <zhu.kunjia@zte.com.cn>
=> fix repeated method

agent/exec/container/container.go, agent/exec/controller_test.go
Signed-off-by: kaiwentan <kaiwentan@harmonycloud.cn>
=> fix the misspells in agent

ca/certificates.go, ca/certificates_test.go
`NewRootCA` already does, and this would be needed to support root CA rotation.
=> Update `ca.GetRemoteCA` to support root bundles

manager/dirty_test.go
=> manager: Fix test build failure

agent/agent.go
A data race is possible when the agent leaves the cluster. `Leave` calls `Wait`, but `Wait` may race with starting a new worker when an assignment is accepted. The existing code signals to the agent's main loop to stop accepting assignments, but this isn't quite enough because an assignment may be received at the same time as this signal. Wait for the main loop to stop accepting assingments before calling `Wait`.
Fixes #1921
=> agent: Leave should wait for the agent to stop accepting assignments

design/topology.md
cc @aluzzardi @dongluochen @stevvooe
=> design: add topology-aware scheduling proposal

agent/agent.go, agent/exec/errors.go
Signed-off-by: kevinetc123 <kaiwentan@harmonycloud.cn>
=> Simplify some redundant code

agent/exec/container/container_test.go, agent/storage_test.go, api/naming/naming.go, ca/keyreadwriter.go, cmd/swarmctl/network/inspect.go, cmd/swarmctl/service/flagparser/tmpfs.go, cmd/swarmctl/service/flagparser/volume.go, design/task_model.md, manager/allocator/allocator_test.go, manager/allocator/networkallocator/networkallocator.go, manager/encryption/nacl.go, manager/scheduler/scheduler_test.go, manager/state/doc.go, manager/state/raft/storage/snapwrap.go, manager/state/raft/storage/walwrap.go, remotes/remotes_test.go
Signed-off-by: Aaron.L.Xu <likexu@harmonycloud.cn>
=> Fix typos on a project scale.

cmd/swarmctl/common/print.go
just fix a misspell
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>
=> fix misspell "relative" in print.go

agent/secrets/secrets.go
Signed-off-by: kevinetc123 <kaiwentan@harmonycloud.cn>
=> Fix some typos in secrets

README.md
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Fix port conflict in setting up a Swarm example in readme

version/cmd.go
Signed-off-by: Kei Ohmura <ohmura.kei@gmail.com>
=> swarmctl: add a validation for 'swarmctl version'

manager/orchestrator/update/updater.go
=> updater: Use correct delay value

ca/config.go
If something requested a forced certificate renewal, and the renewal
failed, RenewTLSConfig should keep trying instead of waiting for the
normal renewal interval.
This was causing a rare integration test failure on leader demotion.
There was a narrow race where the request could hit the local CA server
if the node lost leadership just at the moment that the RPC was invoked.
Losing leadership is expected now that leader demotion involves
transferring leadership.
Reduce Factor in the exponential backoff so the first few attempts will
happen more quickly.
ping @cyli
=> ca: Keep retrying on forced certificate renewal

agent/exec/container/container_test.go, api/specs.pb.go, api/specs.proto, manager/allocator/networkallocator/networkallocator.go
Signed-off-by: Aaron.L.Xu <likexu@harmonycloud.cn>
=> typo-killer,again

agent/errors.go, ca/server.go, ca/testutils/cautils.go
1.correct misspell in comment
2.use errors.New() to output err message in agent/errors.go
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>
=> correct some misspells

manager/controlapi/common.go
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Fix swarmd crash due to nil reference of unknow network plugin

cmd/swarmctl/service/flagparser/tmpfs.go
=> Remove debug print of tmpfs mount from cli

MAINTAINERS
ping @docker/core-swarmkit-maintainers @mrjana follow up to docker/docker#31580
=> update maintainers file

integration/node.go
To try and track down integration test failures such as the following:
```
time="2017-03-06T18:46:46Z" level=error msg="agent failed to clean up assignments" error="context deadline exceeded"
--- FAIL: TestPromoteDemote (72.18s)
Error Trace:    integration_test.go:284
integration_test.go:306
Error:          Received unexpected error error stop worker 67ddtxmqndb2kok8xyxksaybs: context deadline exceeded
```
...add code that will print the stack when node.Stop fails.
cc @cyli @dongluochen
=> integration: Print stack when node.Stop fails

node/node.go
Sometimes node shutdown can hang in `agent.Leave`. It turns out that the
agent main loop is stuck in `handleSessionMessage`, trying to write to
`notifyNodeChange`. The goroutine that reads from this channel may be
blocked in `forceCertRenewal` if the renewal process can't keep up (maybe
the manager has already shut down, and we're retrying several times).
Continue to consume from `notifyNodeChange` while trying to write to
`forceCertRenewal`.
Also, this goroutine should not exit until the agent is finished. Having
it exit when the context is cancelled may cause the deadlock if the
manager exits first, and the agent is stuck trying to write to
`notifyNodeChange`.
cc @cyli @tonistiigi
=> node: Consume notifyNodeChange while requesting certificate renewal

manager/dispatcher/dispatcher.go
The `SecretID` field of a `SecretReference` must contain the full ID of the
secret. controlapi will reject the `SecretReference` if it contains
something other than a valid secret ID.
The dispatcher can look up secrets using `GetSecret` instead of trying to
look them up by prefix. This simplifies the code and makes it clearer
that the prefix matching functionality is not applicable here.
=> dispatcher: Don't look up secrets by ID prefix

Makefile, circle.yml
This causes CI to check that the vendor directory is clean whenever there are changes to this directory.
=> Add vendor directory validation

manager/allocator/network.go
The allocator listens to an event stream. When it sees a task update,
for example, and the task in that event is not allocated, it will
queue the task for allocation.
The problem is that that multiple update events like this may be
received before the event corresponding to the actual task allocation.
There could be two (or more) events in a row containing the unallocated
task, both of which could potentially cause the task to receive an IP
allocation.
This problem only happens if we receive stale events after we have committed an allocation in the store. Fix it by always fetching the latest version of the object from the store. Then it's not possible to act on a stale version of a task, node, or service.
See https://github.com/docker/docker/issues/31694
cc @kleptog @aboch @dongluochen …
=> allocator: Fix duplicated allocations that leak resources

manager/manager.go, manager/manager_test.go
=> ca/manager: If the root CA key is encrypted using env vars, log deprecation warning.

ca/certificates_test.go
See https://github.com/docker/swarmkit/pull/2063/files/b727e680ab9ebed7af6d6adce830ee79b64236a4#diff-44e0960dd88d79fd9866ac818f42794e
=> Fix some test comments that got messed up.

manager/allocator/network.go
```
$ docker swarm init 
Swarm initialized: current node (u5gk7c3r86cb86skkx71q6qjz) is now a manager.
[...]
To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
$ docker network rm ingress 
WARNING! Before removing the routing-mesh network, make sure all the nodes in your swarm run the same docker engine version. Otherwise, removal may not be effective and functionality of newly create ingress networks will be impaired.\nAre you sure you want to continue? [y/N] y
ingress
$ 
$ docker network create -d overlay ovl
ldap6202px7mv3crjg0ge24q1
$ 
$ docker service create --name s0 --network ovl busybox top
error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/services/create: EOF
$ 
```
```
panic: runtime error: invalid memory address …
```
=> Avoid panic in allocateService when no ingress nw

manager/controlapi/service.go, manager/controlapi/service_test.go
This pr try to fix https://github.com/docker/docker/issues/32123
What I did:
1. fix a typo;
2. add validation for hosts in service spec;
3. add a test case for validating container Spec;
=> validate hosts in ContainerSpec

manager/dispatcher/dispatcher_test.go, manager/manager_test.go
These tests were expecting something to happen instantly or after a fixed sleep. This isn't reliable.
Fixes #2088
=> Fix a few manager tests that need polling

manager/manager.go, manager/manager_test.go
From the `DecryptPEMBLock` docs:
> If an incorrect password is detected an IncorrectPasswordError is returned. Because of deficiencies in the encrypted-PEM format, it's not always possible to detect an incorrect password. In these cases no error will be returned but the decrypted DER bytes will be random noise.
We've been seeing occasional test failures like this:
```
--- FAIL: TestManagerEncryptsDecryptsRootKeyMaterial (10.19s)
Error Trace:    manager_test.go:651
Error:          Received unexpected error root key material not decrypted yet
github.com/docker/swarmkit/testutils.PollFuncWithTimeout
/home/cyli/go/src/github.com/docker/swarmkit/testutils/poll.go:28: polling failed
```
Which can happen when we by chance get an encrypted key which, when PEM-decrypted with an empty passphrase, …
=> [ca] fix root CA key encryption rotation

node/node.go, node/node_test.go
The `Node.Role` field was added in 17.04. Managers running earlier
versions don't set this field, which triggers a certificate renewal loop
in nodes running 17.04 or later.
To fix this, trigger certificate renewals off the `DesiredRole` field as
well. This may result in an extra certificate rotation when interacting
with a current CA, since the certificate will first be renewed when
`DesiredRole` changes, then again when `Role` changes.
Also, make rotations edge-triggered based on changes in the `Role` and
`DesiredRole` fields, to avoid rotation happening repeatedly in a loop.
=> node: Support older CAs which don't set Node.Role

node/node.go, node/node_test.go
The `Node.Role` field was added in 17.04. Managers running earlier
versions don't set this field, which triggers a certificate renewal loop
in nodes running 17.04 or later.
To fix this, trigger certificate renewals off the `DesiredRole` field as
well. This may result in an extra certificate rotation when interacting
with a current CA, since the certificate will first be renewed when
`DesiredRole` changes, then again when `Role` changes.
Also, make rotations edge-triggered based on changes in the `Role` and
`DesiredRole` fields, to avoid rotation happening repeatedly in a loop.
Backport of #2126 
ping @cyli @diogomonica
=> [17.05] node: Support older CAs which don't set Node.Role

manager/state/raft/raft.go
When there hasn't been a leader for an extended period of time, assume that the swarm has lost quorum. Return a more specific error message immediately from RPCs instead of just letting RPCs timeout waiting for a leader to be elected.
DEPENDS ON #2128
cc @dongluochen @dperny @aluzzardi
=> raft: Return a more useful error message when quorum is lost

manager/manager_test.go
When polling that the key is decrypted after it is encrypted, wait
until the node is a leader first.  Otherwise, it may poll to early,
get the raft store before it has caught up with all the logs
(including the one that changes the CA key to an encrypted version)
and hence think that the key has been decrypted when it hasn't, yet.
The error in #2140 was caused by updating the cluster before the raft node became a leader - the reason it could happen was because of the above.
Fixes #2140
=> [test] Fix flaky `TestManagerEncryptsDecryptsRootKeyMaterial` test

README.md
Since it's better for high resolution screens
=> docs: change readme badge to svg

manager/controlapi/service.go, manager/controlapi/service_test.go
this is a fix for issue https://github.com/docker/docker/issues/32337.
This PR adds HeathCheck validation for swarmkit, we know that timeout, startperiod and interval should not be less than 1s, and retries should be a positive integer.
What I did:
1. add HealthCheck validation for a service create request;
2. refactor func validateContainerSpec to make it more readable.
=> Validate healthcheck in container spec

agent/agent.go
`updateNode` uses `sendError` to force a new session. The problem is that
`sendError` sends to a channel that is read by the loop which calls
`updateNode`. The channel only has a buffer of 1. If multiple errors
happen at the same time, this can cause a deadlock. One example of when
this can happen is if `nodeUpdateTicker` fires, causing the session to be
closed, and then immediately after, the select chooses
`NotifyTLSChange`, which tries to close the session a second time but
blocks.
Have `updateNode` terminate the session directly, instead of sending over
a channel to a receiver that's in the same goroutine.
Hopefully fixes problems with `TestSessionRestartedOnNodeDescriptionChange`.
cc @cyli
=> agent: Resolve deadlock in run

manager/orchestrator/replicated/update_test.go
`TestUpdaterRollbackAndPauseNoMonitor` fails sometimes. After tens of thousands of repetitions, I can't reproduce the failure locally. This adds some debugging to capture information about the failure.
=> orchestrator: Add test debugging

manager/manager.go, manager/metrics/collector.go, node/node.go, vendor.conf, vendor/github.com/docker/go-metrics/LICENSE.code, vendor/github.com/docker/go-metrics/LICENSE.docs, vendor/github.com/docker/go-metrics/NOTICE, vendor/github.com/docker/go-metrics/README.md, vendor/github.com/docker/go-metrics/counter.go, vendor/github.com/docker/go-metrics/docs.go, vendor/github.com/docker/go-metrics/gauge.go, vendor/github.com/docker/go-metrics/handler.go, vendor/github.com/docker/go-metrics/helpers.go, vendor/github.com/docker/go-metrics/namespace.go, vendor/github.com/docker/go-metrics/register.go, vendor/github.com/docker/go-metrics/timer.go, vendor/github.com/docker/go-metrics/unit.go
Crude implementation of metrics collection in swarmkit.
This is a proof of concept
Output:
```
swarmkit_nodes_total{state="disconnected"} 0
swarmkit_nodes_total{state="down"} 0
swarmkit_nodes_total{state="ready"} 2
swarmkit_nodes_total{state="unknown"} 0
```
/cc @rogaha
=> Metrics collection

manager/allocator/networkallocator/drivers_darwin.go
=> networkallocator: Fix Mac build

manager/scheduler/scheduler_test.go
Simplify the tests by using watchAssignmentFailure instead of sleeping. This also ensures that the status message is set correctly.
=> scheduler: Use watchAssignmentFailure throughout tests

cmd/swarmd/main.go
Signed-off-by: Ali Yousuf <aly.yousuf7@gmail.com>
=> Allow Advertise Remote API address to be set from swarmd command

integration/cluster.go, integration/integration_test.go, integration/node.go
This is a followup to #2251.
Make sure that, when joining a cluster for the first time, if there are pre-generated certs in a directory if they do not match the cluster's certs, join fails immediately.
=> [tests] `TestNodeJoinWithWrongCerts`

ca/config_test.go
This failure:
```
--- FAIL: TestRenewTLSConfigUpdatesRootOnUnknownAuthError (0.22s)
Error Trace:	config_test.go:640
Error:		Received unexpected error x509: ECDSA verification failure
github.com/docker/swarmkit/ca.ValidateCertChain
github.com/docker/swarmkit/ca/_test/_obj_test/certificates.go:540: certificates do not form a chain: (1 - node0) is not signed by (2 - CA2)
```
There was a timing issue where during the renew, the CA server made a request to the external CA right before/right at the time of updating the root CA.  By the time the external CA responded, the root had already been rotated and a different intermediate had been added to the external CA, and the URL that had been hit had already been removed from the external CA.
In normal operation, RenewTLSConfig would just retry …
=> [ca/test] Fix flakey `TestRenewTLSConfigUpdatesRootOnUnknownAuthError`

manager/scheduler/nodeinfo.go
Fixes https://github.com/moby/moby/issues/33761. 
Signed-off-by: Pradip Dhara <pradipd@microsoft.com>
=> Ports are being leaked when using host publishing mode.

manager/scheduler/decision_tree.go
The function being referenced here no longer exists.
=> scheduler: Update comment

ca/external_test.go
I guess my fudge factor for the amount written wasn't big enough?  We don't know how much data
the server wrote to the socket before the client disconnected.  We can only observe that the client terminated the connection before the server finished writing, so just test that the client terminated the connection rather than how much was written by the server.
Hopefully fixes https://github.com/docker/swarmkit/issues/2312.
=> [test] Fix flakey external-ca response limit test

manager/dispatcher/dispatcher_test.go
Counting how many changes there were supposed to be pushed down to the dispatcher is kind of ugly and hard to understand - instead, force the tests to enumerate exactly what all the changes are.
cc @riyazdf
=> [tests/dispatcher] Factor the dispatcher tests to be easier to read and maintain

manager/controlapi/network.go
Added check to avoid exception
=> Fix null pointer exception

manager/controlapi/network.go, vendor.conf, vendor/github.com/golang/mock/gomock/call.go, vendor/github.com/golang/mock/gomock/controller.go, vendor/github.com/golang/mock/gomock/matchers.go
Cherry-pick docker/swarmkit/pull/2328 *Fix null pointer exception* to `bump_v17.03.3` branch.
```
$ git cherry-pick -s -x 0dcbc731b491da94cf689d33564bb6929d78fcec
```
Cherry-pick went in clean.
=> [17.03] Fix null pointer exception

README.md
=> Updated readme with instructions for adding new manager.

.github/ISSUE_TEMPLATE.md
=> Updating .github ISSUE_TEMPLATE to reflect new project links

MAINTAINERS
=> Update Misty's GitHub handle

MAINTAINERS
@anshulpundir has been working on SwarmKit regularly for the last few weeks. During this time, he has worked extensively on understanding and improving the Raft backend, Task model, and other components of the system. He has also managed to nail down multiple sophisticated bugs, and is working on fixes for several of them. He has also been very actively reviewing code, which has made it possible for the project to make faster progress.
Welcome @anshulpundir!
=> Welcome anshulpundir to MAINTAINERS

manager/controlapi/cluster.go, manager/controlapi/cluster_test.go, manager/controlapi/node.go, manager/keymanager/keymanager_test.go, manager/manager.go, manager/orchestrator/global/global.go, manager/orchestrator/replicated/services.go, manager/orchestrator/update/updater_test.go
Backport the fix to 17.06 branch
(cherry picked from commit 0b078d10da563bd8c1d4f3a795a81a5d2dbf5232)
Cherry picked cleanly.
=> Backport Error on cluster spec name change.

circle.yml
=> Update protobuf to 3.5.0

manager/dispatcher/dispatcher.go, manager/state/raft/raft.go, manager/state/raft/storage.go, manager/state/store/memory.go
Added latency metrics for raft propose latency, snapshot, scheduling delay, store related stuff etc.
=> Manager Instrumentation

circle.yml
release notes: https://golang.org/doc/devel/release.html#go1.9.minor
full diff: https://github.com/golang/go/compare/go1.9.2...go1.9.3
ping @nishanttotla @anshulpundir
=> Bump Go to 1.9.3

manager/allocator/allocator_test.go, manager/allocator/network.go, manager/allocator/networkallocator/networkallocator.go
git cherry-pick bd4e923c241ff1f9a493eab02125edbf6ec0b901
Cherry pick was not clean.
=> Fix IP overlap with empty EndpointSpec

node/node.go
Adds a great number of comments in (*Node).run, (*Node).runAgent, (*Node).managerSupervise, and (*Node).managerRun, to explain the process, both for my benefit in understanding the code exactly, and for the benefit of anyone who comes to look at it later. Detailed, but not redundant.
This is done as part of an effort to build understanding of the lifecycle of the Node and its components, to eventually fix bugs in the promote/ demote workflow.
Easy merge, no code changes.
/cc @aaronlehmann, if you'd like to review, because I believe you have the best understanding of this section of the code.
=> Add comments to Node object

cmd/swarmd/main.go, manager/state/raft/raft.go
Cherry pick of #2564 
Cherry pick was **clean**
(cherry picked from commit 03c508a9fe108ebd861163c2e3f9a4a5c8d159b5)
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>
=> [17.06] [state/raft] Increase raft ElectionTick to 10xHeartbeatTick.

LICENSE
Fixes #2588 
Signed-off-by: Sven Popping <sven@popping.co>
=> Add company and date to license

api/types.pb.go, api/types.proto
From discussion with @stevvooe.
=> Add comment on which component is responsible for updating which task states

.github/PULL_REQUEST_TEMPLATE.md
Added a PR template, that would help gain information in a structured way when new PRs are submitted. Mainly, this will help make sure we always include brief info on how to test a change.
I more or less copied the PR template from moby/moby.
By submitting a PR (after this one).
Adding a new PR template.
=> Adding Pull Request Template

manager/allocator/allocator_test.go, manager/allocator/network.go
When 9fa9ce1b (https://github.com/docker/swarmkit/pull/2363) was added, one of the changes that it introduced was to
allocate an IP address per node in the network for each network that the
node was attached to.  While this was a safe approach from a code
standpoint, it causes problems when upgrading to CE from older versions
because users that have networks allocated at near capacity suddenly
find their existing networks failing due to a lack of IP addresses.  This patch reverts allocation behavior for 18.03 to its previous state.
This patch adjusts the behavior of swarmkit so that it only allocates
these extra IP addresses if the node is known to actually need it.  This
occurs when the network being attached to is marked as Ingress or when
the node is …
=> Avoid allocating IP node addrs when not required (bump_v18.03)

manager/orchestrator/taskreaper/task_reaper.go, manager/orchestrator/taskreaper/task_reaper_test.go, vendor/github.com/docker/docker/contrib/README.md, vendor/github.com/docker/docker/contrib/nnp-test/nnp-test.c, vendor/github.com/docker/docker/contrib/syscall-test/acct.c, vendor/github.com/docker/docker/contrib/syscall-test/appletalk.c, vendor/github.com/docker/docker/contrib/syscall-test/exit32.s, vendor/github.com/docker/docker/contrib/syscall-test/ns.c, vendor/github.com/docker/docker/contrib/syscall-test/raw.c, vendor/github.com/docker/docker/contrib/syscall-test/setgid.c, vendor/github.com/docker/docker/contrib/syscall-test/setuid.c, vendor/github.com/docker/docker/contrib/syscall-test/socket.c, vendor/github.com/docker/docker/contrib/syscall-test/userns.c, vendor/github.com/opencontainers/runc/libcontainer/nsenter/README.md, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_gccgo.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c, vendor/golang.org/x/crypto/otr/libotr_test_helper.c, vendor/golang.org/x/crypto/otr/otr.go, vendor/golang.org/x/crypto/otr/smp.go, vendor/golang.org/x/sys/windows/svc/event.go, vendor/golang.org/x/sys/windows/svc/go12.c, vendor/golang.org/x/sys/windows/svc/go12.go, vendor/golang.org/x/sys/windows/svc/go13.go, vendor/golang.org/x/sys/windows/svc/security.go, vendor/golang.org/x/sys/windows/svc/service.go, vendor/golang.org/x/sys/windows/svc/sys_386.s, vendor/golang.org/x/sys/windows/svc/sys_amd64.s
PRs included:
https://github.com/docker/swarmkit/pull/2675
https://github.com/docker/swarmkit/pull/2666
https://github.com/docker/swarmkit/pull/2669
Cherry pick was not clean.
Also includes a vendoring change since 17.06 was recently reset back in time.
=> [17.06] Backport taskreaper fixes

MAINTAINERS
I have been unable to perform maintainer duties over the last few months and would like to step down. Thank you everyone for the wonderful journey, it's been a great experience and I will miss it.
Ping @anshulpundir @dperny @chungers
=> Remove nishanttotla from MAINTAINERS

manager/allocator/network.go
Somehow it's possible for tasks to be deleted in between the time that the task is allocated and the time that the task update is committed to the store. Previously, if that happened, the network resources would just get dropped (although they would be freed back up on leadership change).
With this change, if we try to commit a task but find it no longer exists, we should deallocate its resources.
=> [bump_v17.06] Fix leaking task resources

manager/controlapi/service.go, manager/controlapi/service_test.go
Addresses https://github.com/moby/moby/issues/38140. Relates to https://github.com/moby/moby/pull/38142
=> Return correct error-codes on conflicting names

manager/allocator/cnmallocator/networkallocator.go, manager/allocator/network.go, manager/controlapi/cluster.go, manager/manager.go, node/node.go, vendor.conf, vendor/github.com/docker/libnetwork/drivers/overlay/overlayutils/utils.go
Some review comments came in very late after merging
1. API name change in Libnetwork Library
Signed-off-by: selansen <elango.siva@docker.com>
=> VXLAN port configuration - late review comments update

agent/exec/controller_test.go, design/task_model.md
Fix some typos:
1. "becaused" to "because" in line 406.
2. "becacuse" to "because" in line 145.
=> Fix some typos

manager/orchestrator/restart/restart.go
Small change to refactor a condition in the restart supervisor's shouldRestart method. The old condition made my brain hurt. This should make it easier for everyone to understand.
Skipping the usual pull request boilerplate because this is such a tiny refactor with no user-facing impact, which passes the unit tests.
=> Refactor condition in restart supervisor

manager/orchestrator/update/updater.go
See https://github.com/moby/moby/pull/38520 for some background on this change
In situations where only annotations of a service are updated, SwarmKit never
marks a service as `UpdateStateUpdating`; the service's `UpdateStatus` is set
to `nil`, and never updated after.
Because of this, it's not possible to verify if an update actually happened /
reconciled, unless resorting to hacky solutions, such as comparing the services
`Version` before and after.
Even those hacky solutions are not useful, because this requires knowledge
about _which_ conditions require tasks to be updated, and which conditions not (
and require `UpdateStatus` to be checked). Such knowledge should be internal to
SwarmKit, and not needed for users of the API.
This patch modifies the behavior code to try to make this …
=> Make Service.UpdateStatus non-ambiguous

manager/allocator/network.go
=> allocator: use a map for network-IDs to prevent O(n2)

ca/testutils/cautils.go, manager/controlapi/node_test.go, manager/controlapi/server_test.go, manager/dispatcher/dispatcher_test.go, manager/logbroker/broker_test.go, manager/role_manager_test.go, manager/watchapi/server_test.go, vendor.conf, vendor/github.com/davecgh/go-spew/LICENSE, vendor/github.com/davecgh/go-spew/README.md, vendor/github.com/davecgh/go-spew/spew/bypass.go, vendor/github.com/davecgh/go-spew/spew/bypasssafe.go, vendor/github.com/davecgh/go-spew/spew/common.go, vendor/github.com/davecgh/go-spew/spew/dump.go, vendor/github.com/davecgh/go-spew/spew/format.go, vendor/github.com/stretchr/testify/LICENSE, vendor/github.com/stretchr/testify/README.md, vendor/github.com/stretchr/testify/assert/assertion_format.go, vendor/github.com/stretchr/testify/assert/assertion_forward.go, vendor/github.com/stretchr/testify/assert/assertions.go, vendor/github.com/stretchr/testify/assert/forward_assertions.go, vendor/github.com/stretchr/testify/assert/http_assertions.go, vendor/github.com/stretchr/testify/require/forward_requirements.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/github.com/stretchr/testify/require/requirements.go
- bump stretchr/testify v1.3.0 https://github.com/stretchr/testify/compare/v1.1.4...v1.3.0
- bump davecgh/go-spew  v1.1.1 https://github.com/davecgh/go-spew/compare/v1.1.0...v1.1.1
- davecgh/go-spew#79 simpler, more robust bypass
=> Bump stretchr/testify v1.3.0, davecgh/go-spew  v1.1.1

vendor/github.com/stretchr/testify/go.mod, vendor/golang.org/x/crypto/go.mod
this time on the correct branch.
=> [bump_v19.03 backport] rerun vndr to appease CI

manager/orchestrator/update/updater.go
Backport of #2862 to the bump_v19.03 branch.
=> [bump_v19.03] Revert "Make Service.UpdateStatus non-ambiguous"

manager/orchestrator/replicatedjob/orchestrator.go, manager/orchestrator/replicatedjob/orchestrator_test.go, manager/orchestrator/replicatedjob/reconciler.go, manager/orchestrator/replicatedjob/reconciler_test.go, manager/orchestrator/replicatedjob/replicatedjob_suite_test.go
Refactors the replicated job orchestrator to make testing simpler, and
then adds initialization logic to it.
=> [Jobs] Refactor replicated job orchestrator and add initialization

manager/orchestrator/replicatedjob/orchestrator.go, manager/orchestrator/replicatedjob/orchestrator_test.go, manager/orchestrator/replicatedjob/reconciler.go, manager/orchestrator/replicatedjob/reconciler_test.go
Adds the logic for handling store events to the orchestrator.
Additionally, moves the logic for retrieving the cluster object.
=> [Jobs] Add store event logic to replicated jobs orchestrator

manager/orchestrator/globaljob/orchestrator.go, manager/orchestrator/globaljob/reconciler.go, manager/orchestrator/globaljob/reconciler_test.go
Same code as #2884, just bungled it up so I had to create a new PR.
=> [Jobs] Refactor global job orchestrator

manager/controlapi/service.go, manager/controlapi/service_test.go
Adds support to the controlapi for creating and updating job-mode services. This still does not include correct plumbing to execute job-type services.
=> Add controlapi support for job services

manager/orchestrator/constraintenforcer/constraint_enforcer.go, manager/orchestrator/constraintenforcer/constraint_enforcer_test.go, manager/scheduler/nodeinfo.go, manager/scheduler/scheduler.go
Updates various components in swarmkit to work with Jobs, which have Complete as the desired terminal state.
=> [Jobs] Update components to support jobs

manager/orchestrator/jobs/orchestrator.go, manager/orchestrator/jobs/orchestrator_restart_test.go
Adds integration tests which verify that the RestartSupervisor works correctly with jobs.
=> Add tests for jobs integration with RestartSupervisor

manager/orchestrator/jobs/global/reconciler.go, manager/orchestrator/jobs/global/reconciler_test.go
Removes code from the global job reconciler that prevented global jobs from executing on newly created nodes. This behavior probably would not have worked well in real-world use, and closes off a few use cases (like using a global job to perform some initialization on newly-created nodes).
=> [Jobs] Remove global job node creation time check

manager/csi/convert.go, manager/csi/csi_mock_test.go, manager/csi/csi_suite_test.go, manager/csi/doc.go, manager/csi/fakes_test.go, manager/csi/manager.go, manager/csi/manager_test.go, manager/csi/plugin.go, manager/csi/plugin_test.go, manager/csi/secret.go
Renames the github.com/docker/swarmkit/manager/volumes package to github.com/docker/swarmkit/manager/csi, which more accurately reflects what the purpose of that package is.
=> [feature-volumes] Rename CSI volumes package

agent/agent.go, agent/agent_test.go, agent/csi/convert.go, agent/csi/plugin.go, agent/csi/plugin_fakes_test.go, agent/csi/plugin_test.go
- Adding a node plugin object
- Implementation for `NodeGetInfo` and reporting `NodeCSIInfo`
- Test using fake data
=> [feature-volumes] CSI Node Info and reporting

manager/dispatcher/assignments.go, manager/dispatcher/assignments_test.go, manager/dispatcher/dispatcher.go
Add basic handling of volumes to the dispatcher.
Creates VolumeAssignments and Secret assignments for the volumes.
=> [feature-volumes] Add basic dispatcher handling of Volumes

.circleci/config.yml, Dockerfile, agent/agent_test.go, agent/csi/plugin.go, agent/csi/plugin_test.go, agent/csi/volume_manager_test.go, agent/csi/volume_plugin_test.go, agent/csi/volumes.go, agent/dependency.go, agent/exec/executor.go, agent/worker.go, agent/worker_test.go
Expands on and finishes the code written in #2973.
=> [feature-volumes] Expand and finish #2973

agent/agent_test.go, agent/csi/plugin.go, agent/csi/plugin_test.go, agent/csi/volume_manager_test.go, agent/csi/volume_plugin_test.go, agent/csi/volumes.go, agent/dependency.go, agent/exec/executor.go, agent/worker.go, agent/worker_test.go
Adds code to handle VolumeAssignment from dispatcher on the agent side.
=> [feature-volumes]  Handle VolumeAssignment from dispatcher

agent/agent_test.go, agent/csi/plugin.go, agent/csi/plugin_fakes_test.go, agent/csi/plugin_test.go, agent/csi/volume_manager_test.go, agent/csi/volume_plugin_test.go
Adding code for plugin rpc calls on the agent side.
=> [feature-volumes] Add rpc call for agent

manager/manager.go
Signed-off-by: Adam Williams <awilliams@mirantis.com>
HeartbeatPeriod does not persist on restart.  Fixes [moby/moby issue 38321](https://github.com/moby/moby/issues/38321). On start check for stored heart beat period and use that as default if it exists.
Changed how the manager initializes the dispatcher.
1. Start daemon.
2. Set heartbeat period
3. Examine logs to validate that period is set
4. Restart daemon
5. Examine logs to validate the period persisted
HeartbeatPeriod now persists through daemon restart
=> Persist HeartbeatPeriod on restart

manager/scheduler/scheduler.go, manager/scheduler/scheduler_test.go
Fixed a bug where tasks could get stuck in the Pending state if there was no suitable node for the task.
When a task could not be scheduled, because of something like `MaxReplicas` (or, in my testing of it, the WIP Swarm Cluster Volumes functionality), it would stay in the `Pending` state forever, unable to progress but never shut down.
This change makes it so that if a Task has no suitable node, belongs to an older revision of the service, and is desired to be `Shutdown`, then the Scheduler takes initiative to move it to state `Shutdown`.
This is permissible because when the Task is in state `Pending`, it's lifecycle is under the purview of the scheduler.
Includes a new automated test. This test failed before the change, and …
=> Fix tasks getting stuck in Pending

manager/logbroker/subscription.go
Fixes a case where certain situations in the logbroker can create a deadlock. Fixes moby/moby#42314.
@xinfengliu, does this seem correct to you?
=> Fix a possible deadlock in the log broker

manager/logbroker/subscription.go
=> [bump_20.10] Fix a possible deadlock in the log broker

manager/logbroker/subscription.go
🍒:#3006 
Fixes a case where certain situations in the logbroker can create a
deadlock. Fixes moby/moby#42314.
Signed-off-by: Drew Erny <derny@mirantis.com>
(cherry picked from commit 21ba4a1f9854414996c67d2e3c2cd23e060ee9c9)
Signed-off-by: Ameya Gawde <agawde@mirantis.com>
=> [19.03 backport] Fix a possible deadlock in the log broker

manager/orchestrator/update/updater.go
Signed-off-by: Adam Williams <awilliams@mirantis.com>
Cherry pick of [3003](https://github.com/docker/swarmkit/pull/3003)
=> [bump_20.10] Fix issue where service doesn't roll back

manager/controlapi/config.go
Cherrypick [3054](https://github.com/docker/swarmkit/pull/3054) to 20.10 branch
=> [Bump_20.10] Increase max config size cherry-pick

agent/csi/volumes.go, manager/csi/manager.go
Adds a timeout to RPCs against the CSI plugin, both on the manager and on the worker. Without client-side timeouts, calls can hang open for a very long time, blocking progress on all other calls.
=> Add timeout to CSI RPCs

agent/storage_test.go, ca/certificates_test.go, ca/config_test.go, ca/keyreadwriter_test.go, ca/server_test.go, ca/transport_test.go, cmd/swarm-rafttool/common_test.go, ioutils/ioutils_test.go, manager/controlapi/ca_rotation_test.go, manager/deks_test.go, manager/dirty_test.go, manager/manager_test.go, manager/state/raft/storage/snapwrap_test.go, manager/state/raft/storage/storage_test.go, manager/state/raft/storage/walwrap_test.go, node/node.go, node/node_test.go
See individual commits for details
=> rewrite tests to use t.TempDir(), and some minor fixes

agent/exec/dockerapi/controller_integration_test.go
=> agent/exec: TestControllerFlowIntegration: replace deprecated NewClient

api/storeobject.go, manager/allocator/cnmallocator/networkallocator.go
1. "impelemented" to "implemented" in line 46.
2. "nework" to "network" in line 498.
=> Fix some typos in comment

go.mod, go.sum, vendor/github.com/docker/docker/errdefs/http_helpers.go, vendor/modules.txt
full diff: https://github.com/docker/docker/compare/v23.0.0-beta.1...v23.0.0-rc.1
=> vendor: github.com/docker/docker v23.0.0-rc.1

go.mod, go.sum, vendor/github.com/docker/docker/api/swagger.yaml, vendor/github.com/docker/docker/api/types/filters/parse.go, vendor/github.com/docker/docker/pkg/homedir/homedir_linux.go, vendor/github.com/docker/docker/pkg/homedir/homedir_others.go, vendor/github.com/docker/docker/pkg/homedir/homedir_unix.go, vendor/github.com/docker/docker/pkg/homedir/homedir_windows.go, vendor/github.com/docker/docker/pkg/plugins/discovery.go, vendor/github.com/docker/docker/pkg/plugins/discovery_unix.go, vendor/github.com/docker/docker/pkg/plugins/discovery_windows.go, vendor/github.com/docker/docker/pkg/rootless/rootless.go, vendor/github.com/rootless-containers/rootlesskit/LICENSE, vendor/github.com/rootless-containers/rootlesskit/pkg/api/api.go, vendor/github.com/rootless-containers/rootlesskit/pkg/api/client/client.go, vendor/github.com/rootless-containers/rootlesskit/pkg/api/openapi.yaml, vendor/github.com/rootless-containers/rootlesskit/pkg/port/port.go, vendor/modules.txt
full diff: https://github.com/docker/docker/compare/v23.0.0-rc.1...v23.0.0-rc.2
=> vendor: github.com/docker/docker v23.0.0-rc.2

go.mod, go.sum, vendor/modules.txt
full diff: https://github.com/docker/docker/compare/v23.0.2...v23.0.3
=> vendor: github.com/docker/docker v23.0.3

go.mod, go.sum, vendor/github.com/docker/docker/AUTHORS, vendor/github.com/docker/docker/client/container_list.go, vendor/github.com/docker/docker/client/node_list.go, vendor/github.com/docker/docker/libnetwork/datastore/datastore.go, vendor/github.com/docker/docker/libnetwork/datastore/mock_store.go, vendor/github.com/docker/docker/libnetwork/drivers/bridge/brmanager/brmanager.go, vendor/github.com/docker/docker/libnetwork/drivers/host/host.go, vendor/github.com/docker/docker/libnetwork/drivers/ipvlan/ivmanager/ivmanager.go, vendor/github.com/docker/docker/libnetwork/drivers/macvlan/mvmanager/mvmanager.go, vendor/github.com/docker/docker/libnetwork/drivers/overlay/ovmanager/ovmanager.go, vendor/github.com/docker/docker/libnetwork/drivers/remote/driver.go, vendor/github.com/docker/docker/libnetwork/drvregistry/drvregistry.go, vendor/github.com/docker/docker/libnetwork/ipams/builtin/builtin.go, vendor/github.com/docker/docker/libnetwork/ipams/windowsipam/windowsipam.go, vendor/github.com/docker/docker/libnetwork/ipamutils/utils.go, vendor/github.com/docker/docker/libnetwork/types/types.go, vendor/github.com/docker/docker/pkg/plugins/plugins.go, vendor/modules.txt
full diff: https://github.com/docker/docker/compare/b1569b9c185b...75ee002347f8eb07a1246f253222bf575b950577
=> vendor: docker/docker 75ee002347f8eb07a1246f253222bf575b950577 (25.0-dev)

ca/config.go
Latest version of grpc added more strict enforcement of ALPN
Fixes failures in https://github.com/moby/moby/pull/48872
=> Add server next protos configuration
